### ISSUE TITLE
Incompatible function arguments when enabling the auto-mix-precision

### ISSUE THREAD

**Issue by CMULiyuan** [intel/intel-extension-for-pytorch#115]
I installed PyTorch  v1.5.0 rc3 and Extension for PyTorch following the guide. However, when I tried to enable the auto-mix-precision as guided, it throws the error: 
```
TypeError: enable_auto_dnnl(): incompatible function arguments. The following argument types are supported:
    1. () -> None

Invoked with: True
```
Attached with the complete log:
```
>>> import torch
>>> import torch.nn as nn
>>> import intel_pytorch_extension as ipex
>>> ipex.enable_auto_optimization(mixed_dtype = torch.bfloat16)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/pytorchextension/lib/python3.7/site-packages/torch_ipex-1.0.0-py3.7-linux-x86_64.egg/intel_pytorch_extension/__init__.py", line 25, in enable_auto_optimization
    core.enable_auto_dnnl(True)
TypeError: enable_auto_dnnl(): incompatible function arguments. The following argument types are supported:
    1. () -> None

Invoked with: True
```
Is it because I didn't install Extension for PyTorch properly?

**Comment by EikanWang** [comment]
May I know your full python version? I didn't meet this issue, but it should be a bug of the extension. Because the extension invoked `enable_auto_dnnl` and this API should not accept any parameter.

**Comment by pinzhenx** [comment]
It's a typo in our README. It should be
```
ipex.enable_auto_mix_precision(mixed_dtype = torch.bfloat16)
```

**Comment by CMULiyuan** [comment]
> May I know your full python version? I didn't meet this issue, but it should be a bug of the extension. Because the extension invoked `enable_auto_dnnl` and this API should not accept any parameter.

My Python version is `3.7.7`. I noticed that in intel_pytorch_extension_py/__init__.py Line 24
```
if mixed_dtype != None:
    core.enable_auto_dnnl(True)
enable_auto_mix_precision(mixed_dtype)
```

**Comment by CMULiyuan** [comment]
> It's a typo in our README. It should be
> 
> ```
> ipex.enable_auto_mix_precision(mixed_dtype = torch.bfloat16)
> ```

It works. Thanks

**Comment by pinzhenx** [comment]
Actually, we should remove the `True` in the call to `core.enable_auto_dnnl()`.

After we fix that, both commands should all work.
