### ISSUE TITLE
can it support air100 or air101 ?

### ISSUE THREAD

**Issue by dsp6414** [intel/intel-extension-for-pytorch#116]
i want to develop projects on air101，how can i use this tools?

**Comment by EikanWang** [comment]
May I know what's the meaning of air101?

**Comment by dsp6414** [comment]
Intel Atom E3950+Myriad X VPU * 2

**Comment by EikanWang** [comment]
We switched the underhood device from XPU to CPU. The behavior should be as same as PyTorch. If you want to run IPEX, you can try AVX2 version.
