### ISSUE TITLE
torchvision version

### ISSUE THREAD

**Issue by ashokei** [intel/intel-extension-for-pytorch#120]
it seems the torchvision 0.7.0 requires torch > 1.6.0, can ipex use 1.6 branch of pytorch instead of 1.5. ?

Seeing below crash with IPEX.

https://github.com/pytorch/pytorch/issues/42078

**Comment by jgong5** [comment]
Oh, torchvision has multiple versions that can work with different versions of PyTorch. See

torch | torchvision | python
-- | -- | --
master / nightly | master / nightly | >=3.6
1.5.0 | 0.6.0 | >=3.5
1.4.0 | 0.5.0 | ==2.7, >=3.5, <=3.8
1.3.1 | 0.4.2 | ==2.7, >=3.5, <=3.7
1.3.0 | 0.4.1 | ==2.7, >=3.5, <=3.7
1.2.0 | 0.4.0 | ==2.7, >=3.5, <=3.7
1.1.0 | 0.3.0 | ==2.7, >=3.5, <=3.7
<=1.0.1 | 0.2.2 | ==2.7, >=3.5, <=3.7

**Comment by ashokei** [comment]
it is a workaround, i can close this issue, but we have other projects such as torchserve that just install default torchvision as part of their deployment; Due to this issue we have to patch their deployment scripts, including docker files.

**Comment by jgong5** [comment]
> we have other projects such as torchserve that just install default torchvision as part of their deployment

Do you mean torchserve requires the latest torchvision to work, or can it work with an older version of torchvision?

**Comment by ashokei** [comment]
with manual custom installation it will work. If using their default scripts, it installs torchvision 0.7.0. Not a big issue, i can close this.
