### ISSUE TITLE
question about pytorch extension

### ISSUE THREAD

**Issue by zjin-lcf** [intel/intel-extension-for-pytorch#121]
Can people run pytorch on a GPU with your DPCPP extension ?  DPCPP, which is a component in oneAPI, enables people to run a program on multiple computing platforms.  This may explain that "ipex.DEVICE" is needed although the device may be just a CPU device.

**Comment by EikanWang** [comment]
The coming IPEX 1.10 will switch the underhood device from DPCPP to CPU for the CPU device. Regarding Intel GPU, it will still reuse XPU.
