### ISSUE TITLE
RuntimeError: could not construct a memory descriptor using strides

### ISSUE THREAD

**Issue by newtdms** [intel/intel-extension-for-pytorch#128]
RuntimeError: could not construct a memory descriptor using strides

File ".../pytorch_bf16/adorym/adorym/adorym/wrappers.py", line 584, in reshape
    arr = func(var, newshape)
  File ".../python3.6/site-packages/torch_ipex-1.0.0-py3.6-linux-x86_64.egg/intel_pytorch_extension/ops/reshape.py", line 15, in reshape
    return ReshapeFunction.apply(input, size)
  File "/...anaconda3/envs/pytorch-bf16/lib/python3.6/site-packages/torch_ipex-1.0.0-py3.6-linux-x86_64.egg/intel_pytorch_extension/ops/reshape.py", line 10, in forward
    output = core.reshape(input, size)
RuntimeError: could not construct a memory descriptor using strides

**Comment by EikanWang** [comment]
The iss

**Comment by troy818** [comment]
> 



> RuntimeError: could not construct a memory descriptor using strides
> 
> File ".../pytorch_bf16/adorym/adorym/adorym/wrappers.py", line 584, in reshape arr = func(var, newshape) File ".../python3.6/site-packages/torch_ipex-1.0.0-py3.6-linux-x86_64.egg/intel_pytorch_extension/ops/reshape.py", line 15, in reshape return ReshapeFunction.apply(input, size) File "/...anaconda3/envs/pytorch-bf16/lib/python3.6/site-packages/torch_ipex-1.0.0-py3.6-linux-x86_64.egg/intel_pytorch_extension/ops/reshape.py", line 10, in forward output = core.reshape(input, size) RuntimeError: could not construct a memory descriptor using strides

Hi, I have the same issue, how do you solve it?

**Comment by troy818** [comment]
> RuntimeError: could not construct a memory descriptor using strides
> 
> File ".../pytorch_bf16/adorym/adorym/adorym/wrappers.py", line 584, in reshape arr = func(var, newshape) File ".../python3.6/site-packages/torch_ipex-1.0.0-py3.6-linux-x86_64.egg/intel_pytorch_extension/ops/reshape.py", line 15, in reshape return ReshapeFunction.apply(input, size) File "/...anaconda3/envs/pytorch-bf16/lib/python3.6/site-packages/torch_ipex-1.0.0-py3.6-linux-x86_64.egg/intel_pytorch_extension/ops/reshape.py", line 10, in forward output = core.reshape(input, size) RuntimeError: could not construct a memory descriptor using strides

Hi, I have the same issue like you. How do you fix it?

**Comment by jgong5** [comment]
@troy818 Are you using the latest IPEX? If you still encounter issues, can you share reproducer? Thanks.

**Comment by troy818** [comment]
@jgong5 Yes, my env is
```
PyTorch version: 1.13.0a0+gitb1dde16
PyTorch CXX11 ABI: Yes
IPEX version: 1.13.10+xpu
IPEX commit: 7d85b0e92
Build type: Release
```
I cannot share the reproducer, but it is a pytorch network and I use torch.jit.load and the backward function is complex.

**Comment by jgong5** [comment]
hmm, it is hard for us to triage your issue without a reproducer.
