### ISSUE TITLE
undefined symbol: sgemm_ when importing IPEX

### ISSUE THREAD

**Issue by d0u9** [intel/intel-extension-for-pytorch#136]
I build pytorch and IPEX according to the README in Ubuntu 20.04

Everything is find until I execute `import intel_pytorch_extension as ipex`.

Error reported:

```
ImportError                               Traceback (most recent call last)
<ipython-input-3-1031a6c8b3e2> in <module>
----> 1 import intel_pytorch_extension as ipex

~/.pyenv/versions/pytorch/lib/python3.7/site-packages/torch_ipex-1.0.0-py3.7-linux-x86_64.egg/intel_pytorch_extension/__init__.py in <module>
      5 from .version import __version__
      6 from .tensor import *
----> 7 from .optim import *
      8 from .ops import *
      9 import _torch_ipex as core

~/.pyenv/versions/pytorch/lib/python3.7/site-packages/torch_ipex-1.0.0-py3.7-linux-x86_64.egg/intel_pytorch_extension/optim/__init__.py in <module>
----> 1 from .split_sgd import is_available
      2 from .split_sgd import SplitSGD

~/.pyenv/versions/pytorch/lib/python3.7/site-packages/torch_ipex-1.0.0-py3.7-linux-x86_64.egg/intel_pytorch_extension/optim/split_sgd.py in <module>
      1 import torch
      2 from torch.optim.optimizer import Optimizer, required
----> 3 import _torch_ipex
      4
      5 _available = False

ImportError: /home/user/.pyenv/versions/pytorch/lib/python3.7/site-packages/torch_ipex-1.0.0-py3.7-linux-x86_64.egg/_torch_ipex.cpython-37m-x86_64-linux-gnu.so: undefined symbol: sgemm_
```

It can barely find any thing about sgemm__ symbol in Google. What happened here?

**Comment by EikanWang** [comment]
May I know your build environment? I will try to reproduce your issue. The "sgemm__" is an API of the BLAS library. May I know if your build environment contains MKL?

**Comment by d0u9** [comment]
I built pytorch and IPEX in a clean Ubuntu 20.04. I installed MKL from `l_mkl_2020.3.279.tgz` tar ball provided by Intel official site. It is notable that I installed MKL **AFTER** building pytorch and IPEX.

**Comment by mingxiaoh** [comment]
@d0u9  to install mkl, you can just try it by:
    conda config --add channels intel       
    conda install mkl mkl-include numpy -c intel --no-update-deps

**Comment by d0u9** [comment]
Is Conda compulsory? I haven't install it in my environment. I use `pyenv` and install all necessary packages manually.

**Comment by d0u9** [comment]
OK, finally Conda saves me...
