### ISSUE TITLE
Install IPEX with non-system gcc

### ISSUE THREAD

**Issue by thxst** [intel/intel-extension-for-pytorch#137]
Dear developers,
it seems to be that the installation of the IPEX always uses the (on CentOS very outdated) system's 'gcc' and does not recognize the PATH environment, e.g. if multiple compiler versions are managed by 'modules' environment tool.
Best, Th.

**Comment by EikanWang** [comment]
Thanks for your comments. If you want to use different compilers (eg. GCC, clang) or the same compiler with different versions, you can try to set the toolchain environment variable.
```bash
export CC=${YOUR_C_COMPILER_PATH}
export CXX=${YOUR_CPP_COMPILER_PATH}
```

**Comment by EikanWang** [comment]
May I know if it does work for you?

**Comment by thxst** [comment]
Thanks, it worked.
Curious observation: Compilation with Intel compiler fails (I tried it because hoping for better AVX-512 optimisation on a Intel Cascade Lake AP system (HLRN-IV @ ZIB).
