### ISSUE TITLE
Only PyTorch v1.5.0-rc3 supported?

### ISSUE THREAD

**Issue by misterbit-pro** [intel/intel-extension-for-pytorch#142]
Hello,

I would like to know if only the rc3 of the v1.5.0 is supported or are there just outdated docs and it works with the newer versions of pytorch as well?

**Comment by jgong5** [comment]
Yes, only PyTorch v1.5.0rc3 is supported now. We are in the progress of rebasing IPEX to PyTorch 1.7. Stay tuned.
