### ISSUE TITLE
Could you provide a wheel package of IPEX?

### ISSUE THREAD

**Issue by junjihashimoto** [intel/intel-extension-for-pytorch#152]
I want to evaluate IPEX, but I do not want to build IPEX by myself, because it is difficult to test the package with each xeon-processor like skylake, cascadelake and icelake.
If possible, please provide a tested IPEX wheel package.

**Comment by EikanWang** [comment]
Make sense. The IPEX plans to support binary installation for the coming release.

**Comment by junjihashimoto** [comment]
Thx! I'm grad to hear that.

**Comment by EikanWang** [comment]
May I know if I can close this issue?

**Comment by junjihashimoto** [comment]
Yes, you can.
When you release the package, would you like to let us know on twitter or facebook?

**Comment by EikanWang** [comment]
Sure. And I expect this should happen within this month.
