### ISSUE TITLE
Error while building Docker container

### ISSUE THREAD

**Issue by C24IO** [intel/intel-extension-for-pytorch#154]
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

torchvision 0.6.0+cpu requires torch==1.5.0, but you'll have torch 1.7.0a0 which is incompatible.
Successfully installed dataclasses-0.6 future-0.18.2 torch-1.7.0a0 typing-extensions-3.7.4.3
Removed build tracker: '/tmp/pip-req-tracker-gyc6n0d7'
root@9bdbfdb854fb:~/build/intel-extension-for-pytorch/pytorch#

**Comment by jingxu10** [comment]
Could you clarify this issue?
How did you get this error?

**Comment by C24IO** [comment]
Following the instructions here - https://github.com/intel/intel-extension-for-pytorch I get to this error, so switched to using the DockerFile.

**Comment by jingxu10** [comment]
got it.
Does the dockerfile solve the issue?
