### ISSUE TITLE
xpu v1.7.0 patch is incorrect

### ISSUE THREAD

**Issue by Sergey-Fokin-Orion** [intel/intel-extension-for-pytorch#165]
Steps to reproduce:
Setup: 
Windows 10

git --version
git version 2.31.1.windows.1

Perform steps from here https://github.com/intel/intel-extension-for-pytorch/blob/master/README.md :

git clone --recursive https://github.com/pytorch/pytorch
cd pytorch

# checkout source code to the specified version
git checkout v1.7.0

# update submodules for the specified PyTorch version
git submodule sync
git submodule update --init --recursive

git clone --recursive https://github.com/intel/intel-extension-for-pytorch
cd intel-extension-for-pytorch

# if you are updating an existing checkout
git submodule sync
git submodule update --init --recursive

# Apply git patch to pytorch code
cd ${pytorch_directory}
git apply ${intel_extension_for_pytorch_directory}/torch_patches/xpu-1.7.patch

Error appeared:
**error: corrupt patch at line 711**

Also, fixing this patch mannually does not help to build pytorch ipex on windows. Tried on several windows 10 PCs

**Comment by EikanWang** [comment]
Since PyTorch has supported XPU and IPEX does not patch PyTorch, the issue does not exist.
