### ISSUE TITLE
Unable to build on Windows 10

### ISSUE THREAD

**Issue by Sergey-Fokin-Orion** [intel/intel-extension-for-pytorch#166]
[log.txt](https://github.com/intel/intel-extension-for-pytorch/files/6569513/log.txt)

Installed pytorch setup from pytorch\.circleci\scripts\vs_install.ps1

Performed steps from readme.
Build logs are attached

**Comment by EikanWang** [comment]
Thanks for your report. IPEX has not supported windows yet. May I know your CPU model? I just want to check if it is a desktop CPU.

**Comment by Sergey-Fokin-Orion** [comment]
> Thanks for your report. IPEX has not supported windows yet. May I know your CPU model? I just want to check if it is a desktop CPU.

That is sad(
Tried on 
Intel(R) Core(TM) i7-8700K CPU
and on Intel(R) Core(TM) i5-8400 CPU

**Comment by ErikLundin98** [comment]
Are there any plans on implementing Windows support any time soon?

**Comment by EikanWang** [comment]
There is no detailed plan yet. Thank you for your attention. I will notify you if we have any plan for windows support.
