### ISSUE TITLE
MLCommons inference DLRM benchmark with IPEX: thread hanging problem

### ISSUE THREAD

**Issue by EtoDemerzel0427** [intel/intel-extension-for-pytorch#168]
I am trying to reproduce your benchmark experiments: https://github.com/mlcommons/inference_results_v1.0/tree/master/closed/Intel/code/dlrm-99.9/pytorch which uses IPEX. The version of IPEX it uses is:
```shell
git clone https://github.com/intel/intel-extension-for-pytorch  
cd intel-extension-for-pytorch  git checkout mlperf/inference  
git checkout 8f9402e180da8a8a60432c54d390320bac43fb11  
git log -1  
git submodule sync &amp;&amp; git submodule update --init --recursive

# install PyTorch  cd ${WORKDIR}/pytorch  
cp ${WORKDIR}/intel-extension-for-pytorch/torch_patches/0001-enable-Intel-Extension-for-CPU-enable-CCL-backend.patch .  
patch -p1 &lt; 0001-enable-Intel-Extension-for-CPU-enable-CCL-backend.patch  
python setup.py install
``` 
I strictly followed what the README instructs, and made the program run. However it turned out the program never exits: after the query workload ends, there is always a hanging thread that doesn't stop. I saw in your release you mentioned the hanging thread problem on multi-node training, is it a similar problem? Do you have any ideas on this?

**Comment by EtoDemerzel0427** [comment]
My machine is Intel Xeon 8268.

**Comment by EtoDemerzel0427** [comment]
With some effort, I found the program was blocked at https://github.com/mlcommons/inference/blob/10aa90b319bd7f921dedb6050d12041aefd75c7e/loadgen/logging.cc#L399, but still have no idea what's happening here.

**Comment by EikanWang** [comment]
May I know how often this happens? several epochs or several iterations?

**Comment by EikanWang** [comment]
@JianpingChen066, have you ever met this issue?

**Comment by EtoDemerzel0427** [comment]
@EikanWang Thanks for your reply. In fact, I was running the inference rather than the training benchmark, so there is no such thing as epochs or iterations. In my case, the lodegen can generate the queries, the model can perform inference, while in the end, the condition:
```C++
bool AllLatenciesRecorded() {    
     return latencies_recorded_ == latencies_expected_;  
}
```
never fulfilled, making the condition variable `AllLatenciesRecorded_` waiting forever.

**Comment by EikanWang** [comment]
Oh, I misunderstood. This is not the same problem that training encountered. We haven't run into this problem before. You're running DLRM inference on a single node, right?

**Comment by EtoDemerzel0427** [comment]
@EikanWang I think so, I ran it on a single HPC machine.

**Comment by JianpingChen066** [comment]
@EtoDemerzel0427 How much memory in your HPC machine ? and how do you configure the instances to run the DLRM MLPerf inference test ? on CPX machine, it will require 384G (64Gx 6) memory-per-socket and if on ICX or SPR  machine, it need 512G (64G x 8) memory-per-socket for that. If memory is not enough, please reduce the instances to try. When memory is enough, the DLRM MLPerf inference can run smoothly.

**Comment by EtoDemerzel0427** [comment]
@JianpingChen066 Hi, thanks for your reminder. I have 2T memory on that machine, specifically, 2T persistent memory running in memory mode, so I think the memory is not the problem. As for the configuration, I used the default provided in your results. The problem is that, I found that before this line, https://github.com/mlcommons/inference/blob/10aa90b319bd7f921dedb6050d12041aefd75c7e/loadgen/logging.cc#L402, the `latencies_expected_ != latencies_recorded_` (when I set `target_QPS=0`, they are 8 and 0 respectively), and this led the condition variable to wait forever.

**Comment by JianpingChen066** [comment]
The default offline configuration is for CPX 28C machine with 4S as below;
export NUM_SOCKETS=4        # i.e. 8
export CPUS_PER_SOCKET=28   # i.e. 28
export CPUS_PER_PROCESS=28  # which determine how much processes will be used 
export CPUS_PER_INSTANCE=7  # instance number=28/7=4 

So when you run with one socket, please modify the setup_env_offline.sh according to your machine configure, such as 
export NUM_SOCKETS=1
export CPUS_PER_SOCKET=24
export CPUS_PER_PROCESS=24
export CPUS_PER_INSTANCE=6

**Comment by EtoDemerzel0427** [comment]
@JianpingChen066 It turns out that I can run the offline scenario smoothly, only under the server settings, the program cannot end. I tried the suggested configuration, the problem remains.

**Comment by JianpingChen066** [comment]
Server configuration is also need to be tuned, you may try to modify as below:
export NUM_SOCKETS=1
export CPUS_PER_SOCKET=24
export CPUS_PER_PROCESS=24
export CPUS_PER_INSTANCE=12

and also need to modify the user.conf to tune the dlrm.Server.target_qps to a suitable data to meet your machine's performance, since you just have one socket for that, you may can start from dlrm.Server.target_qps=2000. The batch_size in run_main.sh also need to be adjust to meet 30ms latency requirement

**Comment by JianpingChen066** [comment]
dlrm.Server.min_query_count in user.conf also need to meet with the duration value
dlrm.Server.min_query_count = 12288000 is for duration=600000

**Comment by EtoDemerzel0427** [comment]
@JianpingChen066 Thanks for the suggestion. I changed the settings as you described,  the `max-batchsize` in run_main.sh was set 900. Also since I want a quick test, I set the duration=6000, I let the min_query_count be 122880. However, it seems nothing changed, it still cannot end. 

BTW, on my machine there are actually 4 Xeon 8268, 4 sockets, 96 physical cores and 192 virtual cores in total.

**Comment by JianpingChen066** [comment]
which loadgen version you used, is that from r1.0 ?

**Comment by JianpingChen066** [comment]
And please also to make sure dlrm.Server.min_query_count > dlrm.Server.target_qps * (duration/1000)

**Comment by EtoDemerzel0427** [comment]
@JianpingChen066 

> which loadgen version you used, is that from r1.0 ?

Actually, I tried both the r1.0 version and the newest, both have the aforementioned problem. 


> And please also to make sure dlrm.Server.min_query_count > dlrm.Server.target_qps * (duration/1000)

Yes, I do believe 122880 > 2000*(6000/1000), so this config is not wrong. I am not sure whether this situation is caused by the configs, because before I modified the default configs, the offline version is also runnable, while the server version isn't.

**Comment by EtoDemerzel0427** [comment]
This problem still remains on my new machine. I really wonder if there is any problem in server.py instead of my environment settings, as the offline.py can run smoothly. Have you tested it recently?

**Comment by JianpingChen066** [comment]
Could you access the following link :
intel-innersource/frameworks.ai.benchmarking.mlperf_inference_v1-1_submission: MLPerf Inference v1.1 pre-submission code (github.com) ?
which contain the latest scripts for mlperf v1.1 submission. we will use flush_queries to info the server queries end which may resolve the problem you meet

**Comment by EtoDemerzel0427** [comment]
Are you referring to https://github.com/intel-innersource? I am afraid there are no public repositories under this venue. You mentioned using flush_queries, so is there a quick workaround to modify the current version [here](https://github.com/mlcommons/inference_results_v1.0/tree/master/closed/Intel/code/dlrm-99.9/pytorch/python)?

**Comment by JianpingChen066** [comment]
A quick workaround may like below 
1)  define flush_queries inside class QueueRunner: 
def flush_queries(self):
            # print(self.qsize)
            for q in range(self.num_queues):
                if self.ids[q]:
                    self.inQueue.put(Item(self.ids[q], self.idxes[q]))
                    # print("Sendall in queue", q, " with total samples ", len(self.ids[q]), " qsize ", self.qsize[q])
2) then remove line 525-530 from enqueue
3) under main function's flush_queries(), add
     runner.flush_queries()

**Comment by EtoDemerzel0427** [comment]
> 3\. runner.flush_queries()

Thanks, just had time to try it, it really worked.
