### ISSUE TITLE
Unable to build docker image on Mac

### ISSUE THREAD

**Issue by msaroufim** [intel/intel-extension-for-pytorch#172]
## Repro instructions
```
cd docker
DOCKER_BUILDKIT=1 docker build --build-arg IPEX_VERSION=v1.8.0 --build-arg PYTORCH_VERSION=v1.8.0 -t intel-extension-for-pytorch:test .
```

## Suggested fix
Mention in README that machines need to support AVX 512 and a list of the machines that do support it

Digging through errors I believe this is the issue ` Please build IPEX on Machines that support AVX512.`

## Logs
https://gist.github.com/msaroufim/1efcac8eb892d313bdcd9d99f5310509

**Comment by EikanWang** [comment]
Thanks for your suggestion. @jingxu10 , could you help to update the README to point out this?

**Comment by EikanWang** [comment]
@msaroufim , could you help to check this PR(#177 )?
