### ISSUE TITLE
slower when use bfloat16

### ISSUE THREAD

**Issue by Hap-Zhang** [intel/intel-extension-for-pytorch#178]
Hi,all

I want to accelerate the inference of bert model on intel cpu(40 Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz), and try to use ipex, however something abnormal happened:
1. The inference time of original pytorch is 477ms, and faster than the version use ipex(558ms) ;
2. when i use the bfloat16, the inference time is much slower(924ms);
![image](https://user-images.githubusercontent.com/32810063/131300864-23bcc8df-c189-43ab-9bee-d4d9661b039a.png)
3. My CPU support AVX512, when i **export MKL_CBWR=AVX2**, the inference time is faster than AVX512(AVX2:390ms, AVX512:477ms)
![image](https://user-images.githubusercontent.com/32810063/131301175-45f823ad-c1b2-4933-a934-776399190627.png)

I think the conclusion of the above three points should be exactly the opposite, however, the result is not as expected.

**Comment by EikanWang** [comment]
I checked the 4114 instructions set. It does not support [BF16-VNNI](https://software.intel.com/content/www/us/en/develop/articles/intel-deep-learning-boost-new-instruction-bfloat16.html).

**Comment by EikanWang** [comment]
The FP32 GEMM in PyTorch is implemented by MKL while IPEX leverages the oneDNN. Regarding some particular shapes, the oneDNN GEMM efficiency is not as good as MKL. And oneDNN team is working on this.

**Comment by Hap-Zhang** [comment]
@EikanWang 
Thank you for your quickly reply, and i see something.
In addition, could you guide me why the inference with AVX2 is faster than AVX512, is there any problem when I use it?

**Comment by EikanWang** [comment]
If you enabled `CNR(Conditional Numerical Reproducibility)` by exporting `MKL_CBWR` to `AVX`, it means that "MKL calls return the same results on every Intel CPU that supports AVX instructions or later:". Did you try to set `MKL_CBWR` to AVX512 and collect the performance. https://software.intel.com/content/www/us/en/develop/articles/introduction-to-the-conditional-numerical-reproducibility-cnr.html

**Comment by EikanWang** [comment]
One more thing about the BF16, if you want to try BF16, you can run it with IPEX on the BF16 machine (Cooper Lake) because MKL has not supported BF16 yet.

**Comment by Hap-Zhang** [comment]
> If you enabled `CNR(Conditional Numerical Reproducibility)` by exporting `MKL_CBWR` to `AVX`, it means that "MKL calls return the same results on every Intel CPU that supports AVX instructions or later:". Did you try to set `MKL_CBWR` to AVX512 and collect the performance. https://software.intel.com/content/www/us/en/develop/articles/introduction-to-the-conditional-numerical-reproducibility-cnr.html

Yeah, i try to **export MKL_CBWR=AVX512**, and the inference time is 497ms, slower than AVX2(390ms).  In my opinion, AVX512 should get a better performance.

**Comment by EikanWang** [comment]
Yes, you are right. In general, the AVX512 should gain better performance. Let me profile the model in detail. May I know your BERT version and how I can get it?

**Comment by Hap-Zhang** [comment]
OK, of course.
My bert model is **bert-base-chinese**, which you can get from https://huggingface.co/bert-base-chinese/tree/main.
The transformer version is 4.6.1, and the pytorch version is 1.9.0.

**Comment by EikanWang** [comment]
@Hap-Zhang, https://builders.intel.com/docs/networkbuilders/intel-avx-512-instruction-set-for-packet-processing-technology-guide-1617440657.pdf. The AVX512 frequency may be slower than the AVX2 if the CPU cores are with a full workload.

**Comment by Hap-Zhang** [comment]
OK,thank you for your reply. It means don't open too many threads when using AVX512？
