### ISSUE TITLE
MaxPooling has failed error when be transfered to a scripted module

### ISSUE THREAD

**Issue by XiaobingSuper** [intel/intel-extension-for-pytorch#18]
MaxPooling seems be overwrited at Python side, it can not works when transfered to a scripted module.

**Comment by XiaobingSuper** [comment]
And also for linear.

**Comment by pinzhenx** [comment]
Just a thought 

As I noticed that pytorch is complaining it cannot recognize our customized max_pool as a built-in function. So I’m wondering if we are registering custom ops the right way. Currently we are registering the ExtOps with naive pybind mechanism, so pytorch certainly cannot see it. I’m not sure if we can register our ExtOps the same way as those DenseOps with torch::RegisterOperators

**Comment by XiaobingSuper** [comment]
Yes, it can sovle this problem.

**Comment by XiaobingSuper** [comment]
see https://github.com/intel/intel-extension-for-pytorch/pull/15/commits/0052bd9c374abe74a1f925f5fbb66714ef6e02e1

**Comment by XiaobingSuper** [comment]
solved by https://github.com/intel/intel-extension-for-pytorch/pull/15
