### ISSUE TITLE
Getting error while using launch script

### ISSUE THREAD

**Issue by arunjose696** [intel/intel-extension-for-pytorch#182]
installed torch_ipex 1.8 with pip but while trying to launch ipex with the launch script, getting the below error.

/glob/development-tools/versions/oneapi/2021.3.0/inteloneapi/intelpython/latest/envs/pytorch-1.8.0/bin/python: Error while finding module specification for 'torch_ipex.launch' (ModuleNotFoundError: No module named 'torch_ipex')

**Comment by EikanWang** [comment]
@jingxu10 , could you help to check it?

**Comment by jingxu10** [comment]
Hi @arunjose696, the package name for 1.8 was `intel_pytorch_extension`. `torch_ipex` is only available in 1.9.
Please try `intel_pytorch_extension.launch`

**Comment by EikanWang** [comment]
I suppose this issue has been fixed on the release/1.10 branch. Please feel free to reopen it if not.
