### ISSUE TITLE
Is torch-ccl required when running distributed training with pytorch DDP?

### ISSUE THREAD

**Issue by Peach-He** [intel/intel-extension-for-pytorch#196]
Hi,
For ipex, when running distributed training with pytorch DDP, is torch-ccl is a must option, or can I use mpi, gloo as backend as well? Looks like gloo did not support device type xpu.

**Comment by EikanWang** [comment]
We are preparing the 1.10 release. From IPEX 1.10, we switched the device from XPU to CPU. It is a big change. It also means that you will not encounter this issue. You can try the release/1.10 branch now. One more thing I want to highlight is that the gloo, mpi does not support BF16. A simple example to demonstrate the distributed training with IPEX 1.10 is as follows.

1. Invoke “ipex.optimize” with optimizer

```python
model.train()
optimized_model, optimized_optimizer = ipex.optimize(model, dtype=torch.float32, optimizer=optimizer)
```

2. Create DDP model
```python
ddp_mp_model = DDP(optimized_model)
```

3. Start training
```python
optimized_optimizer.zero_grad()
output = ddp_mp_model(input)
loss_fn(output, labels).backward()
optimized_optimizer.step()
```

**Comment by Peach-He** [comment]
Pytorch 1.10 + IPEX 1.10 + torch-ccl 1.10 work perfect well
