### ISSUE TITLE
Latest master not building

### ISSUE THREAD

**Issue by xsacha** [intel/intel-extension-for-pytorch#199]
/d/dev/intel-extension-for-pytorch/torch_ipex/csrc/jit/subgraph_rewrite.cpp: In member function ‘torch::jit::Module torch::jit::IpexSubgraphRewriter::runOnModule(const torch::jit::Module&)’:
/d/dev/intel-extension-for-pytorch/torch_ipex/csrc/jit/subgraph_rewrite.cpp:64:27: error: ‘struct torch::jit::Function’ has no member named ‘graph’
   64 |     auto g = m.function().graph();
      |                           ^~~~~

Using GCC 9.3

**Comment by EikanWang** [comment]
@xsacha , may I know your branch? Are you trying to build master branch?

**Comment by xsacha** [comment]
Yes, master

**Comment by EikanWang** [comment]
Got it. The master branch is for a particular commit of the PyTorch master. We will update the master README later to explicitly specify the particular PyTorch commit number. Currently, I recommend you to use the release/1.10 branch to install IPEX from the source. By the way, we also provide the binary release now. You can directly install IPEX via pip. You can refer to https://intel.github.io/intel-extension-for-pytorch/tutorials/installation.html for more details.

**Comment by xsacha** [comment]
I noticed the prebuilt requires AVX-512. Is it possible to have an AVX-2 build as well?

**Comment by EikanWang** [comment]
@xsacha , if you want to try AVX2, you can build IPEX by setting AVX2 to 1.
```sh
AVX2=1 python setup.py install
```

**Comment by xsacha** [comment]
Thanks!

The original issue was actually due to it finding a newer installed torch (in python dist-packages) for the torch headers. Manually setting PYTORCH_INCLUDE_DIRS or ensuring only 1.10 is installed worked for the issue here.
