### ISSUE TITLE
Ability to compile to target for AVX512 + AVX2 devices

### ISSUE THREAD

**Issue by xsacha** [intel/intel-extension-for-pytorch#200]
I was able to compile for AVX2 but it's more practical to have the same extension work for both.

**Comment by EikanWang** [comment]
We are planning to integrate the AVX2 and AVX512 as a single binary. Sincerely thanks for your suggestion.

**Comment by EikanWang** [comment]
@xsacha , we released IPEX 1.11 by tightly following PyTorch 1.11 release. We merged the AVX2 and AVX512 as a single binary now. Please refer to https://github.com/intel/intel-extension-for-pytorch/releases/tag/v1.11.0 for more details.
