### ISSUE TITLE
`pytorch` with Intel optimization hangs during interaction with `ray` package

### ISSUE THREAD

**Issue by amyskov** [intel/intel-extension-for-pytorch#203]
Hi!
I have a problem with usage of Intel `pytorch` optimization during interaction with `ray` package, see reproducer below:
Create and activate conda environment:
```
conda create --name ray_torch python=3.8 ray-default==1.6.0 pytorch==1.8.0 -c conda-forge
conda activate ray_torch
```
And then run the next snippet:
```
import os
os.environ["KMP_AFFINITY"] = "granularity=fine,compact,1,0"
import torch

import ray
ray.init()

print("Passed")
```

The above snippet works fine if environment variable `KMP_AFFINITY` is not set and hangs if it is set.

P.S. Interaction of `pytorch` and `ray` is important because Intel Modin (part of Intel AI Kit) uses `ray` as one of the engines.

**Comment by amyskov** [comment]
I mean snippet
```
import os
# os.environ["KMP_AFFINITY"] = "granularity=fine,compact,1,0"
import torch

import ray
ray.init()

print("Passed")
```
works fine, but snippet
```
import os
os.environ["KMP_AFFINITY"] = "granularity=fine,compact,1,0"
import torch

import ray
ray.init()

print("Passed")
```
doesn't finishes.
Also i had recently found that hanging depends on the CPU cores number, in my case i had reproduced this issue on the Intel Xeon Platinum 8276L CPU with 112 cores, but it had worked fine on machine with 8 cores.

**Comment by jgong5** [comment]
@amyskov Just to make sure it is PyTorch specific or just related to Intel OMP w/ Ray. Could you please try out below:
```bash
LD_PRELOAD=/path/to/libiomp5.so python your_test.py
```
And in your_test.py, you do:
```python
import os
os.environ["KMP_AFFINITY"] = "granularity=fine,compact,1,0"
#import torch

import ray
ray.init()

print("Passed")
```

**Comment by amyskov** [comment]
@jgong5 i have tried your example and no hanging occurred, so it looks like that this issue is specific for PyTorch.

**Comment by amyskov** [comment]
Hi @EikanWang!
Was the reason of hanging behavior found?

**Comment by EikanWang** [comment]
@amyskov ,  Not yet. But I think it is a PyTorch-specific issue, Could you please help to raise this issue to the PyTorch community?

**Comment by EikanWang** [comment]
If you find any IPEX-related reasons for this issue, please feel free to re-open this issue.

**Comment by amyskov** [comment]
Ok, i see. Corresponding issue was created https://github.com/pytorch/pytorch/issues/70239.
