### ISSUE TITLE
`ipex.optimize` and TorchScript models

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [intel/intel-extension-for-pytorch#209]
The [examples in the documentation](https://intel.github.io/intel-extension-for-pytorch/tutorials/examples.html#id1) for TorchScript inference seem to indicate that you need to run `ipex.optimize` _before_ compiling to TorchScript:
```python
model.eval()

import intel_extension_for_pytorch as ipex
model = ipex.optimize(model)

with torch.no_grad():
  model = torch.jit.trace(model, data)
  model = torch.jit.freeze(model)

  model(data)
```

Is this true, or is it supported to pass a model that has already been `torch.jit.script`ed and `torch.jit.freeze`ed?

**Comment by EikanWang** [comment]
IPEX has not supported this case.
