### ISSUE TITLE
`ipex.cpu.runtime.is_runtime_ext_enabled()` returns `False` after installing from wheel

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [intel/intel-extension-for-pytorch#210]
I installed IPEX using the pre-built wheel on an installation of PyTorch 1.10, and then have in my code:
```python
        import intel_extension_for_pytorch as ipex
        ipex.enable_onednn_fusion(True)
        print("IPEX?", ipex.cpu.runtime.is_runtime_ext_enabled())
        model = ipex.optimize(model, inplace=True)
```
which prints
```
IPEX? False
```

Is this expected, and is there a way to enable the CPU TorchScript runtime?

**Comment by EikanWang** [comment]
The runtime optimization is based on Intel OpenMP. https://intel.github.io/intel-extension-for-pytorch/tutorials/features/runtime_extension.html#requirements
It returns `true` if the Intel OpenMP is used. We will refine the API document to explicitly figure out when the result should be true and false.

**Comment by Linux-cpp-lisp** [comment]
I see, thanks @EikanWang. Just to make sure I understand correctly: regardless of the value returned by that function,
```python
import intel_extension_for_pytorch as ipex
ipex.enable_onednn_fusion(True)
```
is enough to enable IPEX optimizations for any TorchScript graphs in the program?

(Tangentially, is that true even for graphs on which `ipex.optimized` has been called?)

**Comment by EikanWang** [comment]
The model needs to invoke `ipex.optimize` explicitly. You can refer to this examp.
https://intel.github.io/intel-extension-for-pytorch/tutorials/examples.html#float32

**Comment by Linux-cpp-lisp** [comment]
Thanks @EikanWang --- and just to be clear, the argument to `ipex.optimize` can be a TorchScript model?

**Comment by jgong5** [comment]
> and just to be clear, the argument to `ipex.optimize` can be a TorchScript model?

No. `ipex.optimize` only accepts imperative models.

**Comment by xsacha** [comment]
When I test my torchscript model, without any IPEX at all, I get:
Average inference time: 0.1271 seconds

Simply importing ipex:
`import intel_extension_for_pytorch as ipex`
gives me:
Average inference time: 0.918 seconds after 400 iterations

To clarify: not using onednn fusion, not using ipex.optimize at all.
I attempt to add onednn fusion and ipex.optimise (prior to tracing the model to torchscript) and there is zero change in the performance.

I ran this 5 times to be sure.

I believe this is what @Linux-cpp-lisp was referring to.

The gains appear in the torchscript model, without requiring ipex.optimize to be run.

**Comment by EikanWang** [comment]
@xsacha , may I know your model name? Or could you share the model code with me?

**Comment by xsacha** [comment]
That was just on Retinaface. I think it applies to all models?

**Comment by Linux-cpp-lisp** [comment]
@xsacha this was exactly what I was asking; whether just importing IPEX registers additional fusers/backend implementations with PyTorch or whether one actually has to process a Python (not torchscript) model first

**Comment by xsacha** [comment]
I think you need to freeze the model first, but unsure whether this can be done in C++ as well yet.

**Comment by jgong5** [comment]
> I think you need to freeze the model first, but unsure whether this can be done in C++ as well yet.

If you are talking about deploying TorchScript model in C++, you don't have to worry about the model "freeze" since the common practice for C++ is that the code loads an existing TorchScript serialized from the Python code and the TorchScript model has already been frozen there.

**Comment by xsacha** [comment]
I think the idea is to have a single model that can be used for CUDA and ipex, in which case you would need to send an unfrozen torchscript I believe.
Then at startup in the C++ program that has IPEX library linked, you would freeze the module (as it rewrites the code with ipex.* calls).

**Comment by jgong5** [comment]
I don't think graph freezing is backend device specific. When you freeze a graph, you basically tell the backends that all the weights are constant. I suppose both CUDA and IPEX require a frozen graph for inference optimization, no?

**Comment by Linux-cpp-lisp** [comment]
@xsacha I believe @jgong5 is right that freezing is not backend specific and that to get the IPEX gains in C++ you'd have to somehow load the IPEX PyTorch plugin in your C++ program... what that looks like in C++ I have no idea, maybe someone here can say?

**Comment by jgong5** [comment]
> I believe @jgong5 is right that freezing is not backend specific and that to get the IPEX gains in C++ you'd have to somehow load the IPEX PyTorch plugin in your C++ program... what that looks like in C++ I have no idea, maybe someone here can say?

You need IPEX C++ SDK: https://intel.github.io/intel-extension-for-pytorch/1.11/tutorials/installation.html#install-c-sdk
Here is the tutorial how to link IPEX with a C++ program: https://intel.github.io/intel-extension-for-pytorch/1.11/tutorials/examples.html#c

Let us know any questions/problems.

**Comment by Linux-cpp-lisp** [comment]
Great, thanks!
