### ISSUE TITLE
Feature Request: Linear + SiLU fusion

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [intel/intel-extension-for-pytorch#211]
The docs seem to indicate that SiLU is a possible fused nonlinearity, listing Conv + SiLU as a fusion option (https://intel.github.io/intel-extension-for-pytorch/tutorials/features/graph_optimization.html).

Does IPEX support Linear + SiLU? It isn't listed but that makes it sound like it is a fusion supported by oneAPI.

Thanks!

**Comment by EikanWang** [comment]
IPEX 1.10 does not support Linear + SiLU. May I know which model hits this fusion pattern?

**Comment by Linux-cpp-lisp** [comment]
I work on physics machine learning, specifically machine-learning interatomic potentials. (Our code is here: https://github.com/mir-group/nequip.) For such models, derivatives computed using autograd typically form a part of the inference pass. Thus we often need sane second and even third derivatives, for which SiLU is a very useful smooth nonlinearity.

Also, for the `Linear + *` fusion patterns, does this apply to any matmul or only to `torch.nn.functional.linear`?

**Comment by EikanWang** [comment]
Sorry for the late reply. IPEX currently depends on oneDNN fusion capabilities. oneDNN does not support SiLU now. So it is hard to support Linear + SiLU now. May I know the SiLU E2E CPU time ratio?

**Comment by EikanWang** [comment]
We have supported this fusion in the coming release 1.12
