### ISSUE TITLE
Support for torch DDP + ipex + bf16

### ISSUE THREAD

**Issue by Peach-He** [intel/intel-extension-for-pytorch#212]
According the ipex doc, torch DDP with bf16 with ipex is not supported, so we cannot use ipex optimization in this scenario, right? 
Do we have the plan to add support for torch DDP + ipex + bf16?

**Comment by jgong5** [comment]
cc @liangan1

**Comment by liangan1** [comment]
> According the ipex doc, torch DDP with bf16 with ipex is not supported, so we cannot use ipex optimization in this scenario, right?
> Do we have the plan to add support for torch DDP + ipex + bf16?
 BF16 is not supported by the default communication backend(eg, gloo,mpi) in the torch. To use BF16 distributed training with IPEX, You can use DDP+IPEX+BF16+Torch-ccl(https://github.com/intel/torch-ccl/tree/ccl_torch1.10).
