### ISSUE TITLE
DLRM with ipex 1.10

### ISSUE THREAD

**Issue by Peach-He** [intel/intel-extension-for-pytorch#213]
Hi,
Not sure if you have plan on upgrading DLRM code to ipex 1.10. I tried to upgrade the DLRM code with ipex 1.10 based on the patch from [https://github.com/intel/intel-extension-for-pytorch/blob/0.2/torch_patches/models/0001-enable-dlrm-distributed-training-for-cpu.patch](url) and noticed performance regression. 
Micro benchmark showed that all_to_all had 2x worse performance after upgrading ipex 1.10. Any idea?

system config:

- torch ccl 1.10, pytorch 1.10, ipex 1.10
- single node, 2 ranks per node

**all2all ipex v0.2:**
![all2all-ipex02](https://user-images.githubusercontent.com/51695408/150934956-de7fa73c-0338-4254-98eb-722dce14f81d.png)
**all2all ipex 1.10:**
![all2all-ipex110](https://user-images.githubusercontent.com/51695408/150934964-8debe32f-b254-4331-a3fa-148d0c500b5e.png)

**test code:**
```
import torch
import os

import extend_distributed as ext_dist

if __name__ == "__main__":
    ext_dist.init_distributed(backend='ccl')
    inputs = []
    tensor1 = torch.ones(262144, 16, dtype=torch.bfloat16)
    tensor2 = torch.ones(262144, 16, dtype=torch.bfloat16)
    inputs.append(tensor1)
    inputs.append(tensor2)
    with torch.autograd.profiler.profile(True) as prof:
        for _ in range(10):
            a2a_req = ext_dist.alltoall(inputs, None)
            ly_sparse = a2a_req.wait()
    print(prof.key_averages().table(sort_by="cpu_time_total"))
```

Thanks

**Comment by EikanWang** [comment]
@Peach-He , yes, we have a plan to upgrade DLRM for IPEX 1.10. The work is WIP. @zhuhaozhe , please keep Peach posted if you have any updates.

**Comment by zhuhaozhe** [comment]
@Peach-He. We have updated DLRM for IPEX 1.10 for single-node training. And also enabled the functionality for distribute-training with 2 sockets on single-node. But the performance analysis is WIP. @liangan1 is working on distributed training on multi-node with performance tuning.

Hi, @liangan1. Do you have any insights on all2all performance?

**Comment by EikanWang** [comment]
@liangan1, could you please provide your feedback here?

**Comment by liangan1** [comment]
@EikanWang  got it. let me do some experiments and will relay it later.

**Comment by liangan1** [comment]
sorry, @Peach-He  @EikanWang  I can't reproduce your performance result. The following is the performance data with 2s on clx-8280.
Linux kernel: Linux mlt2-clx111 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**all2all ipex v0.2(with BKC [):**](https://github.com/mlcommons/training_results_v1.0/tree/master/Intel/benchmarks/dlrm/N-node-8s-cpx-pytorch)
![image](https://user-images.githubusercontent.com/46986936/160417303-fab5c0fa-34ce-42fb-adc8-4ceb6dc51e5d.png)
all2all ipex **1.10:**
![image](https://user-images.githubusercontent.com/46986936/160417879-a4bf13e4-955a-4d60-af53-7b382ec27a6e.png)

**Comment by EikanWang** [comment]
Please feel free to reopen it if you still encounter this issue.
