### ISSUE TITLE
redundant code

### ISSUE THREAD

**Issue by gzmkl** [intel/intel-extension-for-pytorch#214]
https://github.com/intel/intel-extension-for-pytorch/blob/98483e1e3a22ef7490f0ebd42c53b72f1a53f137/intel_extension_for_pytorch/csrc/cpu/ideep/ideep/abstract_types.hpp#L36

Line #36 is redundant as Line #31 is the same.

**Comment by EikanWang** [comment]
Thanks for your report. @XiaobingSuper , pls. help to remove the redundant code.
