### ISSUE TITLE
Model weights changed after using ipex.optimize

### ISSUE THREAD

**Issue by DirkFi** [intel/intel-extension-for-pytorch#216]
I tried to use ipex on the model I made, which only contains a Conv2d layer. But the **weights** of the **Conv2d layer** has changed after using ipex. 

See as the graph below, the model.0. weight has changed its shape.

![image](https://user-images.githubusercontent.com/51186292/158499183-008f4dd3-7787-422e-b431-45be9d5f0ded.png)

The full code is here.
```python
import numpy as np
import torch
from torch import nn
import intel_extension_for_pytorch as ipex
from copy import deepcopy

class EazyNet(nn.Module):
    def __init__(self, n_in, n_h, n_out):
        super(EazyNet, self).__init__()
        self.model = nn.Sequential(nn.Conv2d(n_h, n_h, 1))

        self.optimizer = torch.optim.SGD(self.parameters(), lr = 0.01)

    def forward(self, inputs):
        return self.model(inputs)

# Example
model1 = EazyNet(2,1,2)

# input of model
x = torch.randn(1, 1 ,2 ,2)

model1_before = deepcopy(list(model1.named_parameters()))
model_result = model1(x)

print("#####----------------------------######")
print(model1)
print("model param before ipex:\n")
print(model1_before)

model1, model1.optimizer = ipex.optimize(model1, optimizer=model1.optimizer)

print("\n#####----------------------------######")
print(model1)
print("model param after ipex:\n")
print(list(model1.named_parameters()))

assert (model_result == model1(x)).all()
```

**Comment by EikanWang** [comment]
IPEX packs the weight to another different layout for optimization https://oneapi-src.github.io/oneDNN/dev_guide_understanding_memory_formats.html#blocked-layout. That's why you observed the weight had been changed.

Do you have any concerns about this feature? Did you encounter any problems?

**Comment by DirkFi** [comment]
Thanks for your response! @EikanWang 

Do you have any utility method to change the weights back to how they originally were? The weights of this layout is not very convenient for interpretation.

**Comment by jgong5** [comment]
Hi @DirkFi : IPEX make sure that the serializable states of the weights are in the PyTorch native layout. That means you can get the native layout weights via `state_dict()`. Does that work for you?

**Comment by DirkFi** [comment]
> Hi @DirkFi : IPEX make sure that the serializable states of the weights are in the PyTorch native layout. That means you can get the native layout weights via `state_dict()`. Does that work for you?

Thanks a lot. This way of getting the weight works fine for me.

**Comment by DirkFi** [comment]
> You can explicitly decrease the optimization level to "O0" - `ipex.optimize(..., level="O0", ...)`. https://intel.github.io/intel-extension-for-pytorch/tutorials/api_doc.html#ipex.optimize

Thanks @EikanWang. I see.
