### ISSUE TITLE
is there IPEX support for intel GPU or Nvidia GPU ?

### ISSUE THREAD

**Issue by aghozzo** [intel/intel-extension-for-pytorch#219]
Few questions :

1- when using ipex , device is called "dpcpp"  does that default to intel CPU ? 

2- is there IPEX support for intel GPU yet?  

3- if I want to use an application like DLRM with oneAPI on Nvidia GPU. how to do that ? I cant see a way to use IPEX or a similar mechanism to use "DLRM+ Pytorch +NVIDIA GPU+ OneAPI" in the same context . 

4- Intel Extension For PyTorch 1.2.0  release notes:
-Device name was changed from DPCPP to XPU.
-We changed the device name from DPCPP to XPU to align with the future Intel GPU product for heterogeneous computation.

Is there available DLRM patch to use with  intel extension 1.2.0 and up ? (the patch available on github only for release 1.1.0)

Thanks in advance

**Comment by EikanWang** [comment]
> 1- when using ipex , device is called "dpcpp" does that default to intel CPU ?

The device is CPU.

> 2- is there IPEX support for intel GPU yet?

The development is on-going. 

> 3- if I want to use an application like DLRM with oneAPI on Nvidia GPU. how to do that ? I cant see a way to use IPEX or a similar mechanism to use "DLRM+ Pytorch +NVIDIA GPU+ OneAPI" in the same context .

We did not evaluate this combination. Because the released IPEX only supports CPU now and all the optimizations work under the CPU device. https://github.com/pytorch/pytorch/blob/master/c10/core/DispatchKey.h#L55

> 4- Intel Extension For PyTorch 1.2.0 release notes:

We have released IPEX 1.11.0 now. Please refer to https://intel.github.io/intel-extension-for-pytorch/ for more details.

**Comment by EikanWang** [comment]
> Is there available DLRM patch to use with intel extension 1.2.0 and up ? (the patch available on github only for release 1.1.0)

@zhuhaozhe , I suppose we do not need to patch DLRM now. Please correct me.

**Comment by zhuhaozhe** [comment]
> > Is there available DLRM patch to use with intel extension 1.2.0 and up ? (the patch available on github only for release 1.1.0)
> 
> @zhuhaozhe , I suppose we do not need to patch DLRM now. Please correct me.

We need to patch official DLRM to use our custom OPs. Running with JIT and Pytorch throughput benchmark also need patch. I would suggest to use DLRM in intel model zoo.
scripts:https://github.com/IntelAI/models/tree/pytorch-r1.11-models/quickstart/recommendation/pytorch/dlrm
model code: https://github.com/IntelAI/models/tree/master/models/recommendation/pytorch/dlrm/product

**Comment by aghozzo** [comment]
> > > Is there available DLRM patch to use with intel extension 1.2.0 and up ? (the patch available on github only for release 1.1.0)
> > 
> > 
> > @zhuhaozhe , I suppose we do not need to patch DLRM now. Please correct me.
> 
> We need to patch official DLRM to use our custom OPs. Running with JIT and Pytorch throughput benchmark also need patch. I would suggest to use DLRM in intel model zoo. scripts:https://github.com/IntelAI/models/tree/pytorch-r1.11-models/quickstart/recommendation/pytorch/dlrm model code: https://github.com/IntelAI/models/tree/master/models/recommendation/pytorch/dlrm/product

My work is focused on oneAPI.
Model zoo is running ML outside the context of oneAPI . right  ?

**Comment by aghozzo** [comment]
> > 1- when using ipex , device is called "dpcpp" does that default to intel CPU ?
> 
> The device is CPU.
> 
> > 2- is there IPEX support for intel GPU yet?
> 
> The development is on-going.
> 
> > 3- if I want to use an application like DLRM with oneAPI on Nvidia GPU. how to do that ? I cant see a way to use IPEX or a similar mechanism to use "DLRM+ Pytorch +NVIDIA GPU+ OneAPI" in the same context .
> 
> We did not evaluate this combination. Because the released IPEX only supports CPU now and all the optimizations work under the CPU device. https://github.com/pytorch/pytorch/blob/master/c10/core/DispatchKey.h#L55
> 
> > 4- Intel Extension For PyTorch 1.2.0 release notes:
> 
> We have released IPEX 1.11.0 now. Please refer to https://intel.github.io/intel-extension-for-pytorch/ for more details.

Thanks for the reply, 

Is there FPGA support yet ?

**Comment by EikanWang** [comment]
> 

Yes, the latest DLRM is based on the latest IPEX.

**Comment by EikanWang** [comment]
> 

IPEX currently does not support FPGA.

**Comment by zhuhaozhe** [comment]
> Model zoo is running ML outside the context of oneAPI . right ?

Sorry, I do not understand what belongs "context of oneAPI". The address I shared with you is "Model zoo run ML with ipex".  Should it belong to the "context of oneAPI" ?

**Comment by aghozzo** [comment]
> > Model zoo is running ML outside the context of oneAPI . right ?
> 
> Sorry, I do not understand what belongs "context of oneAPI". The address I shared with you is "Model zoo run DLRM with ipex". Should it belong to the "context of oneAPI" ?


Thanks for the reply, Sorry I got a bit confused. 

looking at the link you sent (https://github.com/IntelAI/models/blob/master/models/recommendation/pytorch/dlrm/product/dlrm_s_pytorch.py) 

I see this is also running on the CPU 
    device = torch.device("cpu")
    print("Using CPU...")

so the advantage of using "Model zoo" here is running the "Latest IPEX" that is compatible with DLRM on the CPU ?

**Comment by zhuhaozhe** [comment]
> > > Model zoo is running ML outside the context of oneAPI . right ?
> > 
> > 
> > Sorry, I do not understand what belongs "context of oneAPI". The address I shared with you is "Model zoo run DLRM with ipex". Should it belong to the "context of oneAPI" ?
> 
> Thanks for the reply, Sorry I got a bit confused.
> 
> looking at the link you sent (https://github.com/IntelAI/models/blob/master/models/recommendation/pytorch/dlrm/product/dlrm_s_pytorch.py)
> 
> I see this is also running on the CPU device = torch.device("cpu") print("Using CPU...")
> 
> so the advantage of using "Model zoo" here is running the "Latest IPEX" that is compatible with DLRM on the CPU ?

Current versions IPEX-CPU (from 1.10) does not need ".to(ipex.device)" anymore and can run any naive CPU model. To get IPEX benefit, we provide an API "ipex.optimize". The models in the model zoo has already enabled with "ipex.optimize".

For DLRM, we also implement some custom OP to speed it up. Using these custom OP require codes change in the DLRM. We also put the changes in the model zoo. So with running  DLRM models in the model zoo, you can get all optimization for latest IPEX CPU version.

**Comment by zhuhaozhe** [comment]
@aghozzo . If you are interested for the changes, you can get 1.10 release note here.
https://intel.github.io/intel-extension-for-pytorch/tutorials/releases.html#id12
And the API doc for ipex.optimize https://intel.github.io/intel-extension-for-pytorch/tutorials/api_doc.html#ipex.optimize

**Comment by aghozzo** [comment]
> > > > Model zoo is running ML outside the context of oneAPI . right ?
> > > 
> > > 
> > > Sorry, I do not understand what belongs "context of oneAPI". The address I shared with you is "Model zoo run DLRM with ipex". Should it belong to the "context of oneAPI" ?
> > 
> > 
> > Thanks for the reply, Sorry I got a bit confused.
> > looking at the link you sent (https://github.com/IntelAI/models/blob/master/models/recommendation/pytorch/dlrm/product/dlrm_s_pytorch.py)
> > I see this is also running on the CPU device = torch.device("cpu") print("Using CPU...")
> > so the advantage of using "Model zoo" here is running the "Latest IPEX" that is compatible with DLRM on the CPU ?
> 
> Current versions IPEX-CPU (from 1.10) does not need ".to(ipex.device)" anymore and can run any naive CPU model. To get IPEX benefit, we provide an API "ipex.optimize". The models in the model zoo has already enabled with "ipex.optimize".
> 
> For DLRM, we also implement some custom OP to speed it up. Using these custom OP require codes change in the DLRM. We also put the changes in the model zoo. So with running DLRM models in the model zoo, you can get all optimization for latest IPEX CPU version.

Got it. Thanks for the explanation
