### ISSUE TITLE
Getting import error

### ISSUE THREAD

**Issue by j-adamczyk** [intel/intel-extension-for-pytorch#221]
I am trying to install Intel Extension for PyTorch in a Docker container. I get error:
```
  File "/usr/src/app/.../Predictor.py", line 4, in <module>
    import intel_extension_for_pytorch as ipex
  File "/usr/local/lib/python3.8/site-packages/intel_extension_for_pytorch/__init__.py", line 13, in <module>
    from . import quantization
  File "/usr/local/lib/python3.8/site-packages/intel_extension_for_pytorch/quantization/__init__.py", line 1, in <module>
    from .quantization_utils import calibrate, convert
  File "/usr/local/lib/python3.8/site-packages/intel_extension_for_pytorch/quantization/quantization_utils.py", line 6, in <module>
    import intel_extension_for_pytorch._C as core
ImportError: /usr/local/lib/python3.8/site-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-cpu.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKS0_PSo
make: *** [Makefile:6: ssp_train] Error 1
```

My Dockerfile:
```
FROM python:3.8

ENV POETRY_VIRTUALENVS_CREATE=false \
    POETRY_VERSION=1.1.12 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /usr/src/app
RUN apt-get update
RUN apt-get --yes install libsnappy-dev libgomp1

COPY ./poetry.lock ./poetry.lock
COPY ./pyproject.toml ./pyproject.toml

RUN pip install poetry
RUN poetry install --no-interaction

COPY . .
RUN cp .env.example .env

CMD ["python3", "-m", "train_model"]
```

I am using `poetry` for package management and `pip` for package installation. How can I fix this error? I have only added `intel-extension-for-pytorch = "1.11.*"` to my dependencies, other packages are e.g. `numpy`, `scipy`, `pytorch` (regular `pip` versions).

**Comment by EikanWang** [comment]
IPEX 1.11 docker image is WIP. @jingxu10 , please share more details here.

**Comment by j-adamczyk** [comment]
I am also getting very similar error when installing IPEX in regular Anaconda env in Linux Ubuntu:
```
    from . import quantization
  File "/home/jakub/anaconda3/envs/ml-models/lib/python3.8/site-packages/intel_extension_for_pytorch/quantization/__init__.py", line 1, in <module>
    from .quantization_utils import calibrate, convert
  File "/home/jakub/anaconda3/envs/ml-models/lib/python3.8/site-packages/intel_extension_for_pytorch/quantization/quantization_utils.py", line 6, in <module>
    import intel_extension_for_pytorch._C as core
ImportError: /home/jakub/anaconda3/envs/ml-models/lib/python3.8/site-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-cpu.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
```

**Comment by EikanWang** [comment]
Did you install ipex by `pip`? And could you help check your local PyTorch version? IPEX 1.11 requires PyTorch 1.11.

**Comment by j-adamczyk** [comment]
It works after upgrading PyTorch. However, training a single epoch got slower by about 20-50% after using `ipex.optimize()` in Docker. In my regular Anaconda env it got faster by about 20%.

**Comment by EikanWang** [comment]
Could you share the model name and CPU information here? We will reproduce the performance locally.

**Comment by j-adamczyk** [comment]
The model is  MLP in PyTorch, 3 hidden layers, learning rate 0.01, dropout 0.3. Inputs are text embeddings from DistilBERT, length 768 dense vectors. Layer shapes: 768 (input), 64, 32, 1 (regression target).

CPU: Intel® Core™ i7-10850H CPU @ 2.70GHz × 12

**Comment by EikanWang** [comment]
IPEX currently is still optimizing the training performance. By the way, what's the loss function?

**Comment by j-adamczyk** [comment]
MSELoss
