### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement intel_extension_for_pytorch==1.10.0 (from version: none)

### ISSUE THREAD

**Issue by rasmusKjaersgaard** [intel/intel-extension-for-pytorch#222]
I'm trying to install the intel_extension_for_pytorch in a virtual Conda environment using pip.
I've installed PyTorch using:
`pip install torch==1.10.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html`

When I try to install the extension using:
`pip install intel_extension_for_pytorch==1.10.0 -f https://software.intel.com/ipex-whl-stable`

I get the following error:
`ERROR: Could not find a version that satisfies the requirement intel_extension_for_pytorch==1.10.0 (from versions: none)`
`ERROR: No matching distribution found for intel_extension_for_pytorch==1.10.0`

**Comment by EikanWang** [comment]
I cannot reproduce this issue. 
![image](https://user-images.githubusercontent.com/55483091/162143970-5f3b35f0-5bd2-4190-99b5-7313b9f13311.png)

**Comment by shuaishuaigu** [comment]
i got same problem,like

(pytorch) X:\Gseq>pip install intel_extension_for_pytorch -f https://software.intel.com/ipex-whl-stable
WARNING: Ignoring invalid distribution -orch (d:\anaconda3\anaconda\envs\pytorch\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (d:\anaconda3\anaconda\envs\pytorch\lib\site-packages)
WARNING: Ignoring invalid distribution -orch (d:\anaconda3\anaconda\envs\pytorch\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (d:\anaconda3\anaconda\envs\pytorch\lib\site-packages)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Looking in links: https://software.intel.com/ipex-whl-stable 
ERROR: Could not find a version that satisfies the requirement intel_extension_for_pytorch (from versions: none)
ERROR: No matching distribution found for intel_extension_for_pytorch
WARNING: Ignoring invalid distribution -orch (d:\anaconda3\anaconda\envs\pytorch\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (d:\anaconda3\anaconda\envs\pytorch\lib\site-packages)
WARNING: Ignoring invalid distribution -orch (d:\anaconda3\anaconda\envs\pytorch\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (d:\anaconda3\anaconda\envs\pytorch\lib\site-packages)
WARNING: Ignoring invalid distribution -orch (d:\anaconda3\anaconda\envs\pytorch\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (d:\anaconda3\anaconda\envs\pytorch\lib\site-packages)

how can i do
