### ISSUE TITLE
Documentation, Installation and Examples web links are 404 now

### ISSUE THREAD

**Issue by ambiamber** [intel/intel-extension-for-pytorch#225]
I think everything has moved to https://pytorch.org/tutorials/recipes/recipes/intel_extension_for_pytorch.html

**Comment by xuhancn** [comment]
@jingxu10 please check this issue.

**Comment by jingxu10** [comment]
Hi, may I know where are links malfunctioning?

**Comment by jingxu10** [comment]
@ambiamber we changed layout of the website a little bit to add history version functionality. Please visit https://intel.github.io/intel-extension-for-pytorch/1.11.100/index.html before we update the link on the readme page. Thank you.

**Comment by ambiamber** [comment]
LGTM, thanks
