### ISSUE TITLE
enable_auto_mixed_precision not working

### ISSUE THREAD

**Issue by ViktorThink** [intel/intel-extension-for-pytorch#226]
Running:

`import intel_extension_for_pytorch as ipex 
ipex.enable_auto_mixed_precision(mixed_dtype = torch.bfloat16) ` 

Results in the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-2-260b092d4782>](https://localhost:8080/#) in <module>()
      1 import intel_extension_for_pytorch as ipex
----> 2 ipex.enable_auto_mixed_precision(mixed_dtype = torch.bfloat16)

AttributeError: module 'intel_extension_for_pytorch' has no attribute 'enable_auto_mixed_precision'
```

Here is a three line colab to show the issue:
https://colab.research.google.com/drive/1_Nhcq9k-wrh30_6bsYWiX6CmIEE6fX0K?usp=sharing

Is there any way to make enable_auto_mixed_precision work?

**Comment by EikanWang** [comment]
https://intel.github.io/intel-extension-for-pytorch/1.11/tutorials/features/amp.html

**Comment by EikanWang** [comment]
PyTorch has exposed the auto-mixed-precision. So IPEX aligned with PyTorch design. We also use this API to enable auto-mixed precision. https://intel.github.io/intel-extension-for-pytorch/1.11/tutorials/features/amp.html

```python
with torch.cpu.amp.autocast():
    y = model(x)
```

**Comment by ViktorThink** [comment]
Geat, thank you!
