### ISSUE TITLE
ImportError: /anaconda/envs/azureml_py38/lib/python3.8/site-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-cpu.so: undefined symbol: _ZNSt19basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev

### ISSUE THREAD

**Issue by Arunavameister** [intel/intel-extension-for-pytorch#237]
Hello, I am trying to run it on Azure and I get the error mentioned above and I cannot find any reference for it.
Please help!
Thanks.

**Comment by jgong5** [comment]
@Arunavameister Thanks for reporting the issue. May I know the reproducing steps?

**Comment by Arunavameister** [comment]
Thanks for the quick response.
The error really occurs in the import.
This is the entire traceback, 

Traceback (most recent call last):
  File "Tests_Intel_AMX.py", line 10, in <module>
    import intel_extension_for_pytorch as ipex
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/intel_extension_for_pytorch/__init__.py", line 24, in <module>
    from . import cpu
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/intel_extension_for_pytorch/cpu/__init__.py", line 2, in <module>
    from . import runtime
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/intel_extension_for_pytorch/cpu/runtime/__init__.py", line 3, in <module>
    from .multi_stream import MultiStreamModule, get_default_num_streams, \
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/intel_extension_for_pytorch/cpu/runtime/multi_stream.py", line 4, in <module>
    import intel_extension_for_pytorch._C as core
ImportError: /anaconda/envs/azureml_py38/lib/python3.8/site-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-cpu.so: undefined symbol: _ZNSt19basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev

Additional info,
CPU family:        6
Model:               85
Model name:     Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz

I dont know what kind of additional information would be useful for you to reproduce this problem.

Please let me know.
Thanks

**Comment by jingxu10** [comment]
May I know how did you install pytorch and intel_extension_for_pytorch?

**Comment by Arunavameister** [comment]
The Azure instance came with pytorch preinstalled but it was an older version so I just upgraded it with pip(right now torch==1.12.0) and I installed intel_extension_for_pytorch using the command as mentioned in the readme, 
python -m pip install intel_extension_for_pytorch

**Comment by jgong5** [comment]
Could you please help share your libstdc++ version with the following command?
```bash
bash$ /sbin/ldconfig -p | grep stdc++
         libstdc++.so.6 (libc6,x86_64) => /lib/x86_64-linux-gnu/libstdc++.so.6
bash$ ls -l /lib/x86_64-linux-gnu/libstdc++.so.6
```

**Comment by jingxu10** [comment]
Please install the cpu version of pytorch with the following command.
`python -m pip install torch --force-reinstall --extra-index-url https://download.pytorch.org/whl/cpu`
https://pytorch.org/get-started/locally/

**Comment by Arunavameister** [comment]
@jgong5 
The version is libstdc++.so.6.0.25

@jingxu10 I just force reinstalled like you suggested and it worked!

Thanks a ton for your help guys!
