### ISSUE TITLE
[Question] CPP Inference

### ISSUE THREAD

**Issue by steathy-spikes** [intel/intel-extension-for-pytorch#246]
On the documentation, it says that [C++ can be used for inference](https://intel.github.io/intel-extension-for-pytorch/latest/tutorials/examples.html#c), and it also says that Intel optimizations will be activated automatically.

My question is, if I want to perform optimizations such as Conv_bn_folding, or just genreal [Graph Optimization](https://intel.github.io/intel-extension-for-pytorch/latest/tutorials/features/graph_optimization.html?highlight=graph#), do I call ipex.optimize() on the Pytorch side, THEN export it as JIT for C++ inference, or is that also taken care of during compilation? 

Thank you

**Comment by jingxu10** [comment]
Please use the former way. i.e. convert the model first in python side, then export it to a model file.

**Comment by steathy-spikes** [comment]
My convert, you mean call ipex.optimize() on pytorch model right? And export that? Sorry just wanted to clarify for sure.

**Comment by jingxu10** [comment]
Yes, your step is correct.
call ipex.optimize() on the Pytorch side, THEN export it as JIT for C++ inference

```
ipex.optimize()
torch.jit.save()
```

**Comment by steathy-spikes** [comment]
Thank you so much for your help!
