### ISSUE TITLE
Missing compatible torchvision in repository https://developer.intel.com/ipex-whl-stable-xpu

### ISSUE THREAD

**Issue by tedliosu** [intel/intel-extension-for-pytorch#251]
```
(base) tedliosu@victus-ted:~/Documents/all_git/intel-extension-for-pytorch/docker$ sudo -H ./build.sh
[a bunch of output here]
(base) tedliosu@victus-ted:~/Documents/all_git/intel-extension-for-pytorch/docker$ IMAGE_NAME=intel-extension-for-pytorch:gpu
(base) tedliosu@victus-ted:~/Documents/all_git/intel-extension-for-pytorch/docker$ VIDEO=$(getent group video | sed -E 's,^video:[^:]*:([^:]*):.*$,\1,')
(base) tedliosu@victus-ted:~/Documents/all_git/intel-extension-for-pytorch/docker$ RENDER=$(getent group render | sed -E 's,^render:[^:]*:([^:]*):.*$,\1,')
(base) tedliosu@victus-ted:~/Documents/all_git/intel-extension-for-pytorch/docker$ test -z "$RENDER" || RENDER_GROUP="--group-add ${RENDER}"
(base) tedliosu@victus-ted:~/Documents/all_git/intel-extension-for-pytorch/docker$ sudo -H docker run --rm -v /home/tedliosu/intel_pytorch_workspace:/workspace --group-add ${VIDEO} ${RENDER_GROUP} --device=/dev/dri --ipc=host -it $IMAGE_NAME bash
[sudo] password for tedliosu: 
groups: cannot find name for group ID 109
root@8e852a62c8b4:/# cd workspace/
root@8e852a62c8b4:/workspace# ls
datasets  ipex_f32_example.py  testfile.txt
root@8e852a62c8b4:/workspace# python3 ipex_f32_example.py 
Traceback (most recent call last):
  File "/workspace/ipex_f32_example.py", line 2, in <module>
    import torchvision
ModuleNotFoundError: No module named 'torchvision'
```
Contents of "/workspace/ipex_f32_example.py" (as you can see it's straight from one of the example scripts [here](https://github.com/intel/intel-extension-for-pytorch/blob/xpu-master/docs/tutorials/examples.md)):
```
import torch
import torchvision
############# code changes ###############
import intel_extension_for_pytorch as ipex
############# code changes ###############

LR = 0.001
DOWNLOAD = True
DATA = 'datasets/cifar10/'

transform = torchvision.transforms.Compose([
    torchvision.transforms.Resize((224, 224)),
    torchvision.transforms.ToTensor(),
    torchvision.transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])
train_dataset = torchvision.datasets.CIFAR10(
        root=DATA,
        train=True,
        transform=transform,
        download=DOWNLOAD,
)
train_loader = torch.utils.data.DataLoader(
        dataset=train_dataset,
        batch_size=128
)

model = torchvision.models.resnet50()
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = LR, momentum=0.9)
model.train()
#################################### code changes ################################
model = model.to("xpu")
model, optimizer = ipex.optimize(model, optimizer=optimizer, dtype=torch.float32)
#################################### code changes ################################

for batch_idx, (data, target) in enumerate(train_loader):
    ########## code changes ##########
    data = data.to("xpu")
    target = target.to("xpu")
    ########## code changes ##########
    optimizer.zero_grad()
    output = model(data)
    loss = criterion(output, target)
    loss.backward()
    optimizer.step()
    print(batch_idx)
torch.save({
     'model_state_dict': model.state_dict(),
     'optimizer_state_dict': optimizer.state_dict(),
     }, 'checkpoint.pth')
```

As you can see a compatible torchvision pip package is currently not in the https://developer.intel.com/ipex-whl-stable-xpu repository, and therefore I can't run any training OR inference workloads using the XPU branch of ipex :confused:

**Comment by sanchitintel** [comment]
Hi @tedliosu, currently, `Intel Extension for PyTorch` for GPU is based on PyTorch 1.10. So, for now, the TorchVision version compatible with it is TorchVision `0.11.3`.

However, things are in flux, and work is already underway to port `Intel Extension for PyTorch` for GPU to the latest PyTorch version.

**Comment by tedliosu** [comment]
> Hi @tedliosu, currently, `Intel Extension for PyTorch` for GPU is based on PyTorch 1.10. So, for now, the TorchVision version compatible with it is TorchVision `0.11.3`.
> 
> However, things are in flux, and work is already underway to port `Intel Extension for PyTorch` for GPU to the latest PyTorch version.
> 
> Please install `TorchVision 0.11.3` with a command such as this one -
> 
> ```shell
> pip install torchvision==0.11.3 --no-deps
> ```
> 
> Thanks!

Thank you so much for the workaround! I also discovered that I needed to `pip install pillow` for the demo script to run :smile: Is it alright if I leave this issue open until the official torchvision package gets uploaded to https://developer.intel.com/ipex-whl-stable-xpu?

**Comment by sanchitintel** [comment]
Thanks for your response, @tedliosu!

Yes, `pillow` is a requirement for `torchvision` but would not have been installed with `--no-deps` (which prevented a different version of PyTorch from being installed when you tried to install torchvision 0.11.3).
We'd document this caveat for future users, but since this is not a blocker, can you please close this issue after verifying that things are working well? Thanks!

We wouldn't be releasing a TorchVision package for `Intel Extension for PyTorch`'s GPU version, as its compatible TorchVision package is the v0.11.3 release, [which can also be built from source](https://github.com/pytorch/vision/tree/v0.11.3).

**Comment by sanchitintel** [comment]
@tedliosu, we really value your feedback!

Here's a caveat you might need to be aware about - the current generation of Intel Arc series GPUs don't support Float64 computations, but some PyTorch ops use FP64 (eg. `batchnorm` during training). So, you might wanna use [Float64 emulation](https://github.com/intel/compute-runtime/blob/master/opencl/doc/FAQ.md#how-do-i-enable-emulation) for such cases (you'd encounter an error if an operator would be using float64, and you'd be able to figure out when to enable it). Float64 emulation, however, is slower, so you might want to enable it only for workloads that actually use Float64. Thanks!

**Comment by tedliosu** [comment]
> We'd document this caveat for future users, but since this is not a blocker, can you please close this issue after verifying that things are working well? Thanks!

Unfortunately @sanchitintel, things are _still_ not working properly after having installed torchvision and pillow for whatever reason; inferencing seems to work fine in IPEX, but unfortunately the training script I posted initially in this issue would get stuck indefinitely at either  `for batch_idx, (data, target) in enumerate(train_loader):` or `data = data.to("xpu")` after just one iteration of the `for` loop.  But as this may or may not be still a torchvision issue, I'll open up another GitHub issue in this repository and edit this comment to reference that new issue here just to be safe.

**Comment by jingxu10** [comment]
yes, please raise another github issue regarding to this freezing issue. We will look into it. Thanks you.

**Comment by jingxu10** [comment]
by the way, I get your script working for training. The freezing you saw could because of runtime executable binary generation. oneDNN use JIT to generate final executable binaries in-the-fly.
![image](https://user-images.githubusercontent.com/25193121/199129114-312fbf86-e3ea-4fff-921f-d12d4e64e4eb.png)

**Comment by tedliosu** [comment]
> by the way, I get your script working for training. The freezing you saw could because of runtime executable binary generation. oneDNN use JIT to generate final executable binaries in-the-fly. ![image](https://user-images.githubusercontent.com/25193121/199129114-312fbf86-e3ea-4fff-921f-d12d4e64e4eb.png)

So how would I go about "unfreezing" the script then?...

**Comment by tedliosu** [comment]
I finally got the example script working using the torchvision workaround mentioned [here](https://github.com/intel/intel-extension-for-pytorch/issues/251#issuecomment-1296487217) per [the update I've posted in this issue](https://github.com/intel/intel-extension-for-pytorch/issues/253#issuecomment-1311364898), so I am going to close this issue for now per @sanchitintel's request.
