### ISSUE TITLE
IPEX change the "requires_grad" attribute in model parameters?

### ISSUE THREAD

**Issue by XinyaoWa** [intel/intel-extension-for-pytorch#255]
I found with after IPEX wrapper, part of the model parameters change the requires_grad from "False" to "True", which is not desired.

Key code:
import timm
import torch
import intel_extension_for_pytorch as ipex
import torch.optim as optim

model = timm.create_model("resnet18")
for (name, parameter) in model.named_parameters():
    parameter.requires_grad =False
    print(name, parameter.requires_grad)
optimizer = optim.SGD(model.parameters(),lr=0.1)
model = model.to(memory_format = torch.channels_last)
model, optimizer = ipex.optimize(model, optimizer=optimizer)
for (name, parameter) in model.named_parameters():
    print(name, parameter.requires_grad)

Output before IPEX:
conv1.weight False
bn1.weight False
bn1.bias False
layer1.0.conv1.weight False
layer1.0.bn1.weight False
layer1.0.bn1.bias False
layer1.0.conv2.weight False
layer1.0.bn2.weight False
layer1.0.bn2.bias False
layer1.1.conv1.weight False
layer1.1.bn1.weight False
layer1.1.bn1.bias False
layer1.1.conv2.weight False
layer1.1.bn2.weight False
layer1.1.bn2.bias False
layer2.0.conv1.weight False
layer2.0.bn1.weight False
layer2.0.bn1.bias False
layer2.0.conv2.weight False
layer2.0.bn2.weight False
layer2.0.bn2.bias False
........

Output after IPEX:
conv1.weight True
bn1.weight False
bn1.bias False
layer1.0.conv1.weight True
layer1.0.bn1.weight False
layer1.0.bn1.bias False
layer1.0.conv2.weight True
layer1.0.bn2.weight False
layer1.0.bn2.bias False
layer1.1.conv1.weight True
layer1.1.bn1.weight False
layer1.1.bn1.bias False
layer1.1.conv2.weight True
layer1.1.bn2.weight False
layer1.1.bn2.bias False
layer2.0.conv1.weight True
layer2.0.bn1.weight False
layer2.0.bn1.bias False
layer2.0.conv2.weight True
layer2.0.bn2.weight False
layer2.0.bn2.bias False
layer2.0.downsample.0.weight True
......

**Comment by unrahul** [comment]
If the workload is only for inference, shouldn't the api call be 

```python
model = ipex.optimize(model, dtype=torch.float32) # as the optimizer is not needed
```
I assume that when u use the api for training `ipex.optimize(model, optimizer, dtype)` the framework assumes that you are optimizing the model for training.

As always, the manual approach would be to traverse the graph and set `requires_grad=False` if the training api of ipex is used.

**Comment by jgong5** [comment]
@XinyaoWa Are you going to do transfer learning which freezes some weights during training? We'd better check why `ipex.optimize` changes the `requires_grad` flag when users set it to `False` upfront.

**Comment by zhuhaozhe** [comment]
Hi, @XinyaoWa, and @unrahul.
I did not reproduce this behavior. I got all false after ipex.optimize with the example your provided.
Could you post your ipex/pytorch commit here so I can further check it?
Btw, this behavior should test by https://github.com/intel/intel-extension-for-pytorch/blob/master/tests/cpu/test_ipex_optimize.py#L136.

Could you help to run this UT in your env and post your result here:
```
cd  tests/cpu
python test_ipex_optimize.py -k test_optimize_pretrain_model
```

**Comment by XinyaoWa** [comment]
> Hi, @XinyaoWa, and @unrahul. I did not reproduce this behavior. I got all false after ipex.optimize with the example your provided. Could you post your ipex/pytorch commit here so I can further check it? I guess your commit might be too older to include [d09f340](https://github.com/intel/intel-extension-for-pytorch/commit/d09f340965bbd2421a00317b466bbad1bf3fcad0) which fixed this issue.
> 
> Btw, this behavior should test by https://github.com/intel/intel-extension-for-pytorch/blob/master/tests/cpu/test_ipex_optimize.py#L136.
> 
> Could you help to run this UT in your env and post your result here:
> 
> ```
> cd  tests/cpu
> python test_ipex_optimize.py -k test_optimize_pretrain_model
> ```

Thanks for you reply @zhuhaozhe, before the bug appears with pytorch 1.10 and ipex 1.10, but when I update the version to 1.12, the issue fixed. Thanks!

**Comment by XinyaoWa** [comment]
> @XinyaoWa Are you going to do transfer learning which freezes some weights during training? We'd better check why `ipex.optimize` changes the `requires_grad` flag when users set it to `False` upfront. cc @zhuhaozhe

Yes, it's for transfer learning.
