### ISSUE TITLE
BFloat16 Mixed Precision Training Support For Arc Alchemist? If Not Could Float16 Training PLEASE Be Supported?

### ISSUE THREAD

**Issue by tedliosu** [intel/intel-extension-for-pytorch#258]
Basically [this](https://github.com/oneapi-src/oneDNN/issues/1498) question but I'd like to know the answer to the question for IPEX as well :smile:

Please let me know if there's any additional info I need to provide for my question to be answered. :+1:

**Comment by jingxu10** [comment]
XMX is enabled via oneDNN. Since its architecture is similar to that of Flex Series, it should work on Arc as well. However we haven't validated it on Arc and don't provide officially supports at this moment.

**Comment by tedliosu** [comment]
@jingxu10 OK thank you for letting me know; I may try it out once I get my hands on an Arc GPU hopefully sometime in the near future :+1:
