### ISSUE TITLE
extension 1.13 linker error

### ISSUE THREAD

**Issue by xsacha** [intel/intel-extension-for-pytorch#260]
Using the latest 1.13.0+cpu extension, it gives me this linker error:
symbol lookup error: lib/libintel-ext-pt-cpu.so: undefined symbol: __itt_task_begin_ptr__3_0

The only change is adding the provided CMake:
```
      add_library(intel_ext_pt_cpu_library INTERFACE IMPORTED)
      set_target_properties(intel_ext_pt_cpu_library PROPERTIES
	      INTERFACE_LINK_LIBRARIES "-Wl,--no-as-needed,\"${INTEL_EXT_PT_CPU_LIBRARY}\""
      )
      LIST(APPEND TORCH_LIBRARIES intel_ext_pt_cpu_library)
```

Am I missing something?

Edit: It's because I disabled ITT (Instrumentation and Tracing Technology) in libtorch.

**Comment by EvilMcStevil** [comment]
Where is the libamplxe_samplingmrte_javaprof_1.0.so sourced from?

**Comment by xsacha** [comment]
It is the ITT sampling library from Intel's OneAPI. If you built torch with ITT turned on (default), I think it would have been included with torch.
