### ISSUE TITLE
Looping critical error when running on Intel Arc GPU on 1.10+gpu

### ISSUE THREAD

**Issue by xsacha** [intel/intel-extension-for-pytorch#263]
When running ipex.optimize(m) on an XPU model, I achieve a never ending loop of critical errors that seem to mention FP64 even though there is no FP64 in my model.
![image](https://user-images.githubusercontent.com/61218/202643425-a93789de-5c04-4ae4-b0ca-69750d929799.png)
The message continues forever and never returns a result (eventually I had to terminate the process).

Without ipex.optimize, the model runs correctly and quickly on the GPU.

**Comment by jingxu10** [comment]
This is a limitation for now. Please avoiding using the `optimize` function when you see these errors. We are planning to enable FP64 emulation by default in future releases.

**Comment by xsacha** [comment]
Thanks
