### ISSUE TITLE
Intel Arc A770 not being recognized in Fedora.

### ISSUE THREAD

**Issue by pacf531** [intel/intel-extension-for-pytorch#266]
I have the following minimized code snippet:

```
import torch
try:
    import intel_extension_for_pytorch as ipex
    print("Imported IPEX")
    torch.zeros(1).to(torch.device("xpu"))
    print("Using XPU")
except Exception:
    print("No oneAPI")
```

When running it in my environment with intel-extension-for-python installed for GPU, I get the following result with the GPU seemingly not being recognized.

```
Imported IPEX
/home/pacf/.local/lib/python3.9/site-packages/intel_extension_for_pytorch/xpu/lazy_init.py:73: UserWarning: DPCPP Device count is zero! (Triggered internally at  /home/guizili/zhongruijie/frameworks.ai.pytorch.ipex-gpu/csrc/runtime/Device.cpp:116.)
  _C._initExtension()
/home/pacf/snippet.py:5: UserWarning: dpcppSetDevice: device_id is out of range (Triggered internally at  /home/guizili/zhongruijie/frameworks.ai.pytorch.ipex-gpu/csrc/runtime/Device.cpp:151.)
  torch.zeros(1).to(torch.device("xpu"))
No oneAPI
```

Is Intel Arc not supported officially at this point? It seems like from what I can see online that it should work. My environment is Linux 6.0.9 on Fedora 36 and the installation was fine, where I ran `source /opt/intel/oneapi/setvars.sh` and  installed the wheels inside the environment provided.

**Comment by gujinghui** [comment]
The device can not be found, according to the log. `UserWarning: DPCPP Device count is zero!`
We did not verify on Fedora. Please try to run `sycl-ls` to list out your device.
The recommended OS is Ubuntu 20.04, with verified driver version.
https://github.com/intel/intel-extension-for-pytorch/blob/xpu-master/docs/tutorials/installation.md

**Comment by pacf531** [comment]
Ah okay. The card was listed when I ran sycl-ls before I opened the issue but since I updated to Fedora 37 yesterday, and the package is broken due to some dependencies issue and since I need to do some stuff over the weekend, it might be a bit before I can try again. I'll see if I can wrangle an installation on a VM or wait for the dependency issues to sort themselves out. Will edit the title to better reflect my issue.

**Comment by kevinquillen** [comment]
Not using pytorch, but I have found that Fedora 37 cannot recognize the GPU on a cold boot, it is only until I have booted into it (then reboot) until I see the GPU listed alongside Xe. I don't want to use Ubuntu - but for the record I did try it and I did not get as far as I did with Fedora.

**Comment by pacf531** [comment]
Upstream Fedora fixed their fork of intel-compute-runtime and etc. some days ago apparent and now, sycl-ls now runs on my running Fedora 37. Here's the sys-ls output.

```
❯ /opt/intel/oneapi/compiler/2022.2.1/linux/bin/sycl-ls
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2022.14.10.0.20_160000.xmain-hotfix]
[opencl:cpu:1] Intel(R) OpenCL, AMD Ryzen 9 5950X 16-Core Processor             3.0 [2022.14.10.0.20_160000.xmain-hotfix]
[opencl:gpu:2] Intel(R) OpenCL HD Graphics, Intel(R) Graphics [0x56a0] 3.0 [22.43.24558]
[host:host:0] SYCL host platform, SYCL host device 1.2 [1.2]
```

This tells me the A770 GPU device should be working. But running the sample application snippet again, I get the same results.

**Comment by gujinghui** [comment]
> Upstream Fedora fixed their fork of intel-compute-runtime and etc. some days ago apparently and now, sycl-ls now runs on my running Fedora 37. Here's the sys-ls output.
> 
> ```
> ❯ /opt/intel/oneapi/compiler/2022.2.1/linux/bin/sycl-ls
> [opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2022.14.10.0.20_160000.xmain-hotfix]
> [opencl:cpu:1] Intel(R) OpenCL, AMD Ryzen 9 5950X 16-Core Processor             3.0 [2022.14.10.0.20_160000.xmain-hotfix]
> [opencl:gpu:2] Intel(R) OpenCL HD Graphics, Intel(R) Graphics [0x56a0] 3.0 [22.43.24558]
> [host:host:0] SYCL host platform, SYCL host device 1.2 [1.2]
> ```
> 
> This tells me the A770 GPU device should be working. But running the sample application snippet again, I get the same results.

Your driver does not have LevelZero runtime. Otherwise, you should be able to see below lines with sycl-ls
```
[opencl:gpu:0] Intel(R) OpenCL HD Graphics, Intel(R) Graphics ....
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Graphics ....
```
IPEX GPU can run with LevelZero runtime only.
I'm not try on Fedora before. Perhaps you have to install LevelZero manually, https://github.com/oneapi-src/level-zero

**Comment by pacf531** [comment]
Huh, there doesn't seem to be a package for that and digging around, there is an existing issue that talks about this and looking deeper from there, a placeholder has been placed for the Level-Zero runtime inside Fedora's intel-compute-runtime package specification file for its rpm.

https://src.fedoraproject.org/rpms/intel-compute-runtime/blob/rawhide/f/intel-compute-runtime.spec#_32

I'll try and compile it for installation myself but that is probably the reason why this isn't working. Thanks for the heads up, it means upstream will need to solve this. I'll close the issue if this is the only problem I run into.

**Comment by pacf531** [comment]
No, it seems like that didn't solve it. I compiled and installed it right into my lib64 folder and something still isn't right, I still only have the output I posted in a previous post running syscl-ls without the ext_oneapi_level_zero line even after a reboot and whatnot. Running the zello_world application provided inside the Level-Zero runtime repository, I get the following output.

```
❯ './zello_world'
Driver not initialized: ZE_RESULT_ERROR_UNINITIALIZED
Did NOT find matching ZE_DEVICE_TYPE_GPU device!
```

I ran ldd on zello_world to see if it wasn't picking up my compiled .so but it did pick it up.

```
❯ ldd '/home/simonlui/rpmbuild/BUILD/level-zero-1.8.8/build/redhat-linux-build/bin/zello_world'
	linux-vdso.so.1 (0x00007ffc93d97000)
	libze_loader.so.1 => /home/simonlui/rpmbuild/BUILD/level-zero-1.8.8/build/redhat-linux-build/lib/libze_loader.so.1 (0x00007f9a7a674000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f9a7a400000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f9a7a639000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9a7a223000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9a7a6dc000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9a7a143000)
```

The only .so object I could find relating to Level Zero inside the oneapi install I did in /opt/, I also ran ldd on and it seems to be able to find everything correctly.

```
❯ ldd /opt/intel/oneapi/compiler/2022.2.1/linux/lib/libpi_level_zero.so
	linux-vdso.so.1 (0x00007fffb4dc9000)
	libze_loader.so.1 => /lib64/libze_loader.so.1 (0x00007f6186ebe000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f6186eb9000)
	libsvml.so => /opt/intel/oneapi/compiler/2022.2.1/linux/compiler/lib/intel64_lin/libsvml.so (0x00007f6185800000)
	libirng.so => /opt/intel/oneapi/compiler/2022.2.1/linux/compiler/lib/intel64_lin/libirng.so (0x00007f6185400000)
	libimf.so => /opt/intel/oneapi/compiler/2022.2.1/linux/compiler/lib/intel64_lin/libimf.so (0x00007f6185000000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f6184f20000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f6186e97000)
	libintlc.so.5 => /opt/intel/oneapi/compiler/2022.2.1/linux/compiler/lib/intel64_lin/libintlc.so.5 (0x00007f6186e25000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6186e20000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f6184d43000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f618702f000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f6184a00000)
```

Not sure what the disconnect is unless the driver bits are missing for compute specifically in upstream Linux 6.0.11 I am running now.

**Comment by pacf531** [comment]
Solved in https://github.com/intel/compute-runtime/issues/601, apparently, the package in Fedora needed to be enabled to get things working. I built a custom version and got things working. I am seeing some weirdness on outputs I am running with my program but I will go and debug that  before I open a separate issue here.
