### ISSUE TITLE
Iris Xe graphics not supported?

### ISSUE THREAD

**Issue by reveperdu** [intel/intel-extension-for-pytorch#292]
I'm using Ubuntu 22.04 with TigerLake-LP GT2 graphics and i915 driver, and cpu is i5-11320H. After setting up oneapi and installing "patched" torch packages, I tried use xpu on torch, but it always says
"RuntimeError: Number of dpcpp devices should be greater than zero!"
and torch.xpu.is_available returns false
it also says" Warning: Overriding a previously registered kernel for the same operator and the same dispatch key" 
and "UserWarning: Failed to load image Python extension" when importing.
Does this mean my hardware is not supported?

**Comment by jingxu10** [comment]
iGPU is not on our support list yet.
https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/installation.html

Personal advice: this seems that driver is not correctly installed or not the correct driver version is installed. You can double confirm the driver installation.

**Comment by reveperdu** [comment]
Thanks a lot! @jingxu10

**Comment by reveperdu** [comment]
Hi, I just installed the driver packages listed on https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-jammy-legacy.html
and when I run the example codes again, it gave a different error.
RuntimeError: The program was built for 1 devices
Build program log for 'Intel(R) Iris(R) Xe Graphics [0x9a49]':
warning: module got recompiled from IR because provided native binary is incompatible with underlying device and/or driver [-Wrecompiled-from-ir]
 -999 (Unknown PI error)
(I'm using 5.19.0-28-generic kernel)
strangely, model=model.to('xpu')gave no error.
Does this mean that Xe Graphics can support oneapi but not the pytorch extension?

**Comment by jingxu10** [comment]
No, most likely because the driver you installed from that link got upgraded, and the new driver contains changes that causing this incompatibility.
Previously you can get the pytorch extension working, right?

**Comment by reveperdu** [comment]
> 
If you mean importing the extension, yes. But I haven't been able to utilize the gpu (e.g. running the example code)

**Comment by jingxu10** [comment]
Hi, as mentioned before, iGPU is not currently in our support list. Please check the installation guide above for our support list. Thank you.

**Comment by reveperdu** [comment]
oh, my mistake. Thanks for your patience!:)

**Comment by JamesSteel** [comment]
Is there any plans to support any of the already released iGPU (so Tiger Lake, Alder Lake, Raptor Lake)? Or will we have to wait for a new iGPU generation?

**Comment by jingxu10** [comment]
No, iGPUs are not in the official support plan yet.

**Comment by CarlGao4** [comment]
But it's interesting that Xe Graphics can actually run many of the codes
