### ISSUE TITLE
Doesn't work on intel devcloud.

### ISSUE THREAD

**Issue by BigWhitePolarBear** [intel/intel-extension-for-pytorch#298]
libmkl_sycl.so.3: cannot open shared object file: No such file or directory
​
it seems like 1.13.10+xpu version.

**Comment by jingxu10** [comment]
Please source mkl in basekit 2023.0.0. If this version doesn't exist on devcloud, please install it separately.
By the way, since currently ipex has driver as it's runtime dependency, different driver versions may behave differently. However, users cannot change the driver on devcloud. I would suggest to use the preconfigured one on devcloud.

**Comment by BigWhitePolarBear** [comment]
> Please source mkl in basekit 2023.0.0. If this version doesn't exist on devcloud, please install it separately. By the way, since currently ipex has driver as it's runtime dependency, different driver versions may behave differently. However, users cannot change the driver on devcloud. I would suggest to use the preconfigured one on devcloud.

I tried to use conda env in the terminal and succeed to import ipex. However, I cannot souce the 2023.0.0 version of mkl. Got error:

[W OperatorEntry.cpp:150] Warning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: torchvision::nms
    no debug info
  dispatch key: CPU
  previous kernel: registered at /build/intel-pytorch-extension/csrc/cpu/aten/TorchVisionNms.cpp:47
       new kernel: registered at /opt/workspace/vision/torchvision/csrc/ops/cpu/nms_kernel.cpp:112 (function registerKernel)
Traceback (most recent call last):
  File "/home/u172982/lenet5-mnist/origin-Copy1.py", line 59, in <module>
    model, optim = ipex.optimize(model, optimizer=optim)
  File "/glob/development-tools/versions/oneapi/2023.0.1/oneapi/intelpython/latest/envs/pytorch/lib/python3.9/site-packages/intel_extension_for_pytorch/frontend.py", line 474, in optimize
    optimized_model, optimized_optimizer = _copy_model_and_optimizer(model, optimizer)
  File "/glob/development-tools/versions/oneapi/2023.0.1/oneapi/intelpython/latest/envs/pytorch/lib/python3.9/site-packages/intel_extension_for_pytorch/frontend.py", line 29, in _copy_model_and_optimizer
    new_optimizer = copy.deepcopy(optimizer)
  File "/glob/development-tools/versions/oneapi/2023.0.1/oneapi/intelpython/latest/envs/pytorch/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'module' object

It seems like the code isn't compatible with python3.9. Must I change the oneapi to 2023.0.0 version?

**Comment by jingxu10** [comment]
Would you please try setting the `inplace` parameter of ipex.optimize function to `True`?
https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/api_doc.html#ipex.optimize

**Comment by BigWhitePolarBear** [comment]
> Would you please try setting the `inplace` parameter of ipex.optimize function to `True`? https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/api_doc.html#ipex.optimize

Yea. Actually the problem was I mistake the optim package as a param. Sorry.
I can use ipex now : ) .
U can fix the problem env problem in notebook. Other users might need it.
