### ISSUE TITLE
ImportError: libmkl_gnu_thread.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bouachalazhar** [intel/intel-extension-for-pytorch#300]
I have this :
`ImportError: libmkl_gnu_thread.so.2: cannot open shared object file: No such file or directory
`
System :
- Asus ZenBook UX325EA Windows 11
- WSL2 Ubuntu 22.04 Jammy
- Python 3.10.6
- IPEX 1.13.10+xpu
- PyTorch 1.13.1
- Intel i7 11th / Intel Iris Xe graphics

**Comment by jingxu10** [comment]
@sanchitintel

**Comment by sanchitintel** [comment]
@bouachalazhar, can you please specify how you installed IPEX? Thanks!

You can install mkl with `pip install mkl-static`

**Comment by bouachalazhar** [comment]
IPEX : 
- `python3 -m pip install intel_extension_for_pytorch`
- `python3 -m pip install intel_extension_for_pytorch==1.13.10+xpu -f https://developer.intel.com/ipex-whl-stable-xpu`

**Comment by sanchitintel** [comment]
Thanks for the info, @bouachalazhar! Please install `mkl` -

`python -m pip install mkl`

**Comment by bouachalazhar** [comment]
Doesn't work

**Comment by sanchitintel** [comment]
@bouachalazhar, you'd probably have to uninstall IPEX & reinstall it, although I'm not sure why dynamic linking didn't work after you installed mkl.

Otherwise, you can find `libmkl_gnu_thread.so.2` on your system (`cd /;find -type f -name "libmkl_gnu_thread.so.2"`).
Then add its path to the environment variable `LD_LIBRARY_PATH`:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:{add-path-here-after-removing-these-curvy-braces}`
And then try to run IPEX workloads

**Comment by sanchitintel** [comment]
@bouachalazhar, BTW your GPU is currently officially unsupported by IPEX.

**Comment by bouachalazhar** [comment]
I try to uninstall & reinstall IPEX and add its path but it doesn't work.

**Comment by bouachalazhar** [comment]
> @bouachalazhar, you'd probably have to uninstall IPEX & reinstall it, although I'm not sure why dynamic linking didn't work after you installed mkl.
> 
> Otherwise, you can find `libmkl_gnu_thread.so.2` on your system (`cd /;find -type f -name "libmkl_gnu_thread.so.2"`). Then add its path to the environment variable `LD_LIBRARY_PATH`: `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:{add-path-here-after-removing-these-curvy-braces}` And then try to run IPEX workloads

Same problem : `ImportError: libmkl_gnu_thread.so.2: cannot open shared object file: No such file or directory`

**Comment by jingxu10** [comment]
Please install all pytorch, torchvision and ipex with the command below.
`python -m pip install torch==1.13.0a0 torchvision==0.14.1a0 intel_extension_for_pytorch==1.13.10+xpu -f https://developer.intel.com/ipex-whl-stable-xpu`

It looks like you installed torch==1.13.1.

**Comment by sanchitintel** [comment]
@jingxu10, we don't currently support their GPU anyway

**Comment by jingxu10** [comment]
The problem itself is not related to iGPU, but the software stack installed. This import error is a pure software issue.
But as Sanchit said, iGPU is out of our support scope. There are very limited supports that we can provide after fixing this importing error at this moment.

**Comment by bouachalazhar** [comment]
> Please install all pytorch, torchvision and ipex with the command below. `python -m pip install torch==1.13.0a0 torchvision==0.14.1a0 intel_extension_for_pytorch==1.13.10+xpu -f https://developer.intel.com/ipex-whl-stable-xpu`
> 
> It looks like you installed torch==1.13.1.

I have an other error with PyTorch now, I uninstall & reinstall with `python3 -m pip install torch==1.13.0a0 torchvision==0.14.1a0 intel_extension_for_pytorch==1.13.10+xpu -f https://developer.intel.com/ipex-whl-stable-xpu` but after I see that `OSError: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory`.

I can read with `pip show detectron2 torch torchvision intel_extension_for_pytorch` : 

Name: detectron2
Version: 0.6
Summary: Detectron2 is FAIR's next-generation research platform for object detection and segmentation.
Home-page: https://github.com/facebookresearch/detectron2
Author: FAIR
Author-email: 
License: UNKNOWN
Location: /home/bouachalazhar/.local/lib/python3.10/site-packages
Requires: black, cloudpickle, fvcore, hydra-core, iopath, matplotlib, omegaconf, packaging, Pillow, pycocotools, tabulate, tensorboard, termcolor, timm, tqdm, yacs
Required-by: 
---
Name: torch
Version: 1.13.0a0+gitb1dde16
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/bouachalazhar/.local/lib/python3.10/site-packages
Requires: typing-extensions
Required-by: timm, torchvision
---
Name: torchvision
Version: 0.14.1a0+0504df5
Summary: image and video datasets and models for torch deep learning
Home-page: https://github.com/pytorch/vision
Author: PyTorch Core Team
Author-email: soumith@pytorch.org
License: BSD
Location: /home/bouachalazhar/.local/lib/python3.10/site-packages
Requires: numpy, pillow, requests, torch, typing-extensions
Required-by: timm
---
Name: intel-extension-for-pytorch
Version: 1.13.10+xpu
Summary: Intel® Extension for PyTorch*
Home-page: https://github.com/intel/intel-extension-for-pytorch
Author: Intel Corp.
Author-email: 
License: 
Location: /home/bouachalazhar/.local/lib/python3.10/site-packages
Requires: numpy, psutil
Required-by:

**Comment by jingxu10** [comment]
could you break down when do you see the mkl not found issue?
After importing torch or after importing intel-extension-for-pytorch?
You can try the following 2:
```python
import torch
```
```python
import torch
import intel-extension-for-pytorch
```
which one triggers that error?

**Comment by bouachalazhar** [comment]
> could you break down when do you see the mkl not found issue? After importing torch or after importing intel-extension-for-pytorch? You can try the following 2:
> 
> ```python
> import torch
> ```
> 
> ```python
> import torch
> import intel-extension-for-pytorch
> ```
> 
> which one triggers that error?

I can see this error after `import torch` and after `import intel_extension_for_pytorch`

**Comment by jingxu10** [comment]
Please activate MKL environment installed in oneAPI.
https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/installation.html#install-oneapi-base-toolkit

Suppose you installed oneAPI to `/opt/intel/oneapi`, you can activate it by the following command.
`source /opt/intel/oneapi/mkl/latest/env/vars.sh`

Then `python -c "import torch"`.

**Comment by jingxu10** [comment]
Please check the getting started at https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/getting_started.html#execution

**Comment by bouachalazhar** [comment]
> 

I do it but I have `python3 -c "import torch; print(torch.__version__)" -->1.13.0a0+gitb1dde16`

**Comment by jingxu10** [comment]
this is correct output.
The ImportError is gone now, right?

**Comment by jingxu10** [comment]
This issue is gone when you activate MKL env first with the `source` command.
Does this solution look good to you?

**Comment by bouachalazhar** [comment]
How activate MKL ? I think did it

**Comment by jingxu10** [comment]
Please check the comment at https://github.com/intel/intel-extension-for-pytorch/issues/300#issuecomment-1431218522
According to your comment at https://github.com/intel/intel-extension-for-pytorch/issues/300#issuecomment-1431269946, I think you got it working.

**Comment by bouachalazhar** [comment]
It doesn't work, I reintsall PyTorch, IPEX, MKL and oneAPI Base Toolkit but I always have : 
```
OSError                                   Traceback (most recent call last)
Cell In[3], line 1
----> 1 import torch
      2 import detectron2
      3 get_ipython().system('icc --version')

File ~/.local/lib/python3.10/site-packages/torch/__init__.py:191
    180 else:
    181     # Easy way.  You want this most of the time, because it will prevent
    182     # C++ symbols from libtorch clobbering C++ symbols from other
   (...)
    188     #
    189     # See Note [Global dependencies]
    190     if USE_GLOBAL_DEPS:
--> 191         _load_global_deps()
    192     from torch._C import *  # noqa: F403
    194 # Appease the type checker; ordinarily this binding is inserted by the
    195 # torch._C module initialization code in C

File ~/.local/lib/python3.10/site-packages/torch/__init__.py:153, in _load_global_deps()
    150 here = os.path.abspath(__file__)
    151 lib_path = os.path.join(os.path.dirname(here), 'lib', lib_name)
--> 153 ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)

File /usr/lib/python3.10/ctypes/__init__.py:374, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    371 self._FuncPtr = _FuncPtr
    373 if handle is None:
--> 374     self._handle = _dlopen(self._name, mode)
    375 else:
    376     self._handle = handle

OSError: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory
```

And with `python -c "import torch"`: 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bouachalazhar/.local/lib/python3.10/site-packages/torch/__init__.py", line 191, in <module>
    _load_global_deps()
  File "/home/bouachalazhar/.local/lib/python3.10/site-packages/torch/__init__.py", line 153, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory
```

**Comment by jingxu10** [comment]
> > 
> 
> I do it but I have `python3 -c "import torch; print(torch.__version__)" -->1.13.0a0+gitb1dde16`

Would you reproduce the steps when you got it working at this comment?

**Comment by bouachalazhar** [comment]
> > > 
> > 
> > 
> > I do it but I have `python3 -c "import torch; print(torch.__version__)" -->1.13.0a0+gitb1dde16`
> 
> Would you reproduce the steps when you got it working at this comment?

I can't reproduce, I'm lost really. Maybe could I reinstall mkl, ipex and PyTorch ?

**Comment by jingxu10** [comment]
Please let me double confirm several things first.
1. Did you run it with commands in WSL2 terminal, rather than IDEs? Let's start from terminal.
2. Did you install oneAPI 2023.0.0 with DPCPP compiler and oneMKL?
3. Did you install pytorch and ipex with `python -m pip install torch==1.13.0a0 torchvision==0.14.1a0 intel_extension_for_pytorch==1.13.10+xpu -f https://developer.intel.com/ipex-whl-stable-xpu`?

**Comment by bouachalazhar** [comment]
> Please let me double confirm several things first.
> 
> 1. Did you run it with commands in WSL2 terminal, rather than IDEs? Let's start from terminal.
> 2. Did you install oneAPI 2023.0.0 with DPCPP compiler and oneMKL?
> 3. Did you install pytorch and ipex with `python -m pip install torch==1.13.0a0 torchvision==0.14.1a0 intel_extension_for_pytorch==1.13.10+xpu -f https://developer.intel.com/ipex-whl-stable-xpu`?

1. Yes, I use my WSL2 Ubuntu terminal
2. Yes, I reinstall oneAPI 2023.0.0 with DPCPP compiler and oneMKL
3. Yes, I reinstall Pytorch and IPEX with the right command.

**Comment by jingxu10** [comment]
Suppose you have oneapi installed in <ONEAPI_ROOT>, what happens if you run the commands below?
```bash
source <ONEAPI_ROOT>/compiler/latest/env/vars.sh
source <ONEAPI_ROOT>/mkl/latest/env/vars.sh
python -c "import torch; print(torch.__version__);"
python -c "import torch; print(torch.__version__); import intel_extension_for_pytorch as ipex; print(ipex.__version__);"
```

**Comment by bouachalazhar** [comment]
``> Suppose you have oneapi installed in <ONEAPI_ROOT>, what happens if you run the commands below?
> 
> ```shell
> source <ONEAPI_ROOT>/compiler/latest/env/vars.sh
> source <ONEAPI_ROOT>/mkl/latest/env/vars.sh
> echo $LD_LIBRARY_PATH
> python -c "import torch; print(torch.__version__);"
> python -c "import torch; print(torch.__version__); import intel_extension_for_pytorch as ipex; print(ipex.__version__);"
> ```

This is my output : 
```
source /opt/intel/oneapi/compiler/latest/env/vars.sh
source /opt/intel/oneapi/mkl/latest/env/vars.sh
echo $LD_LIBRARY_PATH
python -c "import torch; print(torch.__version__);"
python -c "import torch; print(torch.__version__); import intel_extension_for_pytorch as ipex; print(ipex.__version__);"


/opt/intel/oneapi/mkl/2023.0.0/lib/intel64:/opt/intel/oneapi/compiler/2023.0.0/linux/lib:/opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64:/opt/intel/oneapi/compiler/2023.0.0/linux/lib/oclfpga/host/linux64/lib:/opt/intel/oneapi/compiler/2023.0.0/linux/compiler/lib/intel64_lin:/home/bouachalazhar/opt/intel/oneapi/mkl/latest::/home/bouachalazhar/portaudio:/usr/local/cuda-12.0/lib64
1.13.0a0+gitb1dde16
1.13.0a0+gitb1dde16
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
[W OperatorEntry.cpp:150] Warning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: torchvision::nms
    no debug info
  dispatch key: CPU
  previous kernel: registered at /build/intel-pytorch-extension/csrc/cpu/aten/TorchVisionNms.cpp:47
       new kernel: registered at /opt/workspace/vision/torchvision/csrc/ops/cpu/nms_kernel.cpp:112 (function registerKernel)
/home/bouachalazhar/.local/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension:
  warn(f"Failed to load image Python extension: {e}")
1.13.10+xpu
```

**Comment by jingxu10** [comment]
It runs as expected now.

**Comment by bouachalazhar** [comment]
> It runs as expected from your output.

But when I run on VS Code I have always `OSError: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory
`

**Comment by jingxu10** [comment]
You can take reference to this solution https://www.intel.com/content/www/us/en/develop/documentation/oneapi-fpga-development-with-vs-code-for-linux/top/set-environment-variables.html
Or would you google with keywords something like `How do I set Environment Variables in Visual Studio code?`?

**Comment by bouachalazhar** [comment]
> Would you google with keywords something like `How do I set Environment Variables in Visual Studio code?`?

I already installed IPEX and PyTorch in past and use it without set Environment Variables in Visual Studio code. Because your solution doesn't work.

**Comment by jingxu10** [comment]
Which version did you use without setting env vars in the past?
For using IPEX GPU version, activating dpcpp and mkl env is required.

**Comment by akashdhamasia12** [comment]
In you vscode python script, you may add:

import os
os.system("source /opt/intel/oneapi/setvars.sh")
os.system("conda activate ipex1.13.10+xpu") #if you are using conda envs.. else your env.

your remaining code.

Then you should not get the error when running it from vscode.

**Comment by bouachalazhar** [comment]
> 

I do it any time or just one times and I use python3.10.6 without conda.

**Comment by KimBioInfoStudio** [comment]
may i know r u using `coderunner` or vscode terminal?
if `coderunner` may be add  folowing into top of ur python scripts will work
```python 
import os
os.system("source /opt/intel/oneapi/setvars.sh")
```

Or would u like try add `source /opt/intel/oneapi/setvars.sh` to ur `.bashrc` or rc file of what kind shell u r  using
