### ISSUE TITLE
error: Double type is not supported on this platform

### ISSUE THREAD

**Issue by juzi5201314** [intel/intel-extension-for-pytorch#303]
I ran the sample code from the readme: https://github.com/intel/intel-extension-for-pytorch#inference-on-gpu
got the following error:
```
error: Double type is not supported on this platform.
in kernel: 'typeinfo name for void at::AtenIpexTypeXPU::launch_unrolled_kernel<4, at::AtenIpexTypeXPU::impl::abs_kernel(at::TensorIterator&)::'lambda'()::operator()() const::'lambda2'()::operator()() const::'lambda'(long), xpu::dpcpp::Array<char*, 2>, TrivialOffsetCalculator<1, unsigned int>, TrivialOffsetCalculator<1, unsigned int>, at::native::Memory::LoadWithCast<1, false>, at::native::Memory::StoreWithCast<false> >(long, at::AtenIpexTypeXPU::impl::abs_kernel(at::TensorIterator&)::'lambda'()::operator()() const::'lambda2'()::operator()() const::'lambda'(long) const&, xpu::dpcpp::Array<char*, 2>, TrivialOffsetCalculator<1, unsigned int>, TrivialOffsetCalculator<1, unsigned int>, at::native::Memory::LoadWithCast<1, false>, at::native::Memory::StoreWithCast<false>)::'lambda'(sycl::_V1::handler&)::operator()(sycl::_V1::handler&) const::'lambda'(sycl::_V1::nd_item<1>)'
error: backend compiler failed build.
```

`wsl2 ubuntu20.04`
`arc a750`
resizable bar: `on`

install cmd: `python -m pip install torch==1.13.0a0 torchvision==0.14.1a0 intel_extension_for_pytorch==1.13.10+xpu -f https://developer.intel.com/ipex-whl-stable-xpu-idp`

**Comment by jingxu10** [comment]
This is expected, since Arc GPU doesn't have double precision support from hardware level.
Execution on this operator is skipped.

**Comment by jgong5** [comment]
Are you running the provided sample code without changes? I don't think we should report errors on the examples as is.

**Comment by juzi5201314** [comment]
In fact I'm using [stable-diffusion-webui](https://github.com/jbaboval/stable-diffusion-webui/tree/oneapi) on an arc graphics card (see [this issue](https://github.com /AUTOMATIC1111/stable-diffusion-webui/issues/6417)) and this fork uses intel-extension-for-pytorch.
Oddly enough it seems like I'm the only one getting this error. So I created this issue when I found that the error seemed to come from intel-extension-for-pytorch.
Sorry to bother if the error has nothing to do with intel-extension-for-pytorch.

**Comment by BA8F0D39** [comment]
@juzi5201314 
The error only happens if you have the wrong version of oneAPI and the wrong version of python. If you use the docker containers from Intel, it doesn't happen.

https://medium.com/intel-analytics-software/stable-diffusion-with-intel-arc-gpus-f2986bba8365

**Comment by juzi5201314** [comment]
> @juzi5201314 仅当您使用错误版本的 oneAPI 和错误版本的 python 时才会发生此错误。如果您使用英特尔的 docker 容器，则不会发生这种情况。
> 
> https://medium.com/intel-analytics-software/stable-diffusion-with-intel-arc-gpus-f2986bba8365

I updated the oneapi version and the above error disappeared and replaced by a new error `RuntimeError: An OpenCL error occurred: -6`, oh. .

**Comment by BA8F0D39** [comment]
@juzi5201314 
`RuntimeError: An OpenCL error occurred: -6` means not enough RAM on CPU


How much RAM do you have on CPU?

**Comment by juzi5201314** [comment]
> @juzi5201314 `RuntimeError: An OpenCL error occurred: -6`表示 CPU 内存不足
> 
> 您在 CPU 上有多少 RAM？
> 
> 您可能需要 32 GB 的 RAM。

I put a limit of 32g ram on wsl (which is all I have) but to no avail

**Comment by BA8F0D39** [comment]
@juzi5201314 
Run with
`--lowvram  --lowram`

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Troubleshooting

**Comment by juzi5201314** [comment]
> @juzi5201314 Run with `--lowvram` or `--lowram`
> 
> https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Troubleshooting

I've tried this and it's still the same

**Comment by juzi5201314** [comment]
The current problem seems to have nothing to do with intel-extension-for-pytorch
