### ISSUE TITLE
About performance optimization after using bf16

### ISSUE THREAD

**Issue by KepingYan** [intel/intel-extension-for-pytorch#305]
Hi, I'm testing the performance optimization brought by bfloat16, and the machine is `Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz`. But I found that after adding it, the training time becomes longer. I'm wondering what might be causing it.
Code is the same as the example in tutorial except that the model is resnet18.
```python
import torch
import torchvision
import intel_extension_for_pytorch as ipex

LR = 0.001
DOWNLOAD = True
DATA = 'datasets/CIFAR10/'

transform = torchvision.transforms.Compose([
    torchvision.transforms.Resize((224, 224)),
    torchvision.transforms.ToTensor(),
    torchvision.transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])
train_dataset = torchvision.datasets.CIFAR10(
        root=DATA,
        train=True,
        transform=transform,
        download=DOWNLOAD,
)
train_loader = torch.utils.data.DataLoader(
        dataset=train_dataset,
        batch_size=128
)

model = torchvision.models.resnet18()
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = LR, momentum=0.9)
model.train()
# model, optimizer = ipex.optimize(model, optimizer=optimizer, dtype=torch.bfloat16)
model, optimizer = ipex.optimize(model, optimizer=optimizer)

import time
train_start = time.time()
for batch_idx, (data, target) in enumerate(train_loader):
    optimizer.zero_grad()
    # with torch.cpu.amp.autocast():
    output = model(data)
    loss = criterion(output, target)
    loss.backward()
    optimizer.step()
train_end = time.time()
print("train cost: ", train_end-train_start)
```
Output
```
without bf16
train cost:  547.4949421882629
with bf16
train cost:  578.2296633720398
```
I also profiled it.
```
profiler setting:
with torch.profiler.profile(
        schedule=torch.profiler.schedule(
            wait=4,
            warmup=2,
            active=8,
            repeat=2),
        on_trace_ready=torch.profiler.tensorboard_trace_handler('./profiler_resnet'),
        with_stack=True
    ) as profiler:
```
Show top5 operator:
**without bf16**
<img width="773" alt="image" src="https://user-images.githubusercontent.com/97155466/220942237-ebd48280-f47b-4a4a-abdb-4f9a75ec8b03.png">

**with bf16**
<img width="770" alt="image" src="https://user-images.githubusercontent.com/97155466/220942038-8ee18a9f-d3f3-4255-bd02-3f170cf8b7f7.png">

**Comment by jgong5** [comment]
The slowdown of bf16 is expected since the Xeon 8358 CPU you are using doesn't have bf16 dot-product acceleration supports. Therefore compute-intensive ops like convolution and matmul are emulated with fp32 and slower than fp32 due to extra type-cast cost. You would need a Cooper Lake or Sapphire Rapids CPU to get bf16 speedups.
