### ISSUE TITLE
Advice on integration of custom kernels with pytorch

### ISSUE THREAD

**Issue by salykova** [intel/intel-extension-for-pytorch#314]
Dear developers and community,

Pytorch has nice tutorial [cpp_extension](https://pytorch.org/tutorials/advanced/cpp_extension.html) on how to implement custom cuda kernels and integrate them with pytorch (aka custom operations). I would like to seek your advice on what is the best/easiest way of integrating custom SYCL/oneAPI C++  kernels with pytorch, especially how to manipulate and communicate with ```torch::Tensor```. Are there any examples / docs / tutorials for this? Many thanks in advance!

**Comment by jingxu10** [comment]
Is this what you need?
https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/features/DPC++_Extension.html

**Comment by salykovaa** [comment]
Yes, thank you! I will close the issue.
