### ISSUE TITLE
GPU installation totally broken.

### ISSUE THREAD

**Issue by alyashev** [intel/intel-extension-for-pytorch#318]
### Describe the issue

these are your scripts
python -m pip install torch==1.13.0a0 -f https://developer.intel.com/ipex-whl-stable-xpu
python -m pip install intel_extension_for_pytorch==1.13.10+xpu -f https://developer.intel.com/ipex-whl-stable-xpu

1. https://developer.intel.com/ipex-whl-stable-xpu is not accessible, have you tried it at all?
2. the 3d script is missing
   pip install torchvision==0.14.1a0 -f https://developer.intel.com/ipex-whl-stable-xpu
3. there no any words that oneAPI has to be also activated besides a vague reference to GPU installation page. Why would a developer assume this 2 pages are connected and how?
4. after oneAPI is activated in a generic mode: source /opt/intel/oneapi/setvars.sh the reference to the pytorch is lost.
5. it means the user have to figure out what pieces of the entire oneAPI she/he has to activate manually and how.

**Comment by jingxu10** [comment]
Root cause:
When oneAPI environment is activated, if IDP is installed, IDP env will be activated. Activating IDP overwrites the existing python environment.
This is not an IPEX issue. Will add a note to getting started guide.
