### ISSUE TITLE
AVX2 checker behavior changes in ipex 2.0

### ISSUE THREAD

**Issue by rnwang04** [intel/intel-extension-for-pytorch#326]
### Describe the bug

When we conducted GitHub Action testing, we found that all machines that could run normally in versions prior to ipex2.0 encountered errors after upgrading to ipex 2.0：
```python
import intel_extension_for_pytorch as ipex
```
error message is:
`SystemExit: ERROR! Intel® Extension for PyTorch* only works on machines with instruction sets equal or newer than AVX2, which are not detected on the current machine.`

I found that the code for avx2 checking in the IPEX has changed.
I wonder what specific conditions are currently being used for avx2 checking? And whether the current testing standard too strict?

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu117
PyTorch CXX11 ABI: No
IPEX version: 2.0.0+cpu
IPEX commit: c52d951
Build type: Release

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
IGC version: N/A
CMake version: version 3.26.1
Libc version: glibc-2.31

Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-144-generic-x86_64-with-glibc2.17
Is XPU available: False
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration: 

Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   52 bits physical, 57 bits virtual
CPU(s):                          160
On-line CPU(s) list:             0-159
Thread(s) per core:              2
Core(s) per socket:              40
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8380 CPU @ 2.30GHz
Stepping:                        6
CPU MHz:                         800.188
CPU max MHz:                     3400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4600.00
Virtualization:                  VT-x
L1d cache:                       3.8 MiB
L1i cache:                       2.5 MiB
L2 cache:                        100 MiB
L3 cache:                        120 MiB
NUMA node0 CPU(s):               0-39,80-119
NUMA node1 CPU(s):               40-79,120-159
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.0.0
[pip3] numpy==1.23.1
[pip3] pytorch-lightning==1.6.4
[pip3] torch==2.0.0
[pip3] torchmetrics==0.11.0
[pip3] torchvision==0.15.1
[conda] intel-extension-for-pytorch 2.0.0                    pypi_0    pypi
[conda] numpy                     1.23.0                   pypi_0    pypi
[conda] pytorch-lightning         1.6.4                    pypi_0    pypi
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] torchmetrics              0.11.0                   pypi_0    pypi
[conda] torchvision               0.15.1                   pypi_0    pypi

**Comment by jingxu10** [comment]
@xuhancn

**Comment by ZsgsDesign** [comment]
### Cause

Confirmed on `IPEX 2.0` with `PyTorch 2.0.0`.

During XCR check, specific virtual machines can't simulate XCR0 correctly and might give a `false` value for `CPUFeature::os_avx2()`.

https://github.com/intel/intel-extension-for-pytorch/blob/3b1eaec6249108f7b059da38b0a2811189a839ee/csrc/cpu/isa/cpu_feature.cpp#L187-L192

### Solution

Modify the CMake file to disable XCR check to support Virtual Machines.

https://github.com/intel/intel-extension-for-pytorch/blob/3b1eaec6249108f7b059da38b0a2811189a839ee/csrc/cpu/CMakeLists.txt#L76-L77

@jingxu10 close this issue?

**Comment by rnwang04** [comment]
> ### Cause
> Confirmed on `IPEX 2.0` with `PyTorch 2.0.0`.
> 
> During XCR check, specific virtual machines can't simulate XCR0 correctly and might give a `false` value for `CPUFeature::os_avx2()`.
> 
> https://github.com/intel/intel-extension-for-pytorch/blob/3b1eaec6249108f7b059da38b0a2811189a839ee/csrc/cpu/isa/cpu_feature.cpp#L187-L192
> 
> ### Solution
> Modify the CMake file to disable XCR check to support Virtual Machines.
> 
> https://github.com/intel/intel-extension-for-pytorch/blob/3b1eaec6249108f7b059da38b0a2811189a839ee/csrc/cpu/CMakeLists.txt#L76-L77
> 
> @jingxu10 close this issue?

Thanks for the fix!! Look forward to your next release! : )

**Comment by harindercnvrg** [comment]
@rnwang04 is this issue fixed? 
I see you have just added a comment to add definition to disable this.
Is there any way to disable in the meantime directly?
and how do I proceed to install IPEX after I make changes in the cmake?

**Comment by rnwang04** [comment]
> @rnwang04 is this issue fixed? I see you have just added a comment to add definition to disable this. Is there any way to disable in the meantime directly? and how do I proceed to install IPEX after I make changes in the cmake?

I have not tested yet and I am just waiting the next release to have a try.

**Comment by harindercnvrg** [comment]
@rnwang04 is there a way I can get on with using this patch immediately without waiting for the next release?
Please let me know the steps.
