### ISSUE TITLE
Broken license metadata

### ISSUE THREAD

**Issue by bstriner** [intel/intel-extension-for-pytorch#344]
### Describe the bug

License metadata doesn't go to PyPI so shows up as unknown license when doing license reviews.

### Versions

Issue is with PyPI website itself, current version. No metadata block on left hand side with the license: https://pypi.org/project/intel-extension-for-pytorch/

**Comment by bstriner** [comment]
License metadata update in #343. Cheers!

**Comment by jingxu10** [comment]
Thanks for the bug fixing. Please check the master branch for updated codes. Due to our current mechanism, I cherry picked your commit into our internal repo and synced out.

**Comment by gujinghui** [comment]
merged
