### ISSUE TITLE
huggingface accelerate supported?

### ISSUE THREAD

**Issue by human-01** [intel/intel-extension-for-pytorch#352]
### Describe the issue

Dear all, 

I get the following error when running below code: NotImplementedError: Could not run 'aten::empty_strided' with arguments from the 'XPU' backend. 

I am guessing that accelerate is not supported? Are there any workarounds? 

```
#pip install accelerate
import torch
from transformers import T5Tokenizer, T5ForConditionalGeneration

tokenizer = T5Tokenizer.from_pretrained("google/flan-t5-large")
model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-large", device_map={"":"xpu:1"}, torch_dtype=torch.float16)

print(model.hf_device_map)

import intel_extension_for_pytorch as ipex

input_text = "translate English to German: How old are you?"
input_ids = tokenizer(input_text, return_tensors="pt").input_ids.to(torch.device('xpu:1'))

model = ipex.optimize(model)

outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0]))
```

**Comment by gujinghui** [comment]
We landed the XPU support in HF accelerate several days ago.
Could you try the latest code base of accelerate?

https://github.com/huggingface/accelerate/commit/612ecef7b8f8e7a405cfba61261f599c47f59ca1
https://github.com/huggingface/accelerate/commit/ab379793d44be16d8fcac5c098a3ab9b6f5a7ec3

**Comment by human-01** [comment]
@gujinghui wow! 

The power of open source, the issue is indeed resolved when I install dev version of accelerate. 

Thank you very much!
