### ISSUE TITLE
Python 3.11 support for xpu-master

### ISSUE THREAD

**Issue by pioto1225** [intel/intel-extension-for-pytorch#355]
Hi Intel,

Just a question if/when xpu-master branch will support Python3.11. 
This would help with usability.

Thank you.
Piotr

**Comment by jingxu10** [comment]
Since PyTorch 1.13 doesn't support 3.11 official, we don't provide the support yet. Once xpu-master is rebased to 2.0, 3.11 should be supported. The rebasing work is undergoing.

**Comment by pioto1225** [comment]
Hi again,

Is there an ETA?

**Comment by jingxu10** [comment]
Hi, it will be released by end of this week.

**Comment by pioto1225** [comment]
great, thank you!

**Comment by pioto1225** [comment]
The latest xpu release indeed works with Python 3.11. I'll close the issue. Thanks!
