### ISSUE TITLE
Request intel xe graphic and intel xe max gpu support for stable diffusion

### ISSUE THREAD

**Issue by Nathan-dm** [intel/intel-extension-for-pytorch#360]
### Describe the issue

im now using direct ML but it got bad memory optimization (crash oftenly) i hope IPEX would support my gpus ASAP
im happy to see if IPEX support multi gpu as well (like Intel Deep link)
https://www.intel.com/content/www/us/en/architecture-and-technology/adaptix/deep-link-support.html

my system spec:
Windows 10 64 bit (22H2)
Acer Swift 3X
I5 1135G7
16 GB Ram
Intel xe graphic 80eu (shared memory)
intel xe max (4gb vram)

**Comment by jingxu10** [comment]
@gujinghui  @tye1

**Comment by gujinghui** [comment]
May I know the error details on your platform? Out of memory?

**Comment by Nathan-dm** [comment]
yes, out of memory issue and crash after switching model 
https://github.com/vladmandic/automatic/issues/1017
https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/38#issuecomment-1536626425

**Comment by tripzero** [comment]
You don't have a lot of memory there at 4gb.  I don't know that I've ever seen any stable diffusion model fit in <8gb...

**Comment by tripzero** [comment]
Stable Diffusion via the diffusers library works for me on the A770.  Uses just under 8gb of RAM for 720x512 and fp16.

**Comment by Nathan-dm** [comment]
> Stable Diffusion via the diffusers library works for me on the A770. Uses just under 8gb of RAM for 720x512 and fp16.

it because your gpu supported by IPEX, im now using directML and able generate max 512x640 resolution with full precision

**Comment by Nathan-dm** [comment]
> You don't have a lot of memory there at 4gb. I don't know that I've ever seen any stable diffusion model fit in <8gb...

well let me tell you, ever heard of xformers? it kinda optimization to accelerate image generation on nvidia card, it make nvidia card more efficient by reducing vram usage and making them faster, and similar tool for AMD card it called ROCm and Intel have IPEX and Openvino

last week i tried to use Openvino using GIMP extension created by Intel openvino team, it still on early development and didn't have much stable diffusion features compared to popular webui like A1111 and Vladmandic (the installation a little tricky)
reference:
https://github.com/intel/openvino-ai-plugins-gimp
https://www.youtube.com/watch?v=q8xJjPBjqso

**Comment by ColonelPhantom** [comment]
> You don't have a lot of memory there at 4gb. I don't know that I've ever seen any stable diffusion model fit in <8gb...

Most implementations support options like `--medvram` that shuffle data in and out of VRAM. This isn't a perfect solution as it has a performance penalty, but with `--medvram` my RX 580 4GB works fine in ROCm.

@Nathan-dm Vladmandic should support Arc via Intel Extension for Pytorch (with `--use-ipex`. I don't know if it works on Windows, I only tried Linux). I tried to get it running on my laptop with UHD 620 integrated graphics (the only halfway recent Intel GPU I own) which didn't work, but maybe your Xe/Xe Max will fare better (although I don't think anything other than DG2/Alchemist is actually supported).

**Comment by Nathan-dm** [comment]
> Most implementations support options like `--medvram` that shuffle data in and out of VRAM. This isn't a perfect solution as it has a performance penalty, but with `--medvram` my RX 580 4GB works fine in ROCm.
>
i already tried using `--medvram` argument on still get OOM error on DirectML. 
im using this webui to run directML
https://github.com/lshqqytiger/stable-diffusion-webui-directml
2 days ago,I already reported this problem to repo owner. maybe you want to take a look
https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/173

> @Nathan-dm Vladmandic should support Arc via Intel Extension for Pytorch (with `--use-ipex`. I don't know if it works on Windows, I only tried Linux). I tried to get it running on my laptop with UHD 620 integrated graphics (the only halfway recent Intel GPU I own) which didn't work, but maybe your Xe/Xe Max will fare better (although I don't think anything other than DG2/Alchemist is actually supported).
>
i have already tried vladmandic repo which also support directML (performance is slightly worse than lshqqytiger repo)  and IPEX,  using `--use-ipex` and get this error. 
<details><summary>console logs</summary>
<p>

```
Already up to date.
Using VENV: C:\Stable Diffusion 1\automatic\venv
12:05:51-691073 INFO     Starting SD.Next
12:05:51-694744 INFO     Python 3.10.10 on Windows
12:05:51-734740 INFO     Version: 4867dafa Fri Jun 23 08:00:51 2023 -0400
12:05:52-428460 INFO     Using CPU-only Torch
12:05:53-511852 INFO     Torch 2.0.1+cpu
12:05:53-513343 ERROR    Could not load torch: No module named 'intel_extension_for_pytorch'
Press any key to continue . . .
``` 

</p>
</details>

**Comment by ColonelPhantom** [comment]
`--medvram` is very tight when you're on 4GB, try `--lowvram` which is much slower but nearly guaranteed to work.

For ipex in vladmandic, you need to add `--reinstall` because IPEX needs another version of Torch (1.13 instead of 2.0).

**Comment by Nathan-dm** [comment]
> `--medvram` is very tight when you're on 4GB, try `--lowvram` which is much slower but nearly guaranteed to work.
> 
I am unable to utilize all of my available VRAM; it is limited to only 3GB. If I try to use more than that, I encounter an out-of-memory (OOM) error, please take a look my issues that i had been created 2 day ago for more info

> For ipex in vladmandic, you need to add `--reinstall` because IPEX needs another version of Torch (1.13 instead of 2.0).
>
Adding the  `--reinstall` argument reverts Torch back to version 2.0 so i tried install it manualy and here you go, same result 
<details><summary>console log</summary>
<p>

```
Already up to date.
Using VENV: C:\Stable Diffusion 1\automatic\venv
13:21:44-879223 INFO     Starting SD.Next
13:21:44-883233 INFO     Python 3.10.10 on Windows
13:21:44-913332 INFO     Version: 4867dafa Fri Jun 23 08:00:51 2023 -0400
13:21:45-319557 INFO     Using CPU-only Torch
13:21:46-055386 INFO     Torch 1.13.1+cpu
13:21:46-057171 ERROR    Could not load torch: No module named 'intel_extension_for_pytorch'
Press any key to continue . . .

``` 

</p>
</details>

**Comment by ColonelPhantom** [comment]
> I am unable to utilize all of my available VRAM; it is limited to only 3GB. If I try to use more than that, I encounter an out-of-memory (OOM) error, please take a look my issues that i had been created 2 day ago for more info

Wouldn't know about that tbh, just a fellow user who has tried to use IPEX for stable diffusion.

> 13:21:46-057171 ERROR    Could not load torch: No module named 'intel_extension_for_pytorch'

It looks like IPEX is still not being installed. Are you sure you have `--reinstall` and `--use-ipex` at the same time? Alternatively, try to run the following, with the venv active:
```
python -m pip install torch==1.13.0a0+git6c9b55e intel_extension_for_pytorch==1.13.120+xpu pytorch-lightning==1.8.6 -f https://developer.intel.com/ipex-whl-stable-xpu
```
That should install the Intel-patched version of Pytorch as well as IPEX, and downgrades some dependency that conflicts with IPEX.

**Comment by Nathan-dm** [comment]
>That should install the Intel-patched version of Pytorch as well as IPEX, and downgrades some dependency that conflicts with IPEX.
>
still won't work
<details><summary>Details</summary>
<p>

```
C:\Stable Diffusion 1\automatic\venv\Scripts>activate

(venv) C:\Stable Diffusion 1\automatic\venv\Scripts>python -m pip install torch==1.13.0a0+git6c9b55e intel_extension_for_pytorch==1.13.120+xpu pytorch-lightning==1.8.6 -f https://developer.intel.com/ipex-whl-stable-xpu
Looking in links: https://developer.intel.com/ipex-whl-stable-xpu
ERROR: Could not find a version that satisfies the requirement torch==1.13.0a0+git6c9b55e (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.13.0a0+git6c9b55e
``` 

</p>
</details>

**Comment by ColonelPhantom** [comment]
Make sure to use a supported Python version, such as 3.10

**Comment by Nathan-dm** [comment]
> Make sure to use a supported Python version, such as 3.10
>
<details><summary>Details</summary>
<p>

```
C:\Stable Diffusion 1\automatic\venv\Scripts>activate

(venv) C:\Stable Diffusion 1\automatic\venv\Scripts>python --version
Python 3.10.10

(venv) C:\Stable Diffusion 1\automatic\venv\Scripts>python -m pip install torch==1.13.0a0+git6c9b55e intel_extension_for_pytorch==1.13.120+xpu pytorch-lightning==1.8.6 -f https://developer.intel.com/ipex-whl-stable-xpu
Looking in links: https://developer.intel.com/ipex-whl-stable-xpu
ERROR: Could not find a version that satisfies the requirement torch==1.13.0a0+git6c9b55e (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.13.0a0+git6c9b55e
``` 

</p>
</details>

**Comment by ColonelPhantom** [comment]
It seems IPEX XPU is only available for Linux, looking at https://developer.intel.com/ipex-whl-stable-xpu

According to https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/installation.html WSL2 should also work, so you can run in WSL2 and install Stable Diffusion with IPEX there.
