### ISSUE TITLE
Failed to install the GPU software packages

### ISSUE THREAD

**Issue by jfsunx** [intel/intel-extension-for-pytorch#365]
### Describe the issue

Installation encountered an issue on the Ubuntu 22.04.02 LTS subsystem on WSL2

I followed the GPU Installation Guide. [https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/installation.html](url)

After installing the latest GPU Drivers under Windows. When I install Intel GPU Driver followed by the guide in WSL2 Ubuntu

> Besides that, please follow Steps 4 & 5 of the [Installation Guides](https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-jammy-arc.html#step-4-install-run-time-packages) on WSL2 Ubuntu 22.04.

In Step 4, Install run-time packages--install the GPU software packages
`sudo apt-get install -y gawk libc6-dev udev\
  intel-opencl-icd intel-level-zero-gpu level-zero \
  intel-media-va-driver-non-free libmfx1 libmfxgen1 libvpl2 \
  libegl-mesa0 libegl1-mesa libegl1-mesa-dev libgbm1 libgl1-mesa-dev libgl1-mesa-dri \
  libglapi-mesa libgles2-mesa-dev libglx-mesa0 libigdgmm12 libxatracker2 mesa-va-drivers \
  mesa-vdpau-drivers mesa-vulkan-drivers va-driver-all vainfo`

Return
`E: Unable to locate package intel-level-zero-gpu 
E: Unable to locate package level-zero 
E: Unable to locate package libmfxgen1`

I have made an update by `sudo apt update && sudo apt upgrade`

**Comment by jingxu10** [comment]
@sanchitintel

**Comment by stacksmash76** [comment]
@jfsunx did you also do step 1 (Add package repository)?
```
sudo apt-get install -y gpg-agent wget
```
```
wget -qO - https://repositories.intel.com/graphics/intel-graphics.key | \
  sudo gpg --dearmor --output /usr/share/keyrings/intel-graphics.gpg
```
```
echo 'deb [arch=amd64,i386 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/graphics/ubuntu jammy arc' | \
  sudo tee  /etc/apt/sources.list.d/intel.gpu.jammy.list
```

PS. Maybe as a side note, can someone from Intel confirm that `linux-image-5.19.0-35-generic` is still available? Last time I did an Ubuntu installation there was only `linux-image-5.19.0-42-generic`. Might be worthwhile making docs clearer on how to find the correct 5.19 image.

**Comment by jfsunx** [comment]
@stacksmash76 Thank you for your reply. This can work through step 1.

PS: It seems that the installation guide needs to be updated.
