### ISSUE TITLE
DNNl MaxPool can't get nan result when input's value is nan

### ISSUE THREAD

**Issue by XiaobingSuper** [intel/intel-extension-for-pytorch#37]
DNNL MaxPool should get nan value when input values are all nan.

test case:
```
import torch
import intel_pytorch_extension
from torch._six import inf, nan
intel_pytorch_extension.core.enable_auto_dnnl()

input = torch.full([1, 1] + 2 * [3], nan).to('dpcpp')
output = F.max_pool2d(x, 3, 3)
```

**Comment by EikanWang** [comment]
@pinzhenx , If a tensor cotains nan data, what's the beahavior of dnnl?

**Comment by pinzhenx** [comment]
> If a tensor cotains nan data, what's the beahavior of dnnl?

UB

**Comment by XiaobingSuper** [comment]
It will always return the minimum number of float data type(-3.4028E+38).

**Comment by EikanWang** [comment]
> It will always return the minimum number of float data type(-3.4028E+38).
Could I say that DNNL treats NAN as zero?
