### ISSUE TITLE
Windows build guide (xpu-master branch) uses wildcards but git doesn't expand them

### ISSUE THREAD

**Issue by a-One-Fan** [intel/intel-extension-for-pytorch#382]
### Describe the issue

[This guide](https://github.com/intel/intel-extension-for-pytorch/blob/xpu-master/docs/tutorials/windows/installation.md)
This line:
`git apply ../intel-extension-for-pytorch/torch_patches/*.patch`
This wildcard will not be expanded, and the patch literally named `*.patch` is not found

Some possible replacements:
`ls ..\intel-extension-for-pytorch\torch_patches\*.patch | % {git apply $_.FullName}` for Powershell
`FOR /F %G IN ('dir /b /s ..\intel-extension-for-pytorch\torch_patches\*.patch') DO git apply %G` for CMD
CMD needs the \ slashes.

**Comment by jingxu10** [comment]
Hi, We don't currently support native Windows yet. Please run the script in Linux or WSL.

**Comment by Vipitis** [comment]
have you been able to build it successfully nevertheless?

Will "use WSL" continue to be your official stance? WSL requires Hyper-V which is not allowed by a lot of anti cheat software.
