### ISSUE TITLE
Is there support for embedding on xpu?

### ISSUE THREAD

**Issue by evelinamorim** [intel/intel-extension-for-pytorch#392]
### Describe the issue

If I tried the following lines of code:

```
import torch

embedding = torch.nn.Embedding(10, 3)
embedding.to('xpu')
```

And I got  the following error:

```
 PyTorch is not linked with support for xpu devices
```

So, is there any support for Embedding layer in the intel-extension?

**Comment by gujinghui** [comment]
pls import ipex first.

```
import torch
import intel_extension_for_pytorch
```

**Comment by evelinamorim** [comment]
Ok. Sorry, I thought that the installed version of pytorch version was enough.
