### ISSUE TITLE
prebuilt wheels for windows native missing?

### ISSUE THREAD

**Issue by Vipitis** [intel/intel-extension-for-pytorch#397]
### Describe the issue

given the release of  v2.0.110+xpu we seem to have native support as the [docs](https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/installations/windows.html) exist and these include instructions to use prebuilt wheels.

I don't see any prebuilt wheels https://developer.intel.com/ipex-whl-stable-xpu however that could be an caching issue as was in several previous issues #361 and #364. However I did try with different browsers, devices, phone data and VPN and would see the same list of linux only wheels, including the new release.
![image](https://github.com/intel/intel-extension-for-pytorch/assets/23384483/07c217c1-9e78-49dc-9acd-cf66250b1416)

My attempt at building from source was unsuccessful (only troch worked), but that is likely to me being inexperienced with it. There are several issues with the documentation and script and I had to make some modifications, so perhaps these could be improved. Perhaps someone else had success to build this on Windows Native and would be able to share their solution

**Comment by Vipitis** [comment]
here are the issues with the documentation:
- `wget` doesn't exist in windows cmd
- `ls` doesn't exist, `dir` might work
- there wouldn't be a shell script, but the batch script.

the batch script seems to have trouble with giving full paths as args because windows includes spaces in the default oneapi path. There might be a global sys var `%ONEAPI_ROOT%` which could be used instead. 
putting the `call` arg in quotations and brackets seem to avoid issues with white spaces in the name. I made the following changes to the script and that worked for me. 
![image](https://github.com/intel/intel-extension-for-pytorch/assets/23384483/8818a99b-9456-4573-913e-44eceeb1b5ef)

**Comment by jingxu10** [comment]
Appreciate for pointing these issues out. We've fixed them in the documentation.

@min-jean-cho  could you take a look at the compile_bundle.bat issue mentioned above?

**Comment by Vipitis** [comment]
prebuilt wheels for windows now appear, I haven't had the chance to try them myself yet, although heard from others that it appears to be working. So I believe the original issue is resolved. 

it might also be possible to use wget within PowerShell on windows if you specify an outfile. 

The batch script issue might just be my end (as I haven't used a conda env).

**Comment by min-jean-cho** [comment]
Thanks @Vipitis for reporting the issue. Thank you for catching the issue with `compile_bundle.bat` windows batch script not correctly handling paths that contain spaces. The issue will shortly be fixed.

**Comment by min-jean-cho** [comment]
Additionally, please feel free to refer to [here](https://github.com/intel/intel-extension-for-pytorch/blob/xpu-master/docs/tutorials/windows/installation.md#building-intel-extension-for-pytorch-on-native-windows) on how to build from source.
