### ISSUE TITLE
Support for Llama 2 LLM optimization using IPEX

### ISSUE THREAD

**Issue by jerin-scalers-ai** [intel/intel-extension-for-pytorch#414]
### Describe the issue

We are using Llama-2 chat model from Hugging face using transformers. 
To enable IPEX for inference, Is it valid to use ipex.optimize() for transformers LLM models ?

We have seen unreleased dev branch( [v2.1.0.dev%2Bcpu.llm](https://github.com/intel/intel-extension-for-pytorch/tree/v2.1.0.dev%2Bcpu.llm) )  using ipex._optimize_transformers() for optimization. 

So please suggest the correct way to optimize Llama-2 LLM model (from huggingface) using IPEX?

**Comment by nedo99** [comment]
You have an example here as part of BigDL package from intel analytics: https://github.com/intel-analytics/BigDL/tree/main/python/llm/example/transformers/transformers_int4/llama2

**Comment by jingxu10** [comment]
Please use the `ipex._optimize_transformers()` against LLM models that use Transformers.
You can take reference to https://github.com/intel/intel-extension-for-pytorch/raw/v2.1.0.dev%2Bcpu.llm/examples/cpu/inference/python/llm/run_generation.py

**Comment by jgong5** [comment]
Yes, please use the experimental API `ipex._optimize_transformers` temporarily meanwhile we are adding `ipex.optimize_transformers` as the standard API which you can use in the future.

**Comment by jerin-scalers-ai** [comment]
Thanks for the clarification.
