### ISSUE TITLE
GPU utilization is too low when inference on windows arc

### ISSUE THREAD

**Issue by leonardozcm** [intel/intel-extension-for-pytorch#422]
### Describe the issue

I am following this guideline on windows and manage to run Whisper-tiny(144MB) on my 730M. It is ok to run but takes a really long time(about 418s), and I observed that the GPU monitor's render usage is very low, at 1%.

Whisper-tiny(144MB, 418s) takes a long time but answer is right.
![image](https://github.com/analytics-zoo/nano/assets/26900100/415e5a03-a1d7-49e3-b005-ffe8bdae80b6)

torch: 2.0.0a0+gitd475571
ipex: 2.0.110+git679be34

here is my script, run with `python xxx.py --repo-id-or-model-path WHISPER_PATH`
```python

import torch
import intel_extension_for_pytorch as ipex
import time
import argparse

from transformers import AutoModelForSpeechSeq2Seq
from transformers import WhisperProcessor
from datasets import load_dataset


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Recognize Tokens using `generate()` API for Whisper model')
    parser.add_argument('--repo-id-or-model-path', type=str, default="./models/whisper-tiny",
                        help='The huggingface repo id for the Whisper model to be downloaded'
                             ', or the path to the huggingface checkpoint folder')
    parser.add_argument('--repo-id-or-data-path', type=str,
                        default="hf-internal-testing/librispeech_asr_dummy",
                        help='The huggingface repo id for the audio dataset to be downloaded'
                             ', or the path to the huggingface dataset folder')
    parser.add_argument('--language', type=str, default="english",
                        help='language to be transcribed')

    args = parser.parse_args()
    model_path = args.repo_id_or_model_path
    dataset_path = args.repo_id_or_data_path
    language = args.language

    # Load model in 4 bit,
    # which convert the relevant layers in the model into INT4 format
    model = AutoModelForSpeechSeq2Seq.from_pretrained(model_path)
    model.to('xpu')
    model.config.forced_decoder_ids = None

    # Load processor
    processor = WhisperProcessor.from_pretrained(model_path)
    forced_decoder_ids = processor.get_decoder_prompt_ids(language=language, task="transcribe")

    # Load dummy dataset and read audio files
    ds = load_dataset(dataset_path, "clean", split="validation")

    # Generate predicted tokens
    print("start inference")
    with torch.inference_mode():
        sample = ds[0]["audio"]

        input_features = processor(sample["array"],
                                   sampling_rate=sample["sampling_rate"],
                                   return_tensors="pt").input_features.to('xpu')
        st = time.time()
        # if your selected model is capable of utilizing previous key/value attentions
        # to enhance decoding speed, but has `"use_cache": false` in its model config,
        # it is important to set `use_cache=True` explicitly in the `generate` function
        # to obtain optimal performance with BigDL-LLM INT4 optimizations
        print("start generate")
        predicted_ids = model.generate(input_features,
                                       forced_decoder_ids=forced_decoder_ids)
        end = time.time()
        output_str = processor.batch_decode(predicted_ids, skip_special_tokens=True)
        print(f'Inference time: {end-st} s')
        print('-'*20, 'Output', '-'*20)
        print(output_str)

```

Any suggestion or attempt to try?

**Comment by leonardozcm** [comment]
Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
                   aten::copy_        26.40%      101.431s        26.40%      101.431s      45.000ms          2254
                     aten::add        24.82%       95.338s        24.82%       95.338s     265.565ms           359
            aten::index_select        18.21%       69.965s        18.21%       69.965s        2.799s            25
                     aten::max        15.02%       57.715s        15.02%       57.715s        1.154s            50
                     aten::any         5.56%       21.342s        11.11%       42.684s       21.342s             2
                    aten::prod         2.58%        9.917s         2.58%        9.918s     396.702ms            25
                aten::_softmax         2.42%        9.282s         4.83%       18.563s      45.498ms           408
                     aten::mul         1.30%        5.011s         1.30%        5.011s      17.896ms           280
                    aten::gelu         1.18%        4.532s         1.18%        4.533s      42.760ms           106
       aten::native_layer_norm         1.01%        3.867s         7.19%       27.609s      82.661ms           334
                      aten::ne         0.45%        1.720s         0.45%        1.721s      68.820ms            25
                      aten::eq         0.45%        1.719s         0.45%        1.719s      66.120ms            26
                     aten::cat         0.27%        1.024s         0.27%        1.024s       4.320ms           237
                   aten::fill_         0.15%     573.086ms         0.15%     573.086ms      16.374ms            35

I've make a profile on windows arc(only records cpu kernel submit time), and it shows that the some basic operations like op (like a `add` will cost 265.565ms) currently consume a lot of time in a single execution.

**Comment by jgong5** [comment]
> I've make a profile on windows arc(only records cpu kernel submit time)

What is the time used in GPU? Can you also share the chrome trace?

**Comment by leonardozcm** [comment]
It seems like this is related to warm up time at the first time, and returns normal in the following optimization.
I will close this issue as solved.
