### ISSUE TITLE
Performance comparison with and without IPEX

### ISSUE THREAD

**Issue by rishucoding** [intel/intel-extension-for-pytorch#424]
### Describe the issue

Hello IPEX team,

I am wondering if there is any documentation (white-paper, research paper, blog, wiki, etc) which quantifies the benefit reaped from adopting IPEX compared to vanilla pytorch? Particularly, I am interested in knowing how the IPEX has improved the performance of recommendation system models like DLRMs, and popular image classification models for either of inference or training situations.

Could you please share insights? 

Thanks,
Rishabh Jain

**Comment by jingxu10** [comment]
Please take a reference to https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/blogs_publications.html

**Comment by jgong5** [comment]
You may also check the performance comparison here: https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/performance.html. Please note that the numbers were measured from an older version while the existing features in IPEX are being upstreamed and newer features are added to IPEX. We will update the numbers from time to time.

For the particular questions about DLRMs and image classification models:
1. For DLRM, we have optimized frontend modules for merged embedding bag and fused interaction: https://github.com/intel/intel-extension-for-pytorch/blob/master/intel_extension_for_pytorch/nn/modules/merged_embeddingbag.py, https://github.com/intel/intel-extension-for-pytorch/blob/master/intel_extension_for_pytorch/cpu/nn/interaction.py
2. For image classifications, IPEX provides better static int8 quantization support via quantization API (https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/api_doc.html#module-ipex.quantization). The feature is being upstreamed to PyTorch and will be part of PyTorch 2.1 as an experimental feature.

**Comment by rishucoding** [comment]
These resources are very useful. Thanks for sharing them.
Quick question: https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/performance.html -- does the performance comparison mean optimized IPEX over optimized vanilla Pytorch?

**Comment by jgong5** [comment]
> Quick question: https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/performance.html -- does the performance comparison mean optimized IPEX over optimized vanilla Pytorch?

Yes, that's correct.

**Comment by jgong5** [comment]
@rishucoding  I'm closing the issue. Let me know if you have more questions.
