### ISSUE TITLE
InstanceNorm2d only works with parameter "affine = True"

### ISSUE THREAD

**Issue by Fora888** [intel/intel-extension-for-pytorch#434]
### Describe the bug

**Description**
I encountered a bug when using torch.nn.InstanceNorm2d without learnable affine parameters (affine=False). It throws an error, indicating that the tensor does not have a device. 

**Minimal Example**
```
import torch
import intel_extension_for_pytorch as ipex

t = torch.rand(1, 5, 10, 20).to("xpu")

#Works
instanceNormAffine = torch.nn.InstanceNorm2d(5, affine = True, device = "xpu")
instanceNormAffine(t)

#Throws error message
instanceNorm = torch.nn.InstanceNorm2d(5, device = "xpu")
instanceNorm(t)
```

**Error**
```
Traceback (most recent call last):
  File "C:\Users\Familie Stieffenhofe\Seafile\InstanceNorm2DTest.py", line 10, in <module>
    instanceNorm(t)
  File "C:\ProgramData\mambaforge\envs\pytorch-arc\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\mambaforge\envs\pytorch-arc\Lib\site-packages\torch\nn\modules\instancenorm.py", line 74, in forward
    return self._apply_instance_norm(input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\mambaforge\envs\pytorch-arc\Lib\site-packages\torch\nn\modules\instancenorm.py", line 34, in _apply_instance_norm
    return F.instance_norm(
           ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\mambaforge\envs\pytorch-arc\Lib\site-packages\torch\nn\functional.py", line 2495, in instance_norm
    return torch.instance_norm(
           ^^^^^^^^^^^^^^^^^^^^
RuntimeError: tensor does not have a device
```

**Expected Behavior**
Both torch.nn.InstanceNorm2d calls should work without errors, with the second one applying instance normalization without learnable affine parameters.

### Versions

Collecting environment information...
PyTorch version: 2.0.0a0+gitc6a572f
PyTorch CXX11 ABI: No
IPEX version: 2.0.110+gitba7f6c1
IPEX commit: ba7f6c127
Build type: Release

OS: Microsoft Windows 10 Home
GCC version: N/A
Clang version: N/A
IGC version: 2023.2.0 (2023.2.0.20230627)
CMake version: version 3.26.4-msvc4
Libc version: N/A

Python version: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:23:48) [MSC v.1936 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is XPU available: True
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration:
[0] _DeviceProperties(name='Intel(R) Arc(TM) A770 Graphics', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=0, total_memory=15930MB, max_compute_units=512, gpu_eu_count=512)
Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture=9
CurrentClockSpeed=3700
DeviceID=CPU0
Family=107
L2CacheSize=2048
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3700
Name=AMD Ryzen 5 3400G with Radeon Vega Graphics
ProcessorType=3
Revision=6145

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.0.110+gitba7f6c1
[pip3] memory-efficient-attention-pytorch==0.1.6
[pip3] numpy==1.26.0
[pip3] torch==2.0.0a0+gitc6a572f
[pip3] torchinfo==1.8.0
[conda] intel-extension-for-pytorch 2.0.110+gitba7f6c1          pypi_0    pypi
[conda] memory-efficient-attention-pytorch 0.1.6                    pypi_0    pypi
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] torch                     2.0.0a0+gitc6a572f          pypi_0    pypi
[conda] torchinfo                 1.8.0                    pypi_0    pypi

**Comment by kta-intel** [comment]
Thank you for raising this, we are looking into the issue

**Comment by gujinghui** [comment]
should be already fixed in latest code base.

**Comment by kta-intel** [comment]
@Fora888 May you try on the latest code base? Follow [instructions to install from source](https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/installation.html#install-via-source-compilation). Otherwise you may wait for 2.1 release, which should be soon

**Comment by Fora888** [comment]
Thank you for your replies! I've already implemented a workaround on my side, so everything is working as expected for me. If you don't mind I'm just going to wait for the 2.1 release for a proper fix.
