### ISSUE TITLE
 Fetch corresponding `sycl::queue` for CPU device

### ISSUE THREAD

**Issue by XianFuWongIntel** [intel/intel-extension-for-pytorch#472]
### Describe the issue

Hi there, 

As stated in the [documentation](https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/features/DPC%2B%2B_Extension.html#fetching-the-corresponding-sycl-queue), there is a way to fetch corresponding `sycl::queue` for XPU device:
```
auto device_type = c10::DeviceType::XPU;
c10::impl::VirtualGuardImpl impl(device_type);
c10::Stream c10_stream = impl.getStream(c10::Device(device_type));
auto& queue = xpu::get_queue_from_stream(c10_stream);
```

Is there a similar way for CPU device? I would like to run some SYCL code on CPU tensor.

I did experiment with creating new `sycl::queue`:
```
sycl::queue q(sycl::cpu_selector{});
```
 but this approach hurts performance a lot where this also requires `q.wait()` at the end of kernel code.

**Comment by jingxu10** [comment]
CPU device is currently not enabled with `sycl`

**Comment by XianFuWongIntel** [comment]
Aight, thanks.
