### ISSUE TITLE
source build for fails for ipex on windows 11

### ISSUE THREAD

**Issue by rairatne** [intel/intel-extension-for-pytorch#474]
### Describe the bug

HW used: ADL i7 (12700H)/ARC770

OS Name Microsoft Windows 11 Pro: Version 10.0.22621 Build 22621
ARC Driver: 31.0.101.4972 / 31.0.101.4953 {Tried with both drivers}

Pre-requisites:
miconda3(latest)
git for windows
Python: 3.9
oneAPI: 2024.0 {as no download link is available for 2023.2 anymore}
Build Tool for visual studio 2022: MSVC build 143 and Windows 11 SDK

Steps to reproduce:
launch oneapi command prompt for visual studio 2022
![image](https://github.com/intel/intel-extension-for-pytorch/assets/81367619/d95f115d-d83e-4207-9e96-17bc70ea8f91)

1. conda create --name llmenv python=3.9
2. conda activate llm
3. call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat" -> DPCPPROOT
4. call "C:\Program Files (x86)\Intel\oneAPI\compiler\mkl\env\vars.bat" -> MKLROOT
5. curl -o compile_bundle.bat https://github.com/intel/intel-extension-for-pytorch/raw/v2.0.110%2Bxpu/scripts/compile_bundle.bat
6. 
7. #Edit this two echo lines inside compile_bundle.bat
Line 23:     echo DPC++ compiler environment %DPCPP_ENV% doesn't seem to exist. ->  echo DPC++ compiler environment **"%DPCPP_ENV%"** doesn't seem to exist.

Line 30: echo oneMKL environment %ONEMKL_ENV% doesn't seem to exist. -> echo oneMKL environment **"%ONEMKL_ENV%"** doesn't seem to exist.
8.  compile_bundle.bat "C:\Program Files (x86)\Intel\oneAPI\compiler\latest" "C:\Program Files (x86)\Intel\oneAPI\compiler\mkl"

Output Pytorch Build fails with this error: 
![image](https://github.com/intel/intel-extension-for-pytorch/assets/81367619/7af01125-64da-4f1f-867b-17e2f23a1a81)

### Versions

Collecting environment information...
PyTorch version: N/A
PyTorch CXX11 ABI: N/A
IPEX version: N/A
IPEX commit: N/A
Build type: N/A

OS: Microsoft Windows 11 Pro
GCC version: N/A
Clang version: 16.0.5
IGC version: 2024.0.0 (2024.0.0.20231017)
CMake version: version 3.27.7
Libc version: N/A

Python version: 3.9.18 (main, Sep 11 2023, 14:09:26) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is XPU available: N/A
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration:
N/A
Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture=9
CurrentClockSpeed=2300
DeviceID=CPU0
Family=198
L2CacheSize=11776
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2300
Name=12th Gen Intel(R) Core(TM) i7-12700H
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.2
[conda] mkl-include               2024.0.0                 pypi_0    pypi
[conda] mkl-static                2024.0.0                 pypi_0    pypi
[conda] numpy                     1.26.2                   pypi_0    pypi

**Comment by rairatne** [comment]
Error Details:

[4874/5870] Building CXX object caffe2\CMakeFiles\torch_cp...\__\aten\src\ATen\native\cpu\PowKernel.cpp.DEFAULT.cpp.obj
FAILED: caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/cpu/PowKernel.cpp.DEFAULT.cpp.obj
C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe  /nologo /TP -DAT_PER_OPERATOR_HEADERS -DCPUINFO_SUPPORTED_PLATFORM=1 -DFMT_HEADER_ONLY=1 -DIDEEP_USE_MKL -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DUSE_C10D_GLOO -DUSE_DISTRIBUTED -DUSE_EXTERNAL_MZCRC -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE=1 -D_OPENMP_NOFORCE_MANIFEST -D_UCRT_LEGACY_INFINITY -Dtorch_cpu_EXPORTS -IC:\Users\intel\Documents\ipex\pytorch\build\aten\src -IC:\Users\intel\Documents\ipex\pytorch\aten\src -IC:\Users\intel\Documents\ipex\pytorch\build -IC:\Users\intel\Documents\ipex\pytorch -IC:\Users\intel\Documents\ipex\pytorch\cmake\..\third_party\benchmark\include -IC:\Users\intel\Documents\ipex\pytorch\third_party\onnx -IC:\Users\intel\Documents\ipex\pytorch\build\third_party\onnx -IC:\Users\intel\Documents\ipex\pytorch\third_party\foxi -IC:\Users\intel\Documents\ipex\pytorch\build\third_party\foxi -IC:\Users\intel\Documents\ipex\pytorch\torch\csrc\api -IC:\Users\intel\Documents\ipex\pytorch\torch\csrc\api\include -IC:\Users\intel\Documents\ipex\pytorch\caffe2\aten\src\TH -IC:\Users\intel\Documents\ipex\pytorch\build\caffe2\aten\src\TH -IC:\Users\intel\Documents\ipex\pytorch\build\caffe2\aten\src -IC:\Users\intel\Documents\ipex\pytorch\build\caffe2\..\aten\src -IC:\Users\intel\Documents\ipex\pytorch\torch\csrc -IC:\Users\intel\Documents\ipex\pytorch\third_party\miniz-2.1.0 -IC:\Users\intel\Documents\ipex\pytorch\third_party\kineto\libkineto\include -IC:\Users\intel\Documents\ipex\pytorch\third_party\kineto\libkineto\src -IC:\Users\intel\Documents\ipex\pytorch\aten\..\third_party\catch\single_include -IC:\Users\intel\Documents\ipex\pytorch\aten\src\ATen\.. -IC:\Users\intel\Documents\ipex\pytorch\c10\.. -IC:\Users\intel\Documents\ipex\pytorch\third_party\pthreadpool\include -IC:\Users\intel\Documents\ipex\pytorch\third_party\cpuinfo\include -IC:\Users\intel\Documents\ipex\pytorch\third_party\fbgemm\include -IC:\Users\intel\Documents\ipex\pytorch\third_party\fbgemm -IC:\Users\intel\Documents\ipex\pytorch\third_party\fbgemm\third_party\asmjit\src -IC:\Users\intel\Documents\ipex\pytorch\third_party\ittapi\src\ittnotify -IC:\Users\intel\Documents\ipex\pytorch\third_party\FP16\include -IC:\Users\intel\Documents\ipex\pytorch\third_party\fmt\include -IC:\Users\intel\Documents\ipex\pytorch\build\third_party\ideep\mkl-dnn\third_party\oneDNN\include -IC:\Users\intel\Documents\ipex\pytorch\third_party\ideep\mkl-dnn\third_party\oneDNN\src\..\include -IC:\Users\intel\Documents\ipex\pytorch\third_party\flatbuffers\include -external:IC:\Users\intel\Documents\ipex\pytorch\build\third_party\gloo -external:IC:\Users\intel\Documents\ipex\pytorch\cmake\..\third_party\gloo -external:IC:\Users\intel\Documents\ipex\pytorch\cmake\..\third_party\googletest\googlemock\include -external:IC:\Users\intel\Documents\ipex\pytorch\cmake\..\third_party\googletest\googletest\include -external:IC:\Users\intel\Documents\ipex\pytorch\third_party\protobuf\src -external:I"C:\Program Files (x86)\Intel\oneAPI\mkl\latest\include" -external:IC:\Users\intel\Documents\ipex\pytorch\third_party\XNNPACK\include -external:IC:\Users\intel\Documents\ipex\pytorch\third_party\ittapi\include -external:IC:\Users\intel\Documents\ipex\pytorch\cmake\..\third_party\eigen -external:I"C:\Program Files (x86)\Intel\oneAPI\dnnl\latest\include" -external:IC:\Users\intel\Documents\ipex\pytorch\third_party\ideep\include -external:IC:\Users\intel\Documents\ipex\pytorch\caffe2 -external:W0 /DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DHAVE_AVX2_CPU_DEFINITION /O2 /Ob2 /DNDEBUG /w /bigobj -DNDEBUG -std:c++17 -MD -DCAFFE2_USE_GLOO -DTH_HAVE_THREAD /EHsc /DNOMINMAX /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -O2 -DCAFFE2_BUILD_MAIN_LIB -DONNX_BUILD_MAIN_LIB -openmp:experimental /fp:strict  /DCPU_CAPABILITY=DEFAULT /DCPU_CAPABILITY_DEFAULT /showIncludes /Focaffe2\CMakeFiles\torch_cpu.dir\__\aten\src\ATen\native\cpu\PowKernel.cpp.DEFAULT.cpp.obj /Fdcaffe2\CMakeFiles\torch_cpu.dir\ /FS -c C:\Users\intel\Documents\ipex\pytorch\build\aten\src\ATen\native\cpu\PowKernel.cpp.DEFAULT.cpp
C:\Users\intel\Documents\ipex\pytorch\aten\src\ATen/cpu/vec/vec_base.h(135): fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\CxxFE\sl\p1\c\toinil.c', line 910)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information

**Comment by jingxu10** [comment]
@min-jean-cho @ashokei

**Comment by boyu-chen-intern** [comment]
hi，rairatne，have you solved this problem？

**Comment by rairatne** [comment]
Haven't tried after this report.

**Comment by boyu-chen-intern** [comment]
> > hi，rairatne，have you solved this problem？
> 
> Haven't tried after this report.

Thanks for your reply, I have found a solution.

Torch has officially fixed it in the latest code: [Fix MSVC 14.38 - VS 2022 Build] (https://github.com/pytorch/pytorch/pull/122120)

Therefore, you need to use the latest code, remove the command in 'compile_buddle.bat' to check the torch version, and let the torch use the latest code

**Comment by rairatne** [comment]
> s officially fixed it in the latest code: [Fix MSVC 14.38 - VS 2022 Bui

Thanks, Chen, for the info
