### ISSUE TITLE
Inquiry Regarding Multi-GPU Support in Intel Extension for PyTorch

### ISSUE THREAD

**Issue by kunger97** [intel/intel-extension-for-pytorch#494]
### Describe the issue

I am reaching out as an enthusiast, not a developer, with a keen interest in exploring the capabilities of Intel's extensions for PyTorch. I have been experimenting with your library in a testing environment, specifically the Intel Developer Cloud, which is equipped with four Intel(R) Data Center GPUs Max 1100.

During my testing, I observed that when executing the `torch.xpu.device_count()` function, the library reports only one available device, despite the presence of four GPUs on the server. I am curious to know if the Intel Extension for PyTorch supports multi-GPU parallel processing and if there are any specific steps or configurations required to enable it.

sycl-ls show
```
[opencl:cpu:0] Intel(R) OpenCL, Intel(R) Xeon(R) Platinum 8480+ 3.0 [2023.16.7.0.21_160000]
[opencl:acc:1] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2023.16.7.0.21_160000]
[opencl:gpu:2] Intel(R) OpenCL Graphics, Intel(R) Data Center GPU Max 1100 3.0 [23.22.26516.32]
[opencl:gpu:3] Intel(R) OpenCL Graphics, Intel(R) Data Center GPU Max 1100 3.0 [23.22.26516.32]
[opencl:gpu:4] Intel(R) OpenCL Graphics, Intel(R) Data Center GPU Max 1100 3.0 [23.22.26516.32]
[opencl:gpu:5] Intel(R) OpenCL Graphics, Intel(R) Data Center GPU Max 1100 3.0 [23.22.26516.32]
[opencl:cpu:6] Intel(R) OpenCL, Intel(R) Xeon(R) Platinum 8480+ 3.0 [2023.16.7.0.21_160000]
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Data Center GPU Max 1100 1.3 [1.3.26516]
```
### update
after unset ONEAPI_DEVICE_SELECTOR it show 4 when i call function `torch.xpu.device_count()`. But i still want to know if the Intel Extension for PyTorch supports multi-GPU parallel processing

**Comment by jgong5** [comment]
cc @gujinghui

**Comment by gujinghui** [comment]
Yes. It supports multi-GPU. But by design, only level_zero device will be recognized.
As you saw in sycl-ls output lines, there's only one level_zero device, or your log is not complete?

`[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Data Center GPU Max 1100 1.3 [1.3.26516]`

**Comment by kunger97** [comment]
I have solved the problem of only one level_zero device. It is the problem of the ONEAPI_DEVICE_SELECTOR environment variable. Regarding multi-GPU parallel processing, is there any sample code in the document?

**Comment by alexanderfrey** [comment]
So is multi gpu training and inference on ARC supported? Thanks in advance !
