### ISSUE TITLE
Dead link to Installation Guide

### ISSUE THREAD

**Issue by saforem2** [intel/intel-extension-for-pytorch#496]
The link for the [Installation Guide](https://github.com/intel/intel-extension-for-pytorch/blob/5ed3a2413db5f0a5e53bcca0b3e84a814d87bb50/README.md?plain=1#L48) in the [GPU Version](https://github.com/intel/intel-extension-for-pytorch#gpu-version) of the Installation section from the README is broken.

> Compilation instruction of the latest GPU code base xpu-main branch can be found at [~~Installation Guide~~](https://github.com/intel/intel-extension-for-pytorch/blob/xpu-main/docs/tutorials/installation.md#install-via-compiling-from-source).

**Comment by tye1** [comment]
@jingxu10 README under 'xpu-main' branch has been resolved. Please fix README under 'main' branch.

**Comment by ZhaoqiongZ** [comment]
Hi @tye1 , main and xpu-main are both updated.

**Comment by ZhaoqiongZ** [comment]
Hi @saforem2, thanks a lot for pointing the issue out, it is now resolved!
