### ISSUE TITLE
安装包没有更新到pypl吗

### ISSUE THREAD

**Issue by Metasymbols** [intel/intel-extension-for-pytorch#498]
### Describe the issue

没有的话，给中国区一个镜像地址啊

**Comment by ZailiWang** [comment]
这里有安装指引 https://intel.github.io/intel-extension-for-pytorch/index.html#installation 
对于cpu版本，直接`pip install`就可以，xpu版本需要指定`--extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/cn/`。请再试一下，如果还是不行，反馈下具体报错信息。谢谢！
