### ISSUE TITLE
Clarity on compatible pytorch versions for xpu ipex?

### ISSUE THREAD

**Issue by garrett361** [intel/intel-extension-for-pytorch#507]
### Describe the issue

Hi, I'm finding the version compatibility between `ipex` and `torch` a bit confusing and was hoping for some clarification. Which versions of `torch` are compatible with `ipex==v2.1.10+xpu`?

On [the Installation Docs page](https://intel.github.io/intel-extension-for-pytorch/index.html#installation) for the v2.1.10+xpu version of `ipex` I see the following message:

> Intel® Extension for PyTorch* [v2.1.10+xpu](https://github.com/intel/intel-extension-for-pytorch/tree/v2.1.10%2Bxpu) has to work with PyTorch*/libtorch [v2.1.*](https://github.com/pytorch/pytorch/tree/v2.1.0) (patches needed).

This makes it sound like multiple `torch` versions are compatible: any `2.1.*` version.  But then the [v2.1.10+xpu release notes](https://github.com/intel/intel-extension-for-pytorch/releases/tag/v2.1.10%2Bxpu) specifically mention torch 2.1.0 and this i also the version hard coded in `scripts/compile_bundle.sh`:

https://github.com/intel/intel-extension-for-pytorch/blob/7085fc83eb48fc8df863b457b7c37ab146fd295d/scripts/compile_bundle.sh#L8-L8

So, should any `2.1.*` version of `torch` be compatible, or only `2.1.0`?  Thank you!

Screenshots below for what I'm seeing in the docs.
<img width="1109" alt="Scherm­afbeelding 2024-01-10 om 14 19 55" src="https://github.com/intel/intel-extension-for-pytorch/assets/44747910/4b467ba1-0b14-4566-995f-8a2dd60c35b2">
<img width="1110" alt="Scherm­afbeelding 2024-01-10 om 14 20 16" src="https://github.com/intel/intel-extension-for-pytorch/assets/44747910/3f2917cf-061b-49b2-8117-722064f3a474">

**Comment by jingxu10** [comment]
Makes sense. Thanks for the comment. We will remove this note.

**Comment by garrett361** [comment]
@jingxu10 is the answer that it’s strictly  2.1.0 compatible, then?

**Comment by jingxu10** [comment]
yes, please use the torch binary we released if you install it with pip, or apply patches if you would like to compile it from source. For source compilation, you can use the provided script to automate the compilation.
This note applies to CPU only packages, but not to XPU packages at this moment.

**Comment by garrett361** [comment]
Thank you for clarifying!
