### ISSUE TITLE
Server down for ipex installation

### ISSUE THREAD

**Issue by michaelmalice** [intel/intel-extension-for-pytorch#509]
### Describe the issue

I've been trying to download IPEX today and it seems the server is down. It also looks like a new address is being used since the last time i installed it. Both links below, the new one and the old one, are not responding.

https://pytorch-extension.intel.com/release-whl/stable/xpu/us/
https://developer.intel.com/ipex-whl-stable-xpu

**Comment by jgong5** [comment]
@michaelmalice Thanks for reporting this. @jingxu10 May I know how we can address the problem?

**Comment by jingxu10** [comment]
Thanks for reporting the issue. Looking into it.

**Comment by jingxu10** [comment]
back to service now.
