### ISSUE TITLE
intel/intel-extension-for-pytorch:xpu-jupyter does not include jupyter server

### ISSUE THREAD

**Issue by tkatila** [intel/intel-extension-for-pytorch#516]
### Describe the bug

The xpu-jupyter tagged pytorch image doesn't include jupyter server. Compared to the '2.1.0-pip-jupyter' image, xpu-jupyter's last Dockerfile clause is:
` USER user`
when it should be something like
`CMD ["bash" "-c" "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/jupyter --port $PORT --ip 0.0.0.0 --no-browser --allow-root"]`

### Versions

na

**Comment by vishnumadhu365** [comment]
@tkatila Tuomas, Thanks for reporting the issue, can you help provide some more context around it : 
- Where are you sourcing the xpu-jupyter image from
- provide the link to the Dockerfile

**Comment by tkatila** [comment]
From https://hub.docker.com/r/intel/intel-extension-for-pytorch/tags full image path: docker.io/intel/intel-extension-for-pytorch:xpu-jupyter
I don't know the Dockerfile, I presume it's somewhere in this project.

**Comment by jingxu10** [comment]
looking into it.

**Comment by jingxu10** [comment]
@tye1  fyi

**Comment by tye1** [comment]
@sramakintel could you please check?

**Comment by sramakintel** [comment]
@tkatila thanks for reaching out. After inspecting the dockerfile, The `xpu-jupyter` container doesn't have jupyter server. The dockerfile can be found here https://github.com/intel/ai-containers/blob/main/pytorch/Dockerfile#L196-L216. We are working on fixing the issue with a new container.

**Comment by sramakintel** [comment]
@tkatila the new images have been pushed please use either pip or idp(Intel Distribution of Python) versions of the xpu-jupyter images: `docker pull intel/intel-extension-for-pytorch:2.1.10-xpu-pip-jupyter` or `docker pull intel/intel-extension-for-pytorch:2.1.10-xpu-idp-jupyter`. Let us know if this solves your issues.

**Comment by tkatila** [comment]
Thanks @sramakintel 

Jupyter server is indeed in the container. Is there something special with the startup of the container? I'm running it with this: `docker run --device /dev/dri/ --network=host -e PORT=8888 --rm -it intel/intel-extension-for-pytorch:2.1.10-xpu-pip-jupyter`
But the example xpu notebook fails to detect GPUs:
![image](https://github.com/intel/intel-extension-for-pytorch/assets/14214982/37f870db-2f62-409d-ac2e-b8e593a35bde)

**Comment by sramakintel** [comment]
@tkatila I ran the same command you shared and I am able to detect the GPUs. 
![image](https://github.com/intel/intel-extension-for-pytorch/assets/41214682/20936e94-954c-4c8b-9e11-8fdba23f2650)

Have you installed GPU drivers on the host machine? https://dgpu-docs.intel.com/driver/installation.html

**Comment by tkatila** [comment]
@sramakintel ok, thanks.

> Have you installed GPU drivers on the host machine? https://dgpu-docs.intel.com/driver/installation.html

Yes, the GPU drivers should be fine. ITEX detects the GPUs so I wonder what's the difference.

**Comment by tkatila** [comment]
The issue with no GPUs was related to groups. When I added `render` group to the `docker run` command, ipex started to see the GPU.

Closing this now.
