### ISSUE TITLE
add build system

### ISSUE THREAD

**Issue by martin19** [intel/intel-extension-for-pytorch#520]
Hi, I'm following instructions here:
`https://intel.github.io/intel-extension-for-pytorch/#installation compiling ipex for gpu from source.`

Do you plan creating a proper build (ninja, cmake,...) instead of a bash script?
I've used this script:
`wget https://github.com/intel/intel-extension-for-pytorch/raw/v2.1.10%2Bxpu/scripts/compile_bundle.sh`

Things I noted/wished for:
- could detect oneapi locations
- build could be incremental and thus alot faster
- python version is not detected - just python executable is used
- depends on downloading a whole linux distro with "conda" 
- setting jobs to nproc does not yield optimal performance building this.

**Comment by jingxu10** [comment]
The bash script is a launcher script to invoke compilation. The compilation itself uses ninja/cmake.
The bash script is for a generic usage scenario. If you need to customize it, feel free to do so.

**Comment by martin19** [comment]
I want to build without conda, is it possible? Get a compile error in ipex/gpu - can supply more info if that helps. Thanks
