### ISSUE TITLE
Support for Mixtral

### ISSUE THREAD

**Issue by akarX23** [intel/intel-extension-for-pytorch#535]
### Describe the issue

Is there a plan to support https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1 ? We are using this in our chat application and it shows great accuracy.

**Comment by akarX23** [comment]
It's supposed to be on SPR Xeons and Gaudi2.

**Comment by jingxu10** [comment]
`mistralai/Mixtral-8x7B-v0.1` will be supported in the upcoming release.
https://github.com/intel/intel-extension-for-pytorch/tree/v2.3.0%2Bcpu-rc1/examples/cpu/inference/python/llm#21-verified-for-single-instance-mode

**Comment by jingxu10** [comment]
close for long time no actions
