### ISSUE TITLE
How to build this from source

### ISSUE THREAD

**Issue by wswsmao** [intel/intel-extension-for-pytorch#542]
### Describe the issue

Hi, I have read the doc below
https://intel.github.io/intel-extension-for-pytorch/cpu/latest/

is there any way to build intel-extension-for-pytorch from source？

**Comment by kta-intel** [comment]
Hi, yes there is. Please follow the instructions here: https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=cpu&version=v2.2.0%2Bcpu  (under **_source_**)

We provide a `compile_bundle.sh` script to help make the compilation smoother and highly recommend making use of it

**Comment by wswsmao** [comment]
> Hi, yes there is. Please follow the instructions here: https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=cpu&version=v2.2.0%2Bcpu (under **_source_**)
> 
> We provide a `compile_bundle.sh` script to help make the compilation smoother and highly recommend making use of it

OK, Thanks, I will try it in our distro

**Comment by kta-intel** [comment]
@wswsmao Hi, were you successful with building from source?

**Comment by MaksimDanilov** [comment]
@kta-intel Hi! I tried build from that script and always stuck on final linking intel-ext-xpu-*.dll. I wait 3 hours and got no result.

**Comment by jingxu10** [comment]
which device are you using for the compilation?

**Comment by MaksimDanilov** [comment]
> which device are you using for the compilation?

I use Microsoft Surface Pro 9. I successfully compiled all. It took 6-7 hours to run oclock stage.

**Comment by jingxu10** [comment]
Got it.
Yeah, it is expected to take this long time currently to finish the compilation.

**Comment by jingxu10** [comment]
close for long time no activities.
