### ISSUE TITLE
Neither Codeformers nor GFPGAN works in Stable Diffusion

### ISSUE THREAD

**Issue by Pantonia4** [intel/intel-extension-for-pytorch#550]
### Describe the bug

I was wondering why Face Swap Extensions are not working in Stable Diffusion so i played a bit around and figured out that Face Restorations are not working at all with IPEX.
Tried in A1111 and SD.Next and both are not working.
As a result no AI Tools or Extensions that swap faces are working like https://github.com/s0md3v/sd-webui-roop or https://github.com/Gourieff/sd-webui-reactor
I tested with DirectML and it works there.

To reproduce just use Stable Diffusion with IPEX, get any face swap extensions like the 2 linked above and try to use it to swap a face.

Specs
Win 11
Ryzen 5 7600
Intel Arc A770 16 GB Edition
32 GB Ram

### Versions

"'wget' is not recognized as an internal or external command,"

But im on the latest version of A111 Stable Diffusion.

**Comment by YuningQiu** [comment]
Hello, thanks for reporting this issue. Could you please let me know which SD scripts/codes did you try with IPEX? Thanks a lot!

**Comment by Pantonia4** [comment]
> Hello, thanks for reporting this issue. Could you please let me know which SD scripts/codes did you try with IPEX? Thanks a lot!

Happens in any Clean SD Fork. A1111, SD.Next, Forge etc. Only solution I have found is using Codeformers and GFPGAN via CPU instead of GPU.

**Comment by YuningQiu** [comment]
Did you try IPEX implementation following the steps here at this [link](https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.10%2bxpu&os=windows&package=pip)?

**Comment by YuningQiu** [comment]
Hello, is there anything else we can help? Otherwise, could we close this issue? Thanks!

**Comment by Pantonia4** [comment]
> Hello, is there anything else we can help? Otherwise, could we close this issue? Thanks!

No i have just given up on it. It doesn't work, it is what it is.
