### ISSUE TITLE
how to set command to require best performence?

### ISSUE THREAD

**Issue by Storm0921** [intel/intel-extension-for-pytorch#558]
### Describe the issue

![image](https://github.com/intel/intel-extension-for-pytorch/assets/57557769/5bc5cd5f-4433-479d-9bd2-77144afa6f54)

hi, my machine is like this, I want to run benchmark, which command can get the best performance? The order I tried before was this,
`OMP_NUM_THREADS=256 numactl -C 0-255 -m 0,1,2,3 python run.py --benchmark -m  /root/models/baichuan-inc/Baichuan2-13B-Chat --dtype bfloat16 --ipex  --token-latency --max-new-tokens 80 --num-iter 10`.
But it still runs quite slowly. When I check the core, it may not be fully occupied at the same time. I would like to ask how to improve my command

**Comment by ZhaoqiongZ** [comment]
Hi @Storm0921 ,
You can reduce the cores used for 1 instance, and you can run with multi-instances to fully utilize the cores.

**Comment by Storm0921** [comment]
@ZhaoqiongZ My machine has 4 sockets. Is this not supported? I've tried that before
`numactl -C 0-63 -m 0 python run.py --benchmark -m  /root/models/baichuan-inc/Baichuan2-13B-Chat --dtype bfloat16 --ipex  --token-latency --num-iter 1 --prompt 写一段100字的议论文，自定义主题即可 --max-new-tokens 100 --num-iter 10`
But the speed is a bit slow

**Comment by ZhaoqiongZ** [comment]
Yes, the latency may be decrease when you reduce the cores, it is expected. but when you are using multi-instances, the throughput increase.
If you care more about latency in this case, maybe you can try weight only quantization int8 to get better performance.
You can follow the guide here: https://github.com/intel/intel-extension-for-pytorch/tree/main/examples/cpu/inference/python/llm#4115-run-in-weight-only-quantization-int8-with-ipexllm

**Comment by Storm0921** [comment]
@ZhaoqiongZ Thanks! I would like to ask what you mean by multiple-instances? Multiple machines? Is it impossible for someone like me who only has 1 machine and 4 sockets to operate to accelerate?

**Comment by ZhaoqiongZ** [comment]
Hi @Storm0921 ,
multi-instances means you can run 4 inference program at the same time and each instance use different cores and run respectively. IPEX also provide a launch script to run multi-instances in a simpler ways by using ipexrun: https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/performance_tuning/launch_script.html#usage-examples and of course it is possible for you to run multi-instance, you can try 1 socket with 1 instance. which is also called throughput mode with IPEX launch script. https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/performance_tuning/launch_script.html#v-throughput-mode
