### ISSUE TITLE
support for new intel core ultra processor

### ISSUE THREAD

**Issue by HHCorp** [intel/intel-extension-for-pytorch#559]
### Describe the issue

The new released Core Ultra processor include a built-in Arc GPU. I am wondering if this built-in GPU is supported since the document said only Arc A-series GPUs are supported.

**Comment by ZailiWang** [comment]
Hi, built-in GPU is not officially supported by IPEX for now but it is in the scope of the evolutionary roadmap.
If needed, you can try with the interested workloads. Although we can't guarantee, there is a good possibility that the AI workloads can be executed smoothly with iGPU with IPEX.

**Comment by HHCorp** [comment]
> Hi, built-in GPU is not officially supported by IPEX for now but it is in the scope of the evolutionary roadmap. If needed, you can try with the interested workloads. Although we can't guarantee, there is a good possibility that the AI workloads can be executed smoothly with iGPU with IPEX.

thanks for your reply. I saw the XMX engine is removed from these built-in Arc GPU, so I am just curious if it is still possible  to train models with IPEX on Arc iGPU more efficient than that on pure CPU.

**Comment by HHCorp** [comment]
> Hi, built-in GPU is not officially supported by IPEX for now but it is in the scope of the evolutionary roadmap. If needed, you can try with the interested workloads. Although we can't guarantee, there is a good possibility that the AI workloads can be executed smoothly with iGPU with IPEX.

thanks for your reply. I saw the XMX engine is removed from these built-in Arc GPU, so I am just curious if it is still possible  to train models with IPEX on Arc iGPU more efficient than that on pure CPU.

**Comment by ZailiWang** [comment]
Hi, sorry for the late response, but since we don't have official support for built-in GPU, we don't have such benchmark number and the comparison with CPU.
