### ISSUE TITLE
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'

### ISSUE THREAD

**Issue by prashanthrgs** [intel/intel-extension-for-pytorch#560]
### Describe the issue

I am new to using pytorch on a gpu. I have been trying to use the intel_extension_for_pytorch on my windows 11 system with Intel Iris Xe graphics. I have installed the driver from https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html and oneAPI base toolkit for windows.

However, I am getting ModuleNotFoundError while trying to import  intel_extension_for_pytorch.

Can someone pls guide me.

**Comment by ZailiWang** [comment]
Hi, per your description it seems that you just installed the dependencies but not ipex itself. Please run the following command for installing ipex.
```
python -m pip install torch==2.1.0a0 torchvision==0.16.0a0 torchaudio==2.1.0a0 intel-extension-for-pytorch==2.1.10 --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/
```
And before importing ipex in python env, please source the env variable setting scripts:
```
call {DPCPPROOT}\env\vars.bat
call {MKLROOT}\env\vars.bat
```

If you still get errors in sanity test after ipex installation, please double check if oneAPI basekit version is correct (should be 2024.0 for latest ipex version).

**Comment by prashanthrgs** [comment]
Thanks for your inputs. I have done all the above. I get the following error now:

OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\prash\AppData\Roaming\Python\Python311\site-packages\intel_extension_for_pytorch\bin\intel-ext-pt-gpu.dll" or one of its dependencies.

The intel-ext-pt-gpu.dll file is there in the said path.

**Comment by ZailiWang** [comment]
Thanks for the trials. I'll try to reproduce and try to find the root cause.

**Comment by ZailiWang** [comment]
Hi @prashanthrgs I cannot reproduce the issue you met. Would you please check if you are following the guide and try again?
```
conda create  -n   ipex_test  python=3.10

conda activate ipex_test

# conda install pkg-config libuv, please install it in your conda environment, it is needed. 
python -m pip install torch==2.1.0a0 torchvision==0.16.0a0 torchaudio==2.1.0a0 intel-extension-for-pytorch==2.1.10 --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/

(ipex_test) C:\Users\test>"C:\Program Files (x86)\Intel\oneAPI\compiler\2024.0\env\vars.bat"   

(ipex_test) C:\Users\test>"C:\Program Files (x86)\Intel\oneAPI\mkl\2024.0\env\vars.bat"

(ipex_test) C:\Users\test>python -c "import torch; import torchvision; import torchaudio; import intel_extension_for_pytorch as ipex; print(f'torch_version:       {torch._version}'); print(f'torchvision_version: {torchvision.version}'); print(f'torchaudio_version:  {torchaudio.version}'); print(f'ipex_version:        {ipex.version_}');"
C:\Users\test\miniconda3\envs\ipex_test\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
torch_version:       2.1.0a0+cxx11.abi
torchvision_version: 0.16.0a0+cxx11.abi
torchaudio_version:  2.1.0a0+cxx11.abi
ipex_version:        2.1.10+xpu
```

**Comment by ZailiWang** [comment]
would you try install [VS2022 build tools](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2022) and see if the reported error can be mitigated?

**Comment by ZailiWang** [comment]
Also, please use "developer command prompt for vs 2022" or "anaconda prompt", instead of "powershell prompt".

**Comment by prashanthrgs** [comment]
I have tried the above steps using Anaconda Prompt. I get the following error:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\prash\.conda\envs\ipex_test\lib\site-packages\torch\__init__.py", line 139, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\prash\.conda\envs\ipex_test\lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies.

Attached is the entire sequence of steps performed from Anaconda Prompt.
[Anaconda Prompt.txt](https://github.com/intel/intel-extension-for-pytorch/files/14717667/Anaconda.Prompt.txt)

**Comment by ZailiWang** [comment]
Please activate DPCPP compiler & oneMKL env variables in advance
```
call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat"
call "C:\Program Files (x86)\Intel\oneAPI\mkl\latest\env\vars.bat"
```

**Comment by prashanthrgs** [comment]
After activating them:

C:\Users\prash\.conda\envs\ipex_test\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\prash\.conda\envs\ipex_test\lib\site-packages\torch\__init__.py", line 1833, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute '_version'

**Comment by ZailiWang** [comment]
Seems a copy-paste error. For checking versions the format is `{pkg_name}.__version__` (2 underline symbol at the front and back of 'version'). e.g. `torch.__version__`

**Comment by prashanthrgs** [comment]
Thanks @ZailiWang for your assistance. I was able to start using ipex.

**Comment by MikyLanfra** [comment]
Hello, it seems I am having the same problems as the previous user with the usage of the ipex library (I also have Intel iRISXe Graphics on Windows 11) . 

Other than a few basic changes (such as the change from 2024.0 to 2024.1 in the paths passed to the prompt), I get the same errors:
- OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\test.conda\envs\ipex_test\lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies.
- OSError: [WinError 127] The specified module could not be found. Error loading "C:\Users\test.conda\envs\ipex_test\lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies.

I have installed VS2022, Intel® oneAPI DPC++ Compiler and Intel® oneAPI Base Toolkit as asked in the installation page and haven't had any warnings or errors in those installations, I have restarted the PC as suggested by the installer and now I am trying to install pytorch, pytorchvision and ipex, but something is not working.

To make it easier for you to help me I have also attached a file txt containing all my prompts.
[Ipex_Problems_1.txt](https://github.com/user-attachments/files/15605184/Ipex_Problems_1.txt)
[Ipex_Problems_2.txt](https://github.com/user-attachments/files/15605185/Ipex_Problems_2.txt)
Thank you in advance for the support.
