### ISSUE TITLE
Please update Get Started examples.

### ISSUE THREAD

**Issue by QiXuanWang** [intel/intel-extension-for-pytorch#564]
### Describe the issue

Please try to put some simple yet working examples in pages like "https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/getting_started.html"
None of them works out of box, even the last one that looks so complete. It still contains a strange "MODEL_ID" variable defined no where. Might just add some comment like "bert-base-uncased" so we could copy-paste and make a quick run. 
So as GPU versions.

**Comment by ZailiWang** [comment]
Hi @QiXuanWang thanks for the advice. In `Get Started` page we only introduced some generalized usage by incomplete code snippets. We have the examples page that you could make the copy-paste quick run [here](https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/examples.html). Also in the subfolders in [github examples page](https://github.com/intel/intel-extension-for-pytorch/tree/main/examples/cpu) you can find step-to-step example reproduction guidance.
