### ISSUE TITLE
Using XPU training actually increases the training time and sharply reduces the accuracy.

### ISSUE THREAD

**Issue by SoldierWz** [intel/intel-extension-for-pytorch#565]
### Describe the issue

When I wanted to try using a graphics card to train my classification model I made changes to the following code
device = 'xpu'
X_tensor = torch.tensor(X_processed, dtype=torch.float).to(device)
y_tensor = torch.tensor(y, dtype=torch.long).to(device)
model = FCN(X_train.shape[1], len(np.unique(y))).to(device)
model, optimizer = ipex.optimize(model, optimizer=optimizer)
features, labels = features.to(device), labels.to(device) 
X_test = X_test.to(device)
What I am doing is a prediction and classification task on a small data set. The sample size is only a few hundred.I know this task is not suitable for running on GPU but I just tried it. I am using A770 graphics card and the processor is 12400. I have successfully installed all the necessary according to the tutorial.
My training time using CPU was 24 seconds with an accuracy of 0.94
But when I sent all the data to the XPU, the same training took 1 minute and 40 seconds and the accuracy was only 0.34
This is not an important issue, but I still want to report this unusual phenomenon.

**Comment by wangkl2** [comment]
Hi @SoldierWz, thanks for reporting this issue. Could you please help provide the env info via the following commands:
```
wget https://raw.githubusercontent.com/intel/intel-extension-for-pytorch/master/scripts/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Besides, please also provide us the minimum code reproducer for this issue training on A770 as well as the dataset? Thanks.

**Comment by SoldierWz** [comment]
> If possible, please also provide the torch profiler info so that we can know the breakdown and what ops take most time.

I want to provide information, but a new problem occurred when I was running it today. When I started the computer today, I found that the oneAPI suite seemed to be updated. After I updated it, I ran my code and the following problem occurred.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[4], [line 8](vscode-notebook-cell:?execution_count=4&line=8)
      [6](vscode-notebook-cell:?execution_count=4&line=6) import modin.pandas as pd
      [7](vscode-notebook-cell:?execution_count=4&line=7) import numpy as np
----> [8](vscode-notebook-cell:?execution_count=4&line=8) import torch
      [9](vscode-notebook-cell:?execution_count=4&line=9) import intel_extension_for_pytorch as ipex
     [10](vscode-notebook-cell:?execution_count=4&line=10) import torch.nn as nn

File [~/mambaforge/envs/pytorch-arc/lib/python3.11/site-packages/torch/__init__.py:235](https://file+.vscode-resource.vscode-cdn.net/home/wangzhen/Documents/porcelains/code/~/mambaforge/envs/pytorch-arc/lib/python3.11/site-packages/torch/__init__.py:235)
    [233](https://file+.vscode-resource.vscode-cdn.net/home/wangzhen/Documents/porcelains/code/~/mambaforge/envs/pytorch-arc/lib/python3.11/site-packages/torch/__init__.py:233)     if USE_GLOBAL_DEPS:
    [234](https://file+.vscode-resource.vscode-cdn.net/home/wangzhen/Documents/porcelains/code/~/mambaforge/envs/pytorch-arc/lib/python3.11/site-packages/torch/__init__.py:234)         _load_global_deps()
--> [235](https://file+.vscode-resource.vscode-cdn.net/home/wangzhen/Documents/porcelains/code/~/mambaforge/envs/pytorch-arc/lib/python3.11/site-packages/torch/__init__.py:235)     from torch._C import *  # noqa: F403
    [237](https://file+.vscode-resource.vscode-cdn.net/home/wangzhen/Documents/porcelains/code/~/mambaforge/envs/pytorch-arc/lib/python3.11/site-packages/torch/__init__.py:237) # Appease the type checker; ordinarily this binding is inserted by the
    [238](https://file+.vscode-resource.vscode-cdn.net/home/wangzhen/Documents/porcelains/code/~/mambaforge/envs/pytorch-arc/lib/python3.11/site-packages/torch/__init__.py:238) # torch._C module initialization code in C
    [239](https://file+.vscode-resource.vscode-cdn.net/home/wangzhen/Documents/porcelains/code/~/mambaforge/envs/pytorch-arc/lib/python3.11/site-packages/torch/__init__.py:239) if TYPE_CHECKING:

ImportError: [/home/wangzhen/mambaforge/envs/pytorch-arc/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so](https://file+.vscode-resource.vscode-cdn.net/home/wangzhen/mambaforge/envs/pytorch-arc/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so): undefined symbol: iJIT_NotifyEvent

**Comment by wangkl2** [comment]
@SoldierWz XPU seems not be detected by IPEX in your environment. IPEX 2.1.10+xpu works with oneAPI 2024.0, please help downgrade the dpcpp and mkl version via `sudo apt install -y intel-oneapi-dpcpp-cpp-2024.0 intel-oneapi-mkl-devel=2024.0.0-49656` or the online/offline installer in https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=linux. Then please collect the sys info and try the workloads again.

**Comment by SoldierWz** [comment]
> @SoldierWz XPU seems not be detected by IPEX in your environment. IPEX 2.1.10+xpu works with oneAPI 2024.0, please help downgrade the dpcpp and mkl version via `sudo apt install -y intel-oneapi-dpcpp-cpp-2024.0 intel-oneapi-mkl-devel=2024.0.0-49656` or the online/offline installer in https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=linux. Then please collect the sys info and try the workloads again.

No, the GPU could be detected before, and I successfully ran the code on the XPU. I think the unavailability of the GPU this time was caused by the oneAPI update this morning. I'll try downgrading, thanks.

**Comment by Shr1ftyy** [comment]
Hi @SoldierWz - did downgrading work? I literally just got my arc a770 today and spun it up on Ubuntu 23 and faced the same issue you did. Thanks beforehand.

**Comment by wangkl2** [comment]
@SoldierWz @Shr1ftyy 
For the undefined symbol issue caused by the mismatch between IPEX 2.1.10+xpu and oneAPI 2024.1, we recently released IPEX 2.1.20+xpu, which is compatible with oneAPI base toolkit 2024.1, please refer to https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.20%2bxpu&os=linux%2fwsl2&package=pip.

**Comment by wangkl2** [comment]
@SoldierWz BTW, the dataset you shared seems not successfully uploaded. Please help check.

**Comment by wangkl2** [comment]
There is no response on this issue for over 1 month. Close the issue now. If you still have issues, feel free to reopen it. Thanks.
