### ISSUE TITLE
compile_bundle.sh is hard to use

### ISSUE THREAD

**Issue by msaroufim** [intel/intel-extension-for-pytorch#573]
### Describe the issue

I'm trying to instal ipex from source https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=cpu&version=main&os=linux%2fwsl2&package=source to make a contribution but keep running into many issues which stem from this file `wget https://github.com/intel/intel-extension-for-pytorch/raw/main/scripts/compile_bundle.sh`

1. This file will on my machine download pytorch 2.3 even though a makefile later fails because it needs 2.4. I had to myself install pytorch from nightlies and then disable installation of torch, vision and audio
2. There is no line that says `python setup.py develop` anywhere which for python only changes is frustrating because building the project end to end takes a while
3. Even after succesfully installing ipex once I try to import it, I get this error `ImportError: /opt/conda/envs/ipex/lib/libmkl_intel_thread.so.2: undefined symbol: __kmpc_reduce_nowait` and am now stuck

**Comment by sanchitintel** [comment]
Hi @jingxu10, this specific error occurred because of the system already having another libmkl in its `LD_LIBRARY_PATH`.

@msaroufim, I resolved this specific issue but could you please run the following command on your system to resolve the libstdc
++ linking error?
https://github.com/intel/intel-extension-for-pytorch/blob/main/scripts/compile_bundle.sh#L256C1-L256C83

**Comment by zhangcong2019** [comment]
`undefined symbol` from my environment `ImportError: /opt/intel/oneapi/mkl/2024.0/lib/libmkl_sycl_lapack.so.4: undefined symbol: mkl_lapack_dsytrd_sb2st_block_rfg`, while install from source with `compile_bundle.sh`
Tried `export LD_PRELOAD=$(bash ./intel-extension-for-pytorch/tools/get_libstdcpp_lib.sh)`, not work.

![image](https://github.com/intel/intel-extension-for-pytorch/assets/47588442/0cc79a57-2b37-46f0-8228-f7671c423853)

**Comment by sanchitintel** [comment]
@zhangcong2019, remove `/opt/intel/oneapi/` from your `LD_LIBRARY_PATH`

**Comment by zhangcong2019** [comment]
> @zhangcong2019, remove `/opt/intel/oneapi/` from your `LD_LIBRARY_PATH`

Thanks a lot, will try

**Comment by sanchitintel** [comment]
https://github.com/intel/intel-extension-for-pytorch/blob/main/dependency_version.yml has been updated, so `compile_bundle.sh` has now been fixed. Thanks!

**Comment by zhangcong2019** [comment]
> https://github.com/intel/intel-extension-for-pytorch/blob/main/dependency_version.yml has been updated, so `compile_bundle.sh` has now been fixed. Thanks!

Thanks a lot!
