### ISSUE TITLE
OSError: [WinError 1920] The file cannot be accessed by the system. Error loading "C:\Users\techn\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by Bhargav230m** [intel/intel-extension-for-pytorch#585]
I get this error

```bash
C:\Users\techn>pip install intel-extension-for-pytorch
ERROR: Could not find a version that satisfies the requirement intel-extension-for-pytorch (from versions: none)
ERROR: No matching distribution found for intel-extension-for-pytorch
```
Please help

**Comment by Bhargav230m** [comment]
I fixed it, but now i am getting the error `OSError: [WinError 1920] The file cannot be accessed by the system. Error loading "C:\Users\techn\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies.`

**Comment by Bhargav230m** [comment]
Anyone please help?

**Comment by jingxu10** [comment]
could you check if that file exists there in the folder?

**Comment by ZailiWang** [comment]
Hi, did you activate the oneAPI components in advance?
```
call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat"
call "C:\Program Files (x86)\Intel\oneAPI\mkl\latest\env\vars.bat"
```

**Comment by Bhargav230m** [comment]
I just used another fork of this which is https://github.com/Nuullll/intel-extension-for-pytorch/releases.

It helped me fix the issue, but i do sometimes run into API issues but its ok for now

**Comment by Bhargav230m** [comment]
@ZailiWang, So i uninstalled the fork as it gave me some errors, I reinstalled the ipex from official site. But i am still getting that error..

Using `call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat"` says thats this path doesn't exist as well as the second command you sent

**Comment by ZDP-Q** [comment]
these commands work!
call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat"
call "C:\Program Files (x86)\Intel\oneAPI\mkl\latest\env\vars.bat"
but only once......
why don't you set them permanently?

**Comment by ZailiWang** [comment]
Hi @Bhargav230m do you have oneAPI basekit installed in advance? If not, please download and install it first.
https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html

**Comment by ZailiWang** [comment]
@ZDP-Q we cannot presume every user likes to activate oneAPI env permanently... Feel free to enable this by adding these commands to startup task.

**Comment by ZDP-Q** [comment]
Permanent activation of the environment and activation on each use can be made an option to make it easier for those who want to activate permanently (like me) to use IPEX?

**Comment by Bhargav230m** [comment]
@ZailiWang I installed but i get this problem

```bash
C:\Users\techn>call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat"
:: WARNING: Visual Studio was not found in the standard installation location:
   "C:\Program Files\Microsoft Visual Studio\<Year>\<Edition>" or
   "C:\Program Files (x86)\Microsoft Visual Studio\<Year>\<Edition>"
   Set the VS2019INSTALLDIR or VS2022INSTALLDIR
   environment variable to point to your install location and try again.

C:\Users\techn>call "C:\Program Files (x86)\Intel\oneAPI\mkl\latest\env\vars.bat"

C:\Users\techn>
```

I have installed VS2022 community but it still shows this warning, it is in Program Files X86

**Comment by Bhargav230m** [comment]
I also get this error `OSError: [WinError 1920] The file cannot be accessed by the system. Error loading "C:\Users\techn\AppData\Local\Programs\Python\Python311\Lib\site-packages\intel_extension_for_pytorch\bin\intel-ext-pt-gpu.dll" or one of its dependencies.` now even after calling the thing you said

**Comment by ZailiWang** [comment]
> @ZailiWang I installed but i get this problem
> 
> ```shell
> C:\Users\techn>call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat"
> :: WARNING: Visual Studio was not found in the standard installation location:
>    "C:\Program Files\Microsoft Visual Studio\<Year>\<Edition>" or
>    "C:\Program Files (x86)\Microsoft Visual Studio\<Year>\<Edition>"
>    Set the VS2019INSTALLDIR or VS2022INSTALLDIR
>    environment variable to point to your install location and try again.
> 
> C:\Users\techn>call "C:\Program Files (x86)\Intel\oneAPI\mkl\latest\env\vars.bat"
> 
> C:\Users\techn>
> ```
> 
> I have installed VS2022 community but it still shows this warning, it is in Program Files X86

Would you check for the concrete path that VS2022 is installed?

**Comment by Bhargav230m** [comment]
> > @ZailiWang I installed but i get this problem
> > ```shell
> > C:\Users\techn>call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat"
> > :: WARNING: Visual Studio was not found in the standard installation location:
> >    "C:\Program Files\Microsoft Visual Studio\<Year>\<Edition>" or
> >    "C:\Program Files (x86)\Microsoft Visual Studio\<Year>\<Edition>"
> >    Set the VS2019INSTALLDIR or VS2022INSTALLDIR
> >    environment variable to point to your install location and try again.
> > 
> > C:\Users\techn>call "C:\Program Files (x86)\Intel\oneAPI\mkl\latest\env\vars.bat"
> > 
> > C:\Users\techn>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have installed VS2022 community but it still shows this warning, it is in Program Files X86
> 
> Would you check for the concrete path that VS2022 is installed?


![image](https://github.com/intel/intel-extension-for-pytorch/assets/100185728/7df5937d-bc4c-4d4e-8c79-84d76ea84cc6)

**Comment by ZailiWang** [comment]
Hi, I have asked for Intel internal support to look into this issue, will come back if any progress. Thanks for your patience.

**Comment by Bhargav230m** [comment]
Okay!

**Comment by shirne** [comment]
![image](https://github.com/intel/intel-extension-for-pytorch/assets/2263157/9e800ae7-2080-498c-a693-4b9d54220d8d)
why there's no file  vcvarsall.bat ?

**Comment by shirne** [comment]
> ![image](https://private-user-images.githubusercontent.com/2263157/324217207-9e800ae7-2080-498c-a693-4b9d54220d8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NjIxMTUsIm5iZiI6MTcxMzY2MTgxNSwicGF0aCI6Ii8yMjYzMTU3LzMyNDIxNzIwNy05ZTgwMGFlNy0yMDgwLTQ5OGMtYTY5My00YjlkNTQyMjBkOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMDExMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTY2ZDg4YzFhOTE1MjI4ZjZjM2M4OTViMzFjYjc5ZDM3YWYxYjk5NjliZTQxNDQ1ZWUzZmVkYWI2NzRiZjBlZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4G6zBcU15Zk7mvYRmXNI4RqPF2BVdS1d3OJysu1_Kfo) why there's no file vcvarsall.bat ?

@Bhargav230m install `Desktop C++ build Tools` component will solve this problem
![image](https://github.com/intel/intel-extension-for-pytorch/assets/2263157/34afb38e-b083-4f78-b77f-528709045153)

**Comment by Bhargav230m** [comment]
@shirne, thanks for your help, i made it work

```bash
(base) C:\Users\techn>activate nlp

(nlp) C:\Users\techn>set "VS2019INSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"

(nlp) C:\Users\techn>call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat"

(nlp) C:\Users\techn>call "C:\Program Files (x86)\Intel\oneAPI\mkl\latest\env\vars.bat"

(nlp) C:\Users\techn>python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.__version__); print(ipex.__version__); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"
C:\Users\techn\miniconda3\envs\nlp\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\techn\miniconda3\envs\nlp\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2.1.0.post0+cxx11.abi
2.1.20+xpu
[0]: _DeviceProperties(name='Intel(R) Iris(R) Xe Graphics', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=0, total_memory=10979MB, max_compute_units=80, gpu_eu_count=80)

(nlp) C:\Users\techn>cd onedrive

(nlp) C:\Users\techn\OneDrive>cd desktop

(nlp) C:\Users\techn\OneDrive\Desktop>cd idk

(nlp) C:\Users\techn\OneDrive\Desktop\idk>python src/main.py
C:\Users\techn\miniconda3\envs\nlp\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\techn\miniconda3\envs\nlp\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
TRAINING WITH FOLLOWING HYPERPARAMETERS:
EMBEDDING_DIM: 250
NUM_FILTERS: 250
FILTER_SIZES: [3, 4, 5]
DROPOUT: 0.3
BATCH_SIZE: 128
NUM_EPOCHS: 100
WEIGHT_DECAY: 0.001
LEARNING_RATE: 0.0001
Saving hyperparameters
Epoch 1/100:   0%|                                                                         | 0/2052 [00:00<?, ?batch/s]
```

But it looks like it hasn't yet started training since it hasn't shown ?batch/s

**Comment by Bhargav230m** [comment]
Yup, it failed with the error `Native API failed. Native API returns: -999 (Unknown PI error) -999 (Unknown PI error)`

**Comment by ZailiWang** [comment]
Would you try if the IPEX examples can run in your env? https://github.com/intel/intel-extension-for-pytorch/tree/v2.1.20%2Bxpu/examples/gpu/training
Also, would you provide your `main.py` script so I can try reproduce the error you met and diagnose.

**Comment by Bhargav230m** [comment]
@ZailiWang. Heres the code.

main.py
```python
import intel_extension_for_pytorch as ipex
from ArrowTextClassifier import Model

classificationModel = Model("classification")
classificationModel.train_model(dataset="dataset.parquet", EMBEDDING_DIM=100, NUM_FILTERS=100, FILTER_SIZES=[3, 4, 5], DROPOUT=0.3, BATCH_SIZE=64, NUM_EPOCHS=100, WEIGHT_DECAY=0.001, LEARNING_RATE=0.0001, device="xpu")
```

ArrowTextClassifier.main: https://sourceb.in/OCfmFq5r1E
ArrowTextClassifier.train: https://sourceb.in/6c9t70R80W

This package is written by me, and also i am very new to machine learning so don't judge my code

Also the examples you gave me to test also doesn't seem to be working. It has been frozen after downloading the dataset
```bash
(nlp) C:\Users\techn\OneDrive\Desktop>python test.txt
C:\Users\techn\miniconda3\envs\nlp\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\techn\miniconda3\envs\nlp\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to datasets/cifar10/cifar-10-python.tar.gz
100%|███████████████████████████████████████████████████████████████| 170498071/170498071 [00:21<00:00, 7860368.26it/s]
Extracting datasets/cifar10/cifar-10-python.tar.gz to datasets/cifar10/
```

**Comment by ZailiWang** [comment]
Since the example code has been extensively validated among the users, I assume there is still some env issue. Would you try re-install oneAPI basekit?

**Comment by Bhargav230m** [comment]
I did reinstall the oneAPI basekit @ZailiWang. 

heres the link i downloaded it from: https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=window&distributions=online

**Comment by Bhargav230m** [comment]
it still doesn't work

**Comment by ZailiWang** [comment]
Also, please run this script https://github.com/intel/intel-extension-for-pytorch/blob/main/scripts/collect_env.py and provide the output.

**Comment by qiacheng** [comment]
use anaconda prompt, and do the following:


```bash

conda create -n ipex python=3.10

conda install libuv

pip install torch==2.1.0.post0 torchvision==0.16.0.post0 torchaudio==2.1.0.post0 intel-extension-for-pytorch==2.1.20 --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/

pip install mkl mkl-dpcpp

````

then run scripts

**Comment by Bhargav230m** [comment]
okay

**Comment by Bhargav230m** [comment]
@ZailiWang 

Heres my output
```bash
PyTorch version: N/A
PyTorch CXX11 ABI: N/A
IPEX version: N/A
IPEX commit: N/A
Build type: N/A

OS: Microsoft Windows 11 Home Single Language
GCC version: N/A
Clang version: N/A
IGC version: N/A
CMake version: N/A
Libc version: N/A

Python version: 3.10.14 | packaged by Anaconda, Inc. | (main, Mar 21 2024, 16:20:14) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is XPU available: N/A
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration:
N/A
Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture=9
CurrentClockSpeed=2419
DeviceID=CPU0
Family=205
L2CacheSize=5120
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2419
Name=11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.1.20+xpu
[pip3] numpy==1.26.4
[pip3] torch==2.1.0.post0+cxx11.abi
[pip3] torchaudio==2.1.0.post0+cxx11.abi
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.16.0.post0+cxx11.abi
[conda] intel-extension-for-pytorch 2.1.20+xpu               pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.1.0.post0+cxx11.abi          pypi_0    pypi
[conda] torchaudio                2.1.0.post0+cxx11.abi          pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.16.0.post0+cxx11.abi          pypi_0    pypi
```

**Comment by Bhargav230m** [comment]
oh also i have changed my os to windows 11

**Comment by Bhargav230m** [comment]
@ZailiWang, i think the problem is when we are trying to access the thing we moved to the xpu, for example the script you gave me

```python
import torch
import intel_extension_for_pytorch
a = torch.tensor([0.1])
a = a.to("xpu")
```

This works, but when i try to print(access) it freezes

**Comment by ZailiWang** [comment]
@Bhargav230m you mean after adding 

```
print(a)
```
at the end of the test script, it hangs up? would you set IPEX_VERBOSE=1 and run the script again for the verbose logs?

**Comment by yinghu5** [comment]
Hi @Bhargav230m , 

do you have some kind of Intel GPU cards with the machine, like [Intel® Arc® Graphics family (Codename Alchemist)](https://www.intel.com/content/www/us/en/products/details/discrete-gpus/arc.html) ? 

from the output of env_chk.py: 
 Is XPU available: N/A
maybe the system hasn't recognized the XPU. Could you please check if the GPU is working?  

Please check from start menu => all program => open the oneAPI prompt windows  
try the command sycl-ls.exe and see if it found the GPU or not? 
(if no, maybe need to reinstall driver:  https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)

![image](https://github.com/intel/intel-extension-for-pytorch/assets/43240216/34f5da9f-9581-4380-8b57-1bab27c46e10)
Thanks
Ying

**Comment by Bhargav230m** [comment]
@yinghu5 
```bash
C:\Program Files (x86)\Intel\oneAPI>sycl-ls.exe
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device OpenCL 1.2  [2024.17.3.0.08_160000]
[opencl:cpu:1] Intel(R) OpenCL, 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz OpenCL 3.0 (Build 0) [2024.17.3.0.08_160000]
[opencl:gpu:2] Intel(R) OpenCL Graphics, Intel(R) Iris(R) Xe Graphics OpenCL 3.0 NEO  [31.0.101.4575]
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Iris(R) Xe Graphics 1.3 [1.3.26561]
```

**Comment by Bhargav230m** [comment]
@ZailiWang, Any type of operation or accessing the data from xpu freezes... and i am pretty sure after a long time it would throw an error

**Comment by Bhargav230m** [comment]
Test 3, and the test at https://github.com/intel/intel-extension-for-pytorch/tree/v2.1.20%2Bxpu/examples/gpu/training didn't work. This is so confusing...

**Comment by ZailiWang** [comment]
Hi @Bhargav230m from your `sycl-ls.exe` result, seems that you are not having an Arc graphic card in your machine, or it is not properly detected in the OS.
So the test workloads are executed on the integrated GPU `Intel(R) Iris(R) Xe Graphics`, which *has not been officially supported* by IPEX. We do not guarantee a smooth running of the workloads on iGPU. The hang-up are possibly due that some backward operators are not supported yet.

**Comment by Bhargav230m** [comment]
Okay.. but will it be ever be supported?

**Comment by ZailiWang** [comment]
Yes, it is in the scope of the evolutionary roadmap.

**Comment by Bhargav230m** [comment]
Thanks for the help.

**Comment by CarlGao4** [comment]
Maybe you can try [CarlGao4/ipex-wheel](https://github.com/CarlGao4/ipex-wheel/releases)
I've even packed AOT for all devices along with it
