### ISSUE TITLE
failed to run on ultra 5 with Arc(TM) graphics (16GB VRAM)

### ISSUE THREAD

**Issue by qslia** [intel/intel-extension-for-pytorch#604]
### Describe the issue

do you support this graphic card?

**Comment by ZhaoqiongZ** [comment]
Hi @qslia , thanks for reporting this issue.
Could you please give the exact device info for Arc using the following command:
`
lspci -nn |grep -i display
`
And could you also share the exact error you met?

**Comment by qslia** [comment]
python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.__version__); print(ipex.__version__); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"
D:\anaconda3\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'D:\anaconda3\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda3\Lib\site-packages\intel_extension_for_pytorch\__init__.py", line 91, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "D:\anaconda3\Lib\site-packages\intel_extension_for_pytorch\bin\intel-ext-pt-gpu.dll" or one of its dependencies.

**Comment by qslia** [comment]
Ultralytics YOLOv8.2.8 🚀 Python-3.11.7 torch-2.1.0.post2+cxx11.abi CPU (Intel Core(TM) Ultra 5 125H)
Setup complete ✅ (18 CPUs, 31.6 GB RAM, 117.3/195.3 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.11.7
Install             pip
RAM                 31.65 GB
CPU                 Intel Core(TM) Ultra 5 125H
CUDA                None

**Comment by ZhaoqiongZ** [comment]
Hi @qslia , this error seems to be something wrong during environment setup. 
Please check step by step if you are installing the correct driver and basekit by following https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.30%2bxpu&os=windows&package=pip

1. Install driver in Windows system with link https://www.intel.com/content/www/us/en/download/785597/819065/intel-arc-iris-xe-graphics-windows.html
verify the installation in Device Manager and with Intel Arc Graphics
![image](https://github.com/intel/intel-extension-for-pytorch/assets/106125927/8796317c-5300-4875-a6e7-d5f5891a1888)

2. Install Microsoft Visual C++ Redistributable and oneAPI Basekit by following the guide above


3. Finally install the required packages pkgconfig, libuv and torch ipex etc.

4. remember to activate compiler and mkl by 
call {DPCPPROOT}\env\vars.bat and 
call {MKLROOT}\env\vars.bat  
then you can run python -c "import torch; import intel_extension_for_pytorch; print(torch.xpu.device_count()); print(torch.xpu.get_device_properties(0));" to check the installation.

**Comment by CarlGao4** [comment]
Maybe you can try [CarlGao4/ipex-wheel](https://github.com/CarlGao4/ipex-wheel/releases)
I've even packed AOT for all devices along with it

**Comment by ZhaoqiongZ** [comment]
The issue is closed due to inactivity. Feel free to reopen it if your problem has not been resolved
