### ISSUE TITLE
compatability issues with oobabooga

### ISSUE THREAD

**Issue by alioop222** [intel/intel-extension-for-pytorch#605]
### Describe the issue

My machine has a requirement for torch==2.0.1a0 
It cant find a matching distribution in developer.intel.com. Do you recognise a version with that weird number because i havent seen any versions of anything with alphanumeric codes.

**Comment by ZhaoqiongZ** [comment]
Hi @alioop222 , torch==2.0.1a0 is a version based pytorch v2.0 and has a patch to support Pytorch on Intel GPU.
Could you share where did you find the installation guide with developer.intel.com? 

Please try the installation commands in the [installation guide](https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu) to install it:
`
python -m pip install torch==2.0.1a0 torchvision==0.15.2a0 intel-extension-for-pytorch==2.0.120+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl-aitools/
`
But I would recommend you to use the latest version v2.1.20 with commands:
`
python -m pip install torch==2.1.0.post0 torchvision==0.16.0.post0 torchaudio==2.1.0.post0 intel-extension-for-pytorch==2.1.20+xpu oneccl_bind_pt==2.1.200+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/
`

**Comment by alioop222** [comment]
Hi Zhaoqiong
Thanks ill try that. The link came in my terminal output when i was trying to install oobabooga using pinokio. Heres the whole snippet.
I know the .sh command for my machine because i was running oobabooga before. Theres a conflict here though. Heres the output from my terminal:Looking in links: https://developer.intel.com/ipex-whl-stable-xpu
ERROR: Could not find a version that satisfies the requirement torch==2.0.1a0 (from versions: 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==2.0.1a0
Command '. "/Users/alimac/pinokio/api/oobabooga.pinokio.git/text-generation-webui/installer_files/conda/etc/profile.d/conda.sh" && conda activate "/Users/alimac/pinokio/api/oobabooga.pinokio.git/text-generation-webui/installer_files/env" && conda install -y -k ninja git && python -m pip install torch==2.0.1a0 torchvision==0.15.2a0 intel_extension_for_pytorch==2.0.110+xpu -f https://developer.intel.com/ipex-whl-stable-xpu && python -m pip install py-cpuinfo==9.0.0' failed with exit status code '1'.

Exiting now.
Try running the start/update script again.
(base) alimac@Alistairs-Mac-mini text-generation-webui %

The title of the module shows it as running but when i open the UI its just a blank page with an error. Hope this will sort it out. Cheers.

**Comment by ZhaoqiongZ** [comment]
Hi @alioop222 , could you try to open link https://pytorch-extension.intel.com/release-whl/stable/xpu/cn/  and also https://pytorch-extension.intel.com/release-whl-aitools/  directly in the browser to see if you can access to the server which whls locates.

**Comment by alioop222** [comment]
@ZhaoqiongZ I said before, im using pinokio, the one click installer to install oobabooga, and because it didn't load properly i have been trying to complete the installation in my terminal, so its got to be either pinokio or oobabooga or my own codebase that has generated that terminal output which included that link. Here's the full page address resulting from that link which looks like amazon web services if i’m not mistaken, but that’s all i got on that.
http://ec2-52-27-27-201.us-west-2.compute.amazonaws.com/ipex-release.php?device=xpu&repo=us&release=stable

**Comment by ZhaoqiongZ** [comment]
Hi @alioop222 , Oh, I searched pinokio and understand your point.
But this is not a pip or conda issue.
Intel extension for pytorch is not yet supported on MacOS, so pip install can not find a wheel which match the MacOS.

**Comment by ZhaoqiongZ** [comment]
Hi @alioop222 , as I said Intel extension for pytorch is not yet supported on MacOS, so pip install can not find a wheel which match the MacOS. and it's not a issue for intel extension for pytorch, so I will close the ticket.
