### ISSUE TITLE
Error can't import the library: Key already registered with the same priority

### ISSUE THREAD

**Issue by CarlGao4** [intel/intel-extension-for-pytorch#611]
### Describe the bug

After I built the library 2.1.20+xpu from source and tried to import it:

```
In [1]: import torch

In [2]: import intel_extension_for_pytorch as ipex
[W OperatorEntry.cpp:160] Warning: Warning only once for all operators,  other operators may also be overrided.
  Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: torch_ipex::batch_norm(Tensor _0, Tensor _1, Tensor? _2, Tensor _3, Tensor _4, bool _5, float _6, float _7, bool _8) -> Tensor _0
    registered at E:/.../intel-extension-for-pytorch/csrc/gpu/jit/jit_nodes.cpp:80
  dispatch key: (catch all)
  previous kernel: registered at E:/.../intel-extension-for-pytorch/csrc/gpu/jit/jit_nodes.cpp:80
       new kernel: registered at E:/.../intel-extension-for-pytorch/csrc/gpu/jit/jit_nodes.cpp:80 (function operator ())
Key already registered with the same priority: [key type printing not supported]
```

Then the program crashes with return code 1

### Versions

Built from source, version 2.1.20+xpu, Windows 11

**Comment by ZailiWang** [comment]
Hi, would you try if installing IPEX with prebuilt wheel works for your env? This is for preliminary diagnose if it's due an env issue or compilation issue.
And if the prebuilt wheel works, would you share the steps you used for source code compilation?

**Comment by CarlGao4** [comment]
I found the error. I built the library with oneAPI 2024.1 downloaded from official website, but installed 2024.0 runtime using `pip install mkl mkl-dpcpp`
