### ISSUE TITLE
How to use ipex.llm.optimize

### ISSUE THREAD

**Issue by Alok-Ranjan23** [intel/intel-extension-for-pytorch#612]
### Describe the issue

should we use torch.compile(model,backend='ipex') after ipex.llm.optimize(model, dtype=torch.float32, inplace=True) ?
Does ipex.llm.optimize also include torch.compile functionality?

**Comment by ZailiWang** [comment]
`torch.compile` should be used for graph compilation after `ipex.llm.optimize`. Please refer to [IPEX LLM example](https://github.com/intel/intel-extension-for-pytorch/blob/main/examples/cpu/inference/python/llm/single_instance/run_generation.py), in which `--ipex` and `--torch-compile` are used to enable the functionalities respectively.
