### ISSUE TITLE
NotImplementedError: The following operation failed in the TorchScript interpreter. Traceback of TorchScript (most recent call last): RuntimeError: Could not run 'torch_ipex::mul_add' with arguments from the 'CPU' backend.

### ISSUE THREAD

**Issue by wangdq1989** [intel/intel-extension-for-pytorch#623]
### Describe the issue

Langchain-chatchat run with ipex-llm,  I configured the widnows environment as follows [https://christianjmills.com/posts/intel-pytorch-extension-tutorial/native-windows/](url)，it works.  However, It suddenly doesn't work today.

I get exception 

`C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\ipex_llm\transformers\models\chatglm2.py:405: UserWarning: IPEX XPU dedicated fusion passes are enabled in ScriptGraph non profiling execution mode. Please enable profiling execution mode to retrieve device guard.
 (Triggered internally at C:/Users/arc/ruijie/2.1_RC3/python311/frameworks.ai.pytorch.ipex-gpu/csrc/gpu/jit/fusion_pass.cpp:837.)
  query_layer = apply_rotary_pos_emb_chatglm(query_layer, rotary_pos_emb)
Exception in thread Thread-3 (model_generate):
Traceback (most recent call last):
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\ipex_llm\serving\fastchat\ipex_llm_worker.py", line 332, in model_generate
    self.model.generate(input_ids, **generated_kwargs)
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\ipex_llm\transformers\lookup.py", line 87, in generate
    return original_generate(self,
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\ipex_llm\transformers\speculative.py", line 109, in generate
    return original_generate(self,
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\transformers\generation\utils.py", line 1479, in generate
    return self.greedy_search(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\transformers\generation\utils.py", line 2340, in greedy_search
    outputs = self(
              ^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.cache\huggingface\modules\transformers_modules\chatglm3-6b\modeling_chatglm.py", line 941, in forward
    transformer_outputs = self.transformer(
                          ^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\ipex_llm\transformers\models\chatglm2.py", line 180, in chatglm2_model_forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
                                                                      ^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.cache\huggingface\modules\transformers_modules\chatglm3-6b\modeling_chatglm.py", line 641, in forward
    layer_ret = layer(
                ^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.cache\huggingface\modules\transformers_modules\chatglm3-6b\modeling_chatglm.py", line 544, in forward
    attention_output, kv_cache = self.self_attention(
                                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\ipex_llm\transformers\models\chatglm2.py", line 204, in chatglm2_attention_forward
    return forward_function(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\conte\.conda\envs\ipex-llm\Lib\site-packages\ipex_llm\transformers\models\chatglm2.py", line 405, in chatglm2_attention_forward_8eb45c
    query_layer = apply_rotary_pos_emb_chatglm(query_layer, rotary_pos_emb)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: Could not run 'torch_ipex::mul_add' with arguments from the 'CPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torch_ipex::mul_add' is only available for these backends: [XPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastXPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

XPU: registered at C:/Users/arc/ruijie/2.1_RC3/python311/frameworks.ai.pytorch.ipex-gpu/csrc/gpu/aten/operators/TripleOps.cpp:521 [kernel]
BackendSelect: fallthrough registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\PythonFallbackKernel.cpp:153 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\functorch\DynamicLayer.cpp:498 [backend fallback]
Functionalize: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\FunctionalizeFallbackKernel.cpp:290 [backend fallback]
Named: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\native\NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\VariableFallbackKernel.cpp:86 [backend fallback]
AutogradOther: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\VariableFallbackKernel.cpp:53 [backend fallback]
AutogradCPU: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\VariableFallbackKernel.cpp:57 [backend fallback]
AutogradCUDA: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\VariableFallbackKernel.cpp:65 [backend fallback]
AutogradXLA: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\VariableFallbackKernel.cpp:69 [backend fallback]
AutogradMPS: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\VariableFallbackKernel.cpp:77 [backend fallback]
AutogradXPU: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\VariableFallbackKernel.cpp:61 [backend fallback]
AutogradHPU: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\VariableFallbackKernel.cpp:90 [backend fallback]
AutogradLazy: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\VariableFallbackKernel.cpp:73 [backend fallback]
AutogradMeta: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\VariableFallbackKernel.cpp:81 [backend fallback]
Tracer: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\torch\csrc\autograd\TraceTypeManual.cpp:296 [backend fallback]
AutocastCPU: fallthrough registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\autocast_mode.cpp:382 [backend fallback]
AutocastXPU: registered at C:/Users/arc/ruijie/2.1_RC3/python311/frameworks.ai.pytorch.ipex-gpu/csrc/gpu/aten/operators/TripleOps.cpp:521 [kernel]
AutocastCUDA: fallthrough registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\autocast_mode.cpp:249 [backend fallback]
FuncTorchBatched: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:710 [backend fallback]
FuncTorchVmapMode: fallthrough registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\functorch\VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\functorch\TensorWrapper.cpp:203 [backend fallback]
PythonTLSSnapshot: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\PythonFallbackKernel.cpp:161 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\functorch\DynamicLayer.cpp:494 [backend fallback]
PreDispatch: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\PythonFallbackKernel.cpp:165 [backend fallback]
PythonDispatcher: registered at C:\Jenkins\workspace\IPEX-GPU-ARC770-Windows-Build\frameworks.ai.pytorch.private-gpu\aten\src\ATen\core\PythonFallbackKernel.cpp:157 [backend fallback]`

Can someone pls guide me.

**Comment by yinghu5** [comment]
@wangdq1989

Can you collect your envs by this [collect_env.py](https://github.com/intel/intel-extension-for-pytorch/blob/main/scripts/collect_env.py)

for ipex-llm issue, please also submit to  https://github.com/intel-analytics/ipex-llm/issues and see if anyone can help quickly. 

thanks
Ying

**Comment by yinghu5** [comment]
link to  https://github.com/intel-analytics/ipex-llm-tutorial/issues/78

**Comment by yinghu5** [comment]
About IPEX-llm installation, 
Please note here: ipex-llm window are supporting earlier version of ipex:  IPEX 2.1.10,  so  please use new environment, and follow the install guide of IPEX-llm  [IPEX-LLM Installation: GPU — IPEX-LLM latest documentation](https://ipex-llm.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html) windows
 step by step.   
Moreover, ipex-llm installation was integrated the ipex 2.1.10 installation, you don't need to install ipex independently.

Here is one for llama3 run on windows arc machine for your reference: 

[ipex-llm/python/llm/example/GPU/HF-Transformers-AutoModels/Model/llama3 at main · intel-analytics/ipex-llm (github.com)](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/HF-Transformers-AutoModels/Model/llama3)
conda create -n llm python=3.11 libuv
conda activate llm

# below command will install intel_extension_for_pytorch==2.1.10+xpu as default
pip install --pre --upgrade ipex-llm[xpu] --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/

# transformers>=4.33.0 is required for Llama3 with IPEX-LLM optimizations
pip install transformers==4.37.0

2. Configures OneAPI environment variables for Linux
Note
Skip this step if you are running on Windows.
 
Resolved

    
If you are installing ipex-llm and still run into the problem, please let me know the installation steps you are using.
