### ISSUE TITLE
Can a model quantized using IPEX be run with torch.compile enabled?

### ISSUE THREAD

**Issue by cfRod** [intel/intel-extension-for-pytorch#635]
### Describe the issue

I would like to static quantise an LLM model with IPEX but during inference of this model, I would like to load this model using and run the model.generate with torch.compile(backend="ipex" or "inductor") enabled.

**Comment by xiguiw** [comment]
@cfRod 
Please refer to this link:
https://pytorch.org/tutorials/prototype/pt2e_quant_x86_inductor.html?highlight=x86

It's a prototype feature. Prototype features are typically not available as part of binary distributions like PyPI or Conda, except sometimes behind run-time flags, and are at an early stage for feedback and testing.

**Comment by xiguiw** [comment]
@cfRod, 

Quantized model model + torch.compiler is NOT formally supported.
Till now, we recommend jit for quantized model.

Please refer to this example:
https://github.com/intel/intel-extension-for-pytorch/blob/main/examples/cpu/inference/python/llm/single_instance/run_quantization.py#L722

**Comment by cfRod** [comment]
>Quantized model model + torch.compiler is NOT formally supported. 
Do you mean via IPEX?

because with this https://pytorch.org/tutorials/prototype/pt2e_quant_x86_inductor.html?highlight=x86  can we start looking at Quantised model + torch.compile?

**Comment by cfRod** [comment]
Can we also use https://pytorch.org/tutorials/prototype/pt2e_quant_x86_inductor.html?highlight=x86  for FP16 and int4 thanks?

**Comment by cfRod** [comment]
Also can the model quantised with IPEX run via Eager mode?
When I tried to quantised the model and run "Benchmarking"
it seems to be setting up the model to run via JIT here https://github.com/intel/intel-extension-for-pytorch/blob/64fb34a6cae21880e7e45b35b71aaae8aa060bf3/examples/cpu/inference/python/llm/single_instance/run_quantization.py#L1060 and then later here https://github.com/intel/intel-extension-for-pytorch/blob/64fb34a6cae21880e7e45b35b71aaae8aa060bf3/examples/cpu/inference/python/llm/single_instance/run_quantization.py#L1150 does model.generate 

Can the IPEX scripts be used for e.g https://www.intel.com/content/www/us/en/developer/articles/technical/weight-only-quantization-in-llm-inference.html to run without torchscript? thanks. Apologies for the many questions! Just trying to wrap my head around what is possible with IPEX thanks!

**Comment by xiguiw** [comment]
> > Quantized model model + torch.compiler is NOT formally supported.
> 
> Do you mean via IPEX?
> 
> because with this https://pytorch.org/tutorials/prototype/pt2e_quant_x86_inductor.html?highlight=x86 can we start looking at Quantised model + torch.compile? Are there any other guidelines/ run time flags that I need to be aware of apart from the tutorial? thanks!

@cfRod  At the begnning of https://pytorch.org/tutorials/prototype/pt2e_quant_x86_inductor.html?highlight=x86

It says it's prototpye feature. That's what I said NOT formally supported. 

![image](https://github.com/intel/intel-extension-for-pytorch/assets/111278656/d1d1ff88-ef5c-42f3-9b82-7f56ebd61c27)

**Comment by cfRod** [comment]
Thanks you for your response. I appreciate that it is indeed prototype code, but I was interested in hacking together my workflow for my use case.

**Comment by xiguiw** [comment]
@cfRod  Let me check your questions and feedback to you later.

**Comment by xiguiw** [comment]
> an we start looking at Quantised model + torch.compile? Are there any other guidelines/ run time flags that I need to be aware of apart from the tutorial? thanks!
@cfRod 
Till now, this is the best know methd, configure to run Quantised model + torch.compile. 
So please follow this instructions. If you have any question/problems, please submit issues here.

**Comment by xiguiw** [comment]
> Can we also use https://pytorch.org/tutorials/prototype/pt2e_quant_x86_inductor.html?highlight=x86 for FP16 and int4 thanks?

No. It support INT8 only. FP16 and INT4 is **NOT** supported.

**Comment by xiguiw** [comment]
> Also can the model quantised with IPEX run via Eager mode? When I tried to quantised the model and run "Benchmarking" it seems to be setting up the model to run via JIT here
We recommened to run quantised model via Eager mode with pytorch, but the perforamcne are poor, even slower than FP32.

> Also sort of an extension to my original question -> can we quantise via ipex.optimise and get the best_model.pt and then run that via Eager mode or Inductor mode instead of JIT? As per this (https://www.intel.com/content/www/us/en/developer/articles/technical/weight-only-quantization-in-llm-inference.html ) it makes me that at least Eager mode is possible? Apologies for the many questions and thanks!

1. Yes, you can follow [this paper](https://pytorch.org/tutorials/prototype/pt2e_quant_x86_inductor.html?highlight=x86) to "Export Quantization flow to generate a quantized model customized for the x86 inductor backend"
We recommen to try this feature with offical PyTorch.

**Comment by xiguiw** [comment]
close as no more action required.
