### ISSUE TITLE
nvidia/amd gpu support for ipex

### ISSUE THREAD

**Issue by bopeng1234** [intel/intel-extension-for-pytorch#638]
### Describe the issue

Hi Team,

from [oneDNN](https://github.com/oneapi-src/oneDNN?tab=readme-ov-file#gpu-engine)/[oneMKL](https://github.com/oneapi-src/oneMKL?tab=readme-ov-file#hardware-platform-support) link, both of them experimental support nvidia/amd GPU.

so, is there any plan to support nvidia/amd GPU in framework side, I mean ipex?

This question is similar like #346.

thanks! best regards.

**Comment by MOLOjl** [comment]
@xiguiw Hi,
I'm considering to modify ipex to support nvidia/amd GPU, just use it to call onednn operaters(cudnn, miopen fuctions at the backend) on nvidia/amd GPU, is this easy? or tons of works I'm facing?

**Comment by xiguiw** [comment]
@MOLOjl Nvidia and AMD have their framework.  so IPEX is NOT designed to do this.
As I konw, on one did this before. Personally, if you just port some OP one a model, it's should be fine.
But if you want to it works well, I don't think it's a easy thing personally.

**Comment by xiguiw** [comment]
close as no more action required.
