### ISSUE TITLE
Torchaudio

### ISSUE THREAD

**Issue by ElliottDyson** [intel/intel-extension-for-pytorch#639]
I was curious as to whether or not you plan to support torchaudio?

With the release of GPT-4o, research has become even further focused on multimodality. With this research and many repositories, one being tortoise, requiring the support of torchaudio. It would be much appreciated to have a version of the package that includes IPEX/Intel-ARC support.

Thank you.

**Comment by xiguiw** [comment]
@ElliottDyson IPEX supports torch audio, but not all OP are supported.

If you have specific problem, please file a ticket.
