### ISSUE TITLE
Will intel extension for pytorch support dual a770 in one linux PC?

### ISSUE THREAD

**Issue by david-strejc** [intel/intel-extension-for-pytorch#641]
### Describe the issue

Is it possible to run two a770 in one Linux system and utilize both for inference of LLMs?

**Comment by jingxu10** [comment]
You mean 1 instance with 2 cards or 2 instances with 2 cards respectively?

**Comment by jingxu10** [comment]
close for long time no response. Feel free to reopen it later on if needed.
