### ISSUE TITLE
Qwen-7b int8 inference fails when using run_quantization.py script

### ISSUE THREAD

**Issue by MadhumithaSrini** [intel/intel-extension-for-pytorch#648]
### Describe the issue

1. Tried running https://github.com/intel/intel-extension-for-pytorch/blob/release/2.3/examples/cpu/inference/python/llm/run.py to generate the q_config_summary file
2. Then, I tried inferring with ipex 2.3.0, torch 2.3.0, transformers==4.38.2 and it fails with the following error:
            return forward_call(*args, **kwargs)
            RuntimeError: The following operation failed in the TorchScript interpreter.
            Traceback of TorchScript (most recent call last):
            RuntimeError: cannot return dims when ndims < 0

**Doubt:** I generated the q_config_summary_file without enabling bf16, but while inferring I am enabling it with "--quant-with-amp" flag. I tested couple of other models like gpt-j-6b, chatglm3, llama-2-7b-chat-hf and all of this pass while qwen fails at inference. 
So, will using the flag "quant-with-amp" in inference and not while generating the config file matter?

**Comment by Vasud-ha** [comment]
Hi @MadhumithaSrini, thanks for reporting it we will check at our end and return to you.

**Comment by MadhumithaSrini** [comment]
Thank you

**Comment by Vasud-ha** [comment]
Hi @MadhumithaSrini, could you please share the commands you used for step 1 and step 2?

**Comment by MadhumithaSrini** [comment]
Hi sure, the command is:
OMP_NUM_THREADS=<num_threads> numactl -m 0 python run.py --benchmark -m Qwen/Qwen-7B --output-dir saved_results_qwen --ipex-smooth-quant --quant-with-amp --qconfig-summary-file ./saved_results_qwen/best_configure.json --max-new-tokens 1 --input-tokens 512 --num-iter 6 --num-warmup 3 --batch-size 1 --profile

**Comment by devpramod** [comment]
Hi @MadhumithaSrini I am able to reproduce the error. Thanks for reporting.
I'll perform the necessary triage and get back to you.

**Comment by devpramod** [comment]
@MadhumithaSrini static quantization with AMP is still experimental, please remove the flag `--quant-with-amp` when running Qwen 7b until we resolve this issue.
