### ISSUE TITLE
IPEX Fusions for BF16

### ISSUE THREAD

**Issue by sreelekshmyanil** [intel/intel-extension-for-pytorch#650]
I tried running ipex.optimize followed by tracing/scripting. I am not able to see any fusion groups in IR (torch.jit.last_executed_optimized_graph()). Is there any way to get the fusion groups other than through verbose?

**Comment by jgong5** [comment]
Do you mean by "fusion group"? We rewrite the graph by replace the matched patterns to fused ops. What do you expect to see?

**Comment by sreelekshmyanil** [comment]
So, when we use onednn graph api (torch.jit.enable_onednn_fusion(True), in the IR, we can observe fusion groups as OneDNNFusionGroup_ . Does ipex also do graph fusions in the same way? I read in the documentation that, graph optimizations are enabled in ipex by default( ipex.enable_onednn_fusion). I want to know whether both are same.  

Also, is there any other way to see fused ops, other than through verbose post-ops?

**Comment by sanchitintel** [comment]
> we can observe fusion groups as OneDNNFusionGroup_

With IPEX, you'll see a slightly different name for oneDNN Graph fusion groups, but only with int8 static quantization (you could also use BF16 with AMP alongside int8 static quantization, but only with a processor that supports the AVX512_BF16 ISA).

> Does ipex also do graph fusions in the same way? I read in the documentation that, graph optimizations are enabled in ipex by default( ipex.enable_onednn_fusion). I want to know whether both are same

Intel Extension for PyTorch also supports fusions that don't use oneDNN Graph.

**Comment by vishnumadhu365** [comment]
@sreelekshmyanil was your query answered ?

**Comment by YuningQiu** [comment]
Close this issue for now. Please feel free to re-open this issue or create a new one if you have an further questions or concerns. Thanks a lot!
