### ISSUE TITLE
OSerror during run  : how do I config with huggingface before run

### ISSUE THREAD

**Issue by pauldintel** [intel/intel-extension-for-pytorch#655]
### Describe the issue

OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like meta-llama/Llama-2-7b-hf is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
LLM RUNTIME ERROR: Running generation task failed. Quit.

**Comment by akashdhamasia12** [comment]
Hi, could you please send the reproducer with environment details to replicate this issue, i dont think it is an issue of intel-extension-for-pytorch. Thanks.

**Comment by pauldintel** [comment]
I think the issue is provisioning the access by Meta before trying that model . Since all access part got resolved I don't see that anymore. thanks for getting back
