### ISSUE TITLE
Compilation Intel Extension For PyTorch with specific AOT device enabled didn't reduce AOT for first pass tensor to model.

### ISSUE THREAD

**Issue by MaksimDanilov** [intel/intel-extension-for-pytorch#659]
### Describe the issue

I tried to resolve this problem [Native API failed. Native API returns: -2 (PI_ERROR_DEVICE_NOT_AVAILABLE) -2 (PI_ERROR_DEVICE_NOT_AVAILABLE)](https://github.com/intel/intel-extension-for-pytorch/issues/643) by compiling an extension with AOT=dg1 'cause my display driver is Intel Iris Xe Graphics.  
I used compile_bundle.bat script as recommended on installation page. Everything builded fine except large compiling time (around 14-15 hours) and some warnings before starting making fat binary (see 2d screenshot).  
However, when I tried to run for loop with my model, first pass was taking too long. How can I find if I compiled the extension correctly or maybe I did it in wrong way?

![Screenshot 2024-06-17 095831](https://github.com/intel/intel-extension-for-pytorch/assets/47329914/d7a93741-532d-442d-9ecd-1dbeee044743)

![telegram-cloud-photo-size-2-5440399181257757871-y](https://github.com/intel/intel-extension-for-pytorch/assets/47329914/82d54328-e8fe-4687-9d7d-e9534a26cc72)

**Comment by MaksimDanilov** [comment]
I can upload dll if it helps you.

**Comment by YuningQiu** [comment]
> I can upload dll if it helps you.

Sure, that would be great. Also, could you please share your CPU information?

**Comment by MaksimDanilov** [comment]
![Screenshot 2024-06-18 105959](https://github.com/intel/intel-extension-for-pytorch/assets/47329914/ef86649d-8926-43e3-b432-69378f493001)

**Comment by YuningQiu** [comment]
Hello, the long compiling time can be caused by either the limitation of the iGPU, or the AOT setting. We will look into this issue and get back to you once we have updates. Thanks for your patience!

**Comment by YuningQiu** [comment]
Hello, currently only ats-m and pvc are supported with AOT setting options. You can find more details here https://intel.github.io/intel-extension-for-pytorch/xpu/2.1.30%2Bxpu/tutorials/technical_details/AOT.html. Hope this can be helpful to your case.

**Comment by MaksimDanilov** [comment]
@YuningQiu, Hello. I read it and my hope was that it's not a strict option, cause article in the end has link to compile for another device type. It seems this thread must be closed now :-(
