### ISSUE TITLE
how to free gpu without restarting python

### ISSUE THREAD

**Issue by 13917904019** [intel/intel-extension-for-pytorch#661]
### Describe the issue

After I had set the model and data to None, although torch.xpu.memory_allocated() was 0, but the result from the Resource Manager was not. What was the reason, and how to deal with it. Thanks.

![image](https://github.com/intel/intel-extension-for-pytorch/assets/44342693/6087b001-57c2-4370-8be5-212a42f5c4c1)

**Comment by ZhaoqiongZ** [comment]
Hi @13917904019 , I saw your driver version is quite old, could you please try with the latest driver version. https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html

**Comment by 13917904019** [comment]
ok，thanks. I will try it.
