### ISSUE TITLE
does ipex.llm support speculative sampling?  

### ISSUE THREAD

**Issue by zhangnju** [intel/intel-extension-for-pytorch#664]
### Describe the issue

Hi IPEX guys 
does ipex.llm support speculative sampling? if support, where are the codes? and how do we test it? 
Thanks

**Comment by ZailiWang** [comment]
Hi, for IPEX CPU the support for speculative sampling is working in progress, please keep tuned.
For IPEX XPU, this support has not been taken into the scope for now.
