### ISSUE TITLE
Running IPEX samples - environment setup clarification

### ISSUE THREAD

**Issue by js333031** [intel/intel-extension-for-pytorch#669]
### Describe the issue

I would like to install IPEX for CPU via PIP and run the sample code. 

I installed IPEX using steps from [here](https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=cpu&version=v2.3.0%2bcpu&os=linux%2fwsl2&package=pip)

Then, to run a demo, I looked at section 3 [here](https://github.com/intel/intel-extension-for-pytorch/tree/main/examples/cpu/inference/python/llm) for the instructions.  I'm not using Docker. Section 3.2 downloads a lot of things since that section's intention is to compile IPEX. 

For running the demo, can section 3 provide instructions for case where one installs IPEX using the first link above?

**Comment by js333031** [comment]
Found steps here. Trying them out and will update the issue accordingly. https://github.com/intel/intel-extension-for-pytorch/blob/v2.3.0%2Bcpu/examples/cpu/inference/python/llm/README.md#32-conda-based-environment-setup-with-pre-built-wheels

**Comment by tye1** [comment]
@jingxu10  please take a look.

**Comment by wangkl2** [comment]
@js333031 Thanks for reporting the issue. Yes, the ipex will be built from source anyway in the main branch, while using the release branch such as `2.3.100+cpu` will have the option to use pre-compiled whls or build from source.
