### ISSUE TITLE
DPC++ Extension is not enabled on Windows OS

### ISSUE THREAD

**Issue by jeremyyx** [intel/intel-extension-for-pytorch#671]
### Describe the bug

Do we have plans for supporting this feature? It means a lot to me to do some experiments on Windows. And I would love to do this support this feature with your advice.

### Versions

2.1.30

**Comment by YixinSong-e** [comment]
I want to add my custom iGPU sycl operator to ipex on xpu. If I bypass the xpu implementation of ipex and implement the igpu operator separately, I don’t know how to make the two compatible, so my first thought is to find a way to make windows support the expansion capabilities.

**Comment by YixinSong-e** [comment]
Yes my sycl operator works well on my local environment. In fact, due to some unavoidable reasons, I need to deploy my operators and models in a Windows environment. :(

**Comment by YixinSong-e** [comment]
I'll try that. Thank you. :)
