### ISSUE TITLE
[Windows] [Pyinstaller] Process exit when I use "Pyinstaller" to package, the executable cannot detect XPU.

### ISSUE THREAD

**Issue by tjtanaa** [intel/intel-extension-for-pytorch#674]
### Describe the issue

I have no issue when running before packaging.

I encounter the same issue with pyinstaller compiled executable. The program exited within AutoModelForCausalLM without any error. I can observed that the progress bar of loading the weight is complete. 

```
        self.model = AutoModelForCausalLM.from_pretrained(
            model_path, trust_remote_code=True
        ).to(self.device)
```

 There is also this error when launching the `intel_extension_for_pytorch`.

`intel_extension_for_pytorch\xpu\lazy_init.py` when loading extension `_C._initExtension()` is causing the following error. `_C` is `_C.cp310-win_amd64.pyd`
```        
 intel_extension_for_pytorch\xpu\lazy_init.py:80: UserWarning: XPU Device count is zero! (Triggered internally at C:/Users/arc/ruijie/2.1_RC3/python310/frameworks.ai.pytorch.ipex-gpu/csrc/gpu/runtime/Device.cpp:127.)
  _C._initExtension()
```

**Comment by huiyan2021** [comment]
Hi @tjtanaa, could you share a reproducer step by step? Thanks!

**Comment by tjtanaa** [comment]
> Hi @tjtanaa , We don't support PyInstaller and no bandwidth at the time being.

Could you give me some pointers as to which part of the code that is generates `_C.cp310-win_amd64.pyd`, so that in the meantime, I could try to look into it on my end.

**Comment by xiguiw** [comment]
> # Steps to Reproduce
> 1. Install `embeddedllm`.
> 2. `git clone https://github.com/EmbeddedLLM/embeddedllm.git --branch ipex-llm-win-tj`
> 3. `cd embeddedllm`
> 4. `conda create -n ellm python=3.10 libuv; conda activate ellm`
> 5. `ELLM_TARGET_DEVICE='ipex' python setup.py develop`
> 6. Go to `C:\Users\<user>\anaconda3\envs\ellmifp\Lib\site-packages\ipex_llm\transformers\convert.py` of your conda environment to change the following line 56: `_IS_VLLM_AVAILABLE = None` to `_IS_VLLM_AVAILABLE = False`.

What's your environment to reproduce this issue. The Intel extension-for-pytorch version, oneAPI version, driver version? 
What's the `ipex_llm` is?

**Comment by xiguiw** [comment]
> There is also this error when launching the `intel_extension_for_pytorch`.
> 
> `intel_extension_for_pytorch\xpu\lazy_init.py` when loading extension `_C._initExtension()` is causing the following error. `_C` is `_C.cp310-win_amd64.pyd`
> 
> ```
>  intel_extension_for_pytorch\xpu\lazy_init.py:80: UserWarning: XPU Device count is zero! (Triggered internally at C:/Users/arc/ruijie/2.1_RC3/python310/frameworks.ai.pytorch.ipex-gpu/csrc/gpu/runtime/Device.cpp:127.)
>   _C._initExtension()
> ```

@tjtanaa 
How did you install IPEX? 
What are these: "C:/Users/arc/ruijie/2.1_RC3/python310/frameworks.ai.pytorch.ipex-gpu/csrc/gpu/runtime/Device.cpp:127" 
I did not find any 'gpu' in IPEX source files (it's 'xpu'). And I did find out the file 'Device.cpp' in IPEX source code.

**Comment by jingxu10** [comment]
> > Hi @tjtanaa , We don't support PyInstaller and no bandwidth at the time being.
> 
> Hi, @huiyan2021 , could you give me some pointers as to which part of the code that is generates `_C.cp310-win_amd64.pyd`, so that in the meantime, I could try to look into it on my end.

@ashokei @min-jean-cho  any insights?

**Comment by min-jean-cho** [comment]
> UserWarning: XPU Device count is zero!

Could you please run command `sycl-ls` after activating oneAPI environment to verify your GPU device is being detected?

**Comment by tjtanaa** [comment]
@xiguiw 
I installed `ipex-llm` from `pypi package`. The steps is based on this [Ipex-llm: Install Windows GPU](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/install_windows_gpu.md)
which runs the command `pip install --pre --upgrade ipex-llm[xpu] --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/`

When installing `embeddedllm` it will run this same command `pip install --pre --upgrade ipex-llm[xpu] --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/`.

**Comment by tjtanaa** [comment]
> > UserWarning: XPU Device count is zero!
> 
> Could you please run command `sycl-ls` after activating oneAPI environment to verify your GPU device is being detected?

@min-jean-cho 
I forgot to disclose my hardware setup. The following is my hardware setup. It is a **Windows 11 PC with Hardware: Intel(R) Core(TM) Ultra 7 165H**

The `ipex-llm[xpu]` supports the use of `iGPU` of `Intel(R) Core(TM) Ultra 7 165H`.
The `ipex-llm[xpu]` is able to detect and utilized the `iGPU` when I run through python command.
However, after packaging it into executable using pyInstaller, the executable cannot detect and utilized the `iGPU` and fail to run.

**Comment by MaksimDanilov** [comment]
@tjtanaa, Hello. I use pyinstaller once to make exe and succeed. You need to ensure that all dll including 
<img width="825" alt="image" src="https://github.com/user-attachments/assets/56bde51f-0140-4500-bc73-83fc0b921719">
you have in PATH or in your dist package. And of course, pyinstaller knows nothing about ipex package and its dependencies, so you need to do everything manually.

**Comment by tjtanaa** [comment]
> @tjtanaa, Hello. I use pyinstaller once to make exe and succeed. You need to ensure that all dll including 
> <img width="825" alt="image" src="https://github.com/user-attachments/assets/56bde51f-0140-4500-bc73-83fc0b921719">
> you have in PATH or in your dist package. And of course, pyinstaller knows nothing about ipex package and its dependencies, so you need to do everything manually.

Thank you. Can u share the steps to include all the dll?

**Comment by MaksimDanilov** [comment]
@tjtanaa firstly, lets check if everything works fine. Try to launch your exe in console, but before that use Intel oneAPI setvars button as suggested in installation page. if you don't have oneAPI installed, then update PATH variable with installation path of anaconda packages, that correspond with above dependencies. 
If everything works fine, you are free-to-go to find all deps of your exe.

**Comment by tjtanaa** [comment]
@MaksimDanilov Thank you very much for the confidence and pointers. I have managed to compile a pyinstaller executable. 
I found that the latest Arc Driver is not compatible with `ipex-llm`. The engine will hang. So I downgraded and tested that the driver version `32.0.101.5762` is working for me.

**Comment by def-know-how-to-code-trust** [comment]
Hey sorry, @tjtanaa could you share the .spec file if you are using it?

**Comment by def-know-how-to-code-trust** [comment]
Thank you! Turns out I was not packing one of the dll files from one api
