### ISSUE TITLE
tensor parallel support for multi intel GPU

### ISSUE THREAD

**Issue by bopeng1234** [intel/intel-extension-for-pytorch#680]
Hi ipex team,

from torch 2.3, they are going to support tensor parallel on native pytorch.

https://pytorch.org/blog/pytorch2-3/

https://pytorch.org/docs/stable/distributed.tensor.parallel.html

is there any plan for ipex to support the tensor parallel, train or inference on multi MAX or Arc GPU.

thanks.

**Comment by xiguiw** [comment]
Hi @bopeng1234,

Distributed training with PyTorch DDP is accelerated by oneAPI Collective Communications Library Bindings for Pytorch* (oneCCL Bindings for Pytorch*). The extension supports FP32 and BF16 data types. More detailed information and examples are available at the [Github repo](https://github.com/intel/torch-ccl).

Here is the document for [IPEX Distributed Training](https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/examples.html#distributed-training)

Is this what you want?

**Comment by bopeng1234** [comment]
Hi @xiguiw , I guess no, IPEX is supporting data parallel distribute training, pytorch is supporting tensor parallel training.

**Comment by xiguiw** [comment]
> Hi @xiguiw , I guess no, IPEX is supporting data parallel distribute training, pytorch is supporting tensor parallel training.

Hi @bopeng1234, deeps peed + IPEX for tensor parallel training.

So you want IPEX native tensor parallel training without deep-speed?

**Comment by bopeng1234** [comment]
@xiguiw , thanks for the information, yes, to my knowledge, PyTorch is supporting tensor parallel by native in release 2.3.
I would like to know if Ipex will follow up on that to enable the feature without other dependencies, eg deepspeed.

I also noticed next Ipex release will be based on PyTorch 2.3.1, that's why I opened this issue.

**Comment by xiguiw** [comment]
@bopeng1234 
I did not get a clear information about this yet.
Will feedback to you when I get the answer.

**Comment by xiguiw** [comment]
@bopeng1234 
Yes, IPEX 2.3 will support tensor parallel for multi Intel GPU without other dependencies.
But the released version is not determined, yet. (i.e. the first released IPEX 2.3 version may not enable it).

**Comment by bopeng1234** [comment]
thank you, no problems now, we can close this issue.

**Comment by Qubitium** [comment]
@jingxu10 Is there an example of IPEX llm for tensor paralle on ARC  either for inference or for training? The current docs only shows DataParallel:

https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/examples.html#distributed-training

```
model = torch.nn.parallel.DistributedDataParallel(model)
```
