### ISSUE TITLE
When I try to run the fp8 quantized flux model with ComfyUI, the following problem occurs:

### ISSUE THREAD

**Issue by 1ngram433** [intel/intel-extension-for-pytorch#687]
### Describe the bug

I only have 16G ram and an A750 graphics card, but I want to run flux locally, so I simplified the workflow. Then I got this error. I think it's because ComfyUI loads part of the model in memory. In the same environment, I can run the quantized SD3.
![Flux-schnell工作流](https://github.com/user-attachments/assets/da5f19ca-e6ca-4324-bc76-0e7813a872e7)

got prompt
model weight dtype torch.bfloat16, manual cast: None
model_type FLOW
Requested to load Flux
Loading 1 new model
loading in lowvram mode 6705.278125
!!! Exception during processing!!! The model is mixed with different device type
Traceback (most recent call last):
  File "C:\Program Files\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\ComfyUI\comfy_extras\nodes_custom_sampler.py", line 612, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\ComfyUI\comfy\samplers.py", line 706, in sample
    self.inner_model, self.conds, self.loaded_models = comfy.sampler_helpers.prepare_sampling(self.model_patcher, noise.shape, self.conds)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\ComfyUI\comfy\sampler_helpers.py", line 66, in prepare_sampling
    comfy.model_management.load_models_gpu([model] + models, memory_required=memory_required, minimum_memory_required=minimum_memory_required)
  File "C:\Program Files\ComfyUI\comfy\model_management.py", line 468, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\ComfyUI\comfy\model_management.py", line 301, in model_load
    self.real_model = ipex.optimize(self.real_model.eval(), graph_mode=True, concat_linear=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1ngram4\anaconda3\envs\torch_arc\Lib\site-packages\intel_extension_for_pytorch\frontend.py", line 353, in optimize
    raise RuntimeError("The model is mixed with different device type")
RuntimeError: The model is mixed with different device type

Prompt executed in 65.10 seconds

### Versions

C:\Users\1ngram4\anaconda3\envs\torch_arc\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\1ngram4\anaconda3\envs\torch_arc\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Collecting environment information...
PyTorch version: 2.1.0.post2+cxx11.abi
PyTorch CXX11 ABI: No
IPEX version: 2.1.30.post0
IPEX commit: 97b37e23d
Build type: Release

OS: Microsoft Windows 11 专业版
GCC version: N/A
Clang version: N/A
IGC version: 2024.1.0 (2024.1.0.20240308)
CMake version: version 3.28.0-msvc1
Libc version: N/A

Python version: 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is XPU available: True
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration:
[0] _DeviceProperties(name='Intel(R) Arc(TM) A750 Graphics', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.29803', has_fp64=0, total_memory=7934MB, max_compute_units=448, gpu_eu_count=448)
Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture=9
CurrentClockSpeed=3600
DeviceID=CPU0
Family=107
L2CacheSize=3072
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3600
Name=AMD Ryzen 5 5500
ProcessorType=3
Revision=20480

Versions of relevant libraries:
[pip3] intel_extension_for_pytorch==2.1.30.post0
[pip3] numpy==1.26.4
[pip3] torch==2.1.0.post2+cxx11.abi
[pip3] torchaudio==2.1.0.post2+cxx11.abi
[pip3] torchsde==0.2.6
[pip3] torchvision==0.16.0.post2+cxx11.abi
[conda] intel-extension-for-pytorch 2.1.30.post0             pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.1.0.post2+cxx11.abi          pypi_0    pypi
[conda] torchaudio                2.1.0.post2+cxx11.abi          pypi_0    pypi
[conda] torchsde                  0.2.6                    pypi_0    pypi
[conda] torchvision               0.16.0.post2+cxx11.abi          pypi_0    pypi

**Comment by ZhaoqiongZ** [comment]
Hi @1ngram433 , thank you for trying IPEX and reporting this issue.
I am looking into this issue and will get back to you as soon as possible.

**Comment by ZhaoqiongZ** [comment]
Hi @1ngram433 , could you list more information here, 
for example, the link to the models you use in your env?
how did you set it up?

**Comment by m1712948113** [comment]
I have the same problem when  i used FLUX.1 model.

**Comment by ZhaoqiongZ** [comment]
Hi @1ngram433  and @m1712948113 ,
I tried both 2.1.30+xpu and latest 2.1.40+xpu to run flux fp8 with comfyui  by following guide https://comfyanonymous.github.io/ComfyUI_examples/flux/#simple-to-use-fp8-checkpoint-version.
both these two version works properly. Could you describe the steps you take to run it?

**Comment by 1ngram433** [comment]
Hi @1ngram433 and @m1712948113, I tried both 2.1.30+xpu and the latest 2.1.40+xpu to run flux fp8 with comfyui by following the guide https://comfyanonymous.github.io/ComfyUI_examples/flux/#simple-to-use-fp8-checkpoint-version. Both of these two versions work properly. Could you describe the steps you take to run it?

Thank you for your contribution. I have temporarily resolved this issue. At first, I used the default method to start ComfyUI with python main.py, using the models from https://huggingface.co/Kijai/flux-fp8/tree/main. Later, I tried adding the parameter "python main.py --disable-ipex-optimize" to disable ipex.optimize when loading models with Intel GPUs, and then it ran smoothly. I'm not sure if this is a ComfyUI issue or an IPEX issue.

**Comment by simonlui** [comment]
@1ngram433 I implemented that piece of code in ComfyUI, `ipex.optimize` should work and does currently on my Linux machine and it seems like @ZhaoqiongZ got it working too since it is called by default. The only other thing I can think of is that you don't have your ComfyUI install updated since there were some changes that were added to the repository fixing lowvram mode specifically like https://github.com/comfyanonymous/ComfyUI/commit/74e124f4d784b859465e751a7b361c20f192f0f9 and https://github.com/comfyanonymous/ComfyUI/commit/83f343146ae1e8ccaf21da5b012bf59c78b97179 just today. I was busy so I didn't touch flux until around 2-3 days ago when that first change was already put in.

**Comment by ZhaoqiongZ** [comment]
Hi @1ngram433 ， maybe you can have a try with latest ComfyUI code as simonlui said.

**Comment by simonlui** [comment]
@1ngram433 I figured out the issue after playing around with the ComfyUI arguments passed and I can't believe I missed this. You have to add `--fp8_e4m3fn-unet` to your ComfyUI launch options and it should work. You aren't using it now, hence, ComfyUI defaults to thinking your diffusion model is a different type, bf16, per this line in your log as Intel Arc GGPUs support it.
`model weight dtype torch.bfloat16, manual cast: None`
I don't cast anything in the `ipex.optimize` call due to different types per model used and passed in the function. Let me know if this change solves your issue.

**Comment by bongshagalaga** [comment]
have you solve the problem about "The model is mixed with different device type"

**Comment by AlexFeYang** [comment]
hey, I still got this problem, and solve by adding "--disable-ipex-optimize" when launching

**Comment by CaledoniaProject** [comment]
@simonlui I run fp8 on L40S instance, with `--fp8_e4m3fn-unet` comfyui still make the cast, any ideas?

```
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
model_type FLUX
```

**Comment by simonlui** [comment]
@CaledoniaProject You need to use the "Load Diffusion Model" node in ComfyUI to load FLUX checkpoints. If you don't use that, it will only get down to at most torch.bfloat16 and not torch.float8_e4m3fn

**Comment by CaledoniaProject** [comment]
Hi @simonlui I am indeed using it, but still getting cast. Take a look at my workflow:

![Image](https://github.com/user-attachments/assets/7dad0948-82a7-4d20-b28a-8a44093601f7)

**Comment by simonlui** [comment]
It's not a workflow problem, it seems like the code changed so the model configuration supported inference types don't include FP8.

![Image](https://github.com/user-attachments/assets/8041537b-aad1-4256-881a-a2572fb705f5)

It doesn't affect me since XPU has improved its memory management and there is no native FP8 inference in XPU devices so I would never need to use it. Would suggest you would need to open an issue in ComfyUI itself for supporting it on devices that support FP8 and this is the wrong place to ask for something like that anyways.
