### ISSUE TITLE
0 <= device.index() && device.index() < static_cast<c10::DeviceIndex>(device_ready_queues_.size()) INTERNAL ASSERT FAILED at "C:\\Jenkins\\workspace\\IPEX-GPU-ARC770-Windows-Build\\frameworks.ai.pytorch.private-gpu\\torch\\csrc\\autograd\\engine.cpp":1421

### ISSUE THREAD

**Issue by niuhongbin1** [intel/intel-extension-for-pytorch#688]
### Describe the bug

```
import numpy as np
import torch
import intel_extension_for_pytorch as ipex
from torch.utils import data
from d2l import torch as d2l

true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)
def load_array(data_arrays, batch_size, is_train=True):  #@save
    """构造一个PyTorch数据迭代器"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 10
data_iter = load_array((features, labels), batch_size)
from torch import nn
net = nn.Sequential(nn.Linear(2, 1))
net = net.to('xpu')
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)
loss = nn.MSELoss()
loss = loss.to('xpu')
trainer = torch.optim.SGD(net.parameters(), lr=0.03)
net,trainer = ipex.optimize(net,optimizer=trainer)
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        X = X.to("xpu")
        y = y.to("xpu")
        l = loss(net(X) ,y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')
```
## errors 
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[9], line 24
     22     l = loss(net(X) ,y)
     23     trainer.zero_grad()
---> 24     l.backward()
     25     trainer.step()
     26 l = loss(net(features), labels)

File E:\miniconda\envs\txpu\lib\site-packages\torch\_tensor.py:492, in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
    482 if has_torch_function_unary(self):
    483     return handle_torch_function(
    484         Tensor.backward,
    485         (self,),
   (...)
    490         inputs=inputs,
    491     )
--> 492 torch.autograd.backward(
    493     self, gradient, retain_graph, create_graph, inputs=inputs
    494 )

File E:\miniconda\envs\txpu\lib\site-packages\torch\autograd\__init__.py:251, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    246     retain_graph = create_graph
    248 # The reason we repeat the same comment below is that
    249 # some Python versions print out the first line of a multi-line function
    250 # calls in the traceback and some print out the last line
--> 251 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    252     tensors,
    253     grad_tensors_,
    254     retain_graph,
    255     create_graph,
    256     inputs,
    257     allow_unreachable=True,
    258     accumulate_grad=True,
    259 )

RuntimeError: 0 <= device.index() && device.index() < static_cast<c10::DeviceIndex>(device_ready_queues_.size()) INTERNAL ASSERT FAILED at "C:\\Jenkins\\workspace\\IPEX-GPU-ARC770-Windows-Build\\frameworks.ai.pytorch.private-gpu\\torch\\csrc\\autograd\\engine.cpp":1421, please report a bug to PyTorch. 
```

### Versions

E:\miniconda\envs\txpu\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'E:\miniconda\envs\txpu\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Collecting environment information...
PyTorch version: 2.1.0.post3+cxx11.abi
PyTorch CXX11 ABI: No
IPEX version: 2.1.40+xpu
IPEX commit: 80ed47655
Build type: Release

OS: Microsoft Windows 11 教育版
GCC version: N/A
Clang version: N/A
IGC version: 2024.2.1 (2024.2.1.20240711)
CMake version: N/A
Libc version: N/A

Python version: 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is XPU available: True
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration:
[0] _DeviceProperties(name='Intel(R) Arc(TM) A770 Graphics', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.29516', has_fp64=0, total_memory=15930MB, max_compute_units=512, gpu_eu_count=512)
Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture=9
CurrentClockSpeed=3700
DeviceID=CPU0
Family=205
L2CacheSize=9728
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3700
Name=12th Gen Intel(R) Core(TM) i5-12600KF
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] intel_extension_for_pytorch==2.1.40+xpu
[pip3] numpy==1.23.5
[pip3] torch==2.1.0.post3+cxx11.abi
[pip3] torchaudio==2.1.0.post3+cxx11.abi
[pip3] torchvision==0.16.0.post3+cxx11.abi
[conda] intel-extension-for-pytorch 2.1.40+xpu               pypi_0    pypi
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] torch                     2.1.0.post3+cxx11.abi          pypi_0    pypi
[conda] torchaudio                2.1.0.post3+cxx11.abi          pypi_0    pypi
[conda] torchvision               0.16.0.post3+cxx11.abi          pypi_0    pypi

**Comment by ZailiWang** [comment]
Thanks for reporting this. I'll try to reproduce and analyze the issue and get back to you.

**Comment by ZailiWang** [comment]
Looks like you are not moving `features` and `labels` to xpu. Would you try if the error could be eliminated with the change?

**Comment by niuhongbin1** [comment]
> Looks like you are not moving `features` and `labels` to xpu. Would you try if the error could be eliminated with the change?

X,y is features,labels. They were .to("xpu"). I will try to move features and labels to xpu.

**Comment by niuhongbin1** [comment]
> Looks like you are not moving `features` and `labels` to xpu. Would you try if the error could be eliminated with the change?

Thanks for your help!
