### ISSUE TITLE
Powershell environment scripts to fix "[WinError 126] The specified module could not be found. Error loading "C:\path\to\venv\lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies"

### ISSUE THREAD

**Issue by han-minhee** [intel/intel-extension-for-pytorch#689]
#485 
```
python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.__version__); print(ipex.__version__); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\path\to\.conda\envs\intel\Lib\site-packages\torch\__init__.py", line 139, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\path\to\.conda\envs\intel\Lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies.
```
            
I've also faced the [issue](https://github.com/intel/intel-extension-for-pytorch/issues/485) but couldn't find a proper fix. I'll be glad if you can provide me a link, but anyway, instead, I tried [writing powershell scripts](https://github.com/han-minhee/intel-extension-for-pytorch-powershell-fix) to use instead of the current vars.bat files. Can someone checks if it also works on your environment?

**Comment by ZailiWang** [comment]
Thanks for your connection. You mean your powershell script is expected to work but actually not working at your side?

**Comment by karnikkanojia** [comment]
@han-minhee, I don't think so that the sanity test commands(faced the same problem) are really meant for powershell. I ran it on the command prompt with few changes

```cmd
call "%DPCPPROOT%\env\vars.bat"
call "%MKLROOT%\env\vars.bat"
```

Do set the DPCPPROOT and MKLROOT in your env vars probably:
- DPCPPROOT: "C:\Program Files (x86)\Intel\oneAPI\compiler\latest"
- MKLROOT: "C:\Program Files (x86)\Intel\oneAPI\mkl\latest"

and if you want to run things on powershell the commands would be:
```powershell
Start-Process "$env:DPCPPROOT\env\vars.bat"
Start-Process "$env:MKLROOT\env\vars.bat"
```

**Comment by han-minhee** [comment]
> Thanks for your connection. You mean your powershell script is expected to work but actually not working at your side?

It works for me, but wanted to check if it works on other enviroments too

**Comment by han-minhee** [comment]
I see that it will be unnecessary from future pytorch versions. Closing the issue on my own
