### ISSUE TITLE
Building with torch nightly (torch 2.5) for XPU

### ISSUE THREAD

**Issue by narendrachaudhary51** [intel/intel-extension-for-pytorch#693]
### Describe the issue

Latest, pytorch has XPU support by default. Additionally, XPU triton backend is also moving towards working with the upstream pytorch. However, this repo works only with older version of pytorch. When it will be possible to build this repo with upstream pytorch?

**Comment by ZailiWang** [comment]
Hi, `ipex-xpu` extends upstream PyTorch so a patched PyTorch lib is required.
As you mentioned, Intel have enabled XPU support with upstream PyTorch. Currently Intel PyTorch team is focusing on the maturity of upstream PyTorch support for Intel XPU. `ipex-xpu` is providing complete support for running PyTorch workloads on Intel XPU in the short term, and will be eventually deprecated when upstream PyTorch support is mature.

**Comment by narendrachaudhary51** [comment]
Pytorch version (2.1) supported by ipex is too old. The newer version of pytorch (2.4 onwards) supports triton xpu backend. Currently, it is not possible to run triton-based code with ipex and torch(2.1). We also cannot run triton-based code with oneccl as that also requires torch 2.1. Is it possible to have the patched pytorch with >2.4 as the supported version? This will enable users to run newer triton-based workloads on XPU with ipex and oneccl.

**Comment by ZailiWang** [comment]
A new `ipex-xpu` version based on PyTorch2.3 is planned to  be released in around 2 weeks and further release plan is under dicussion.
Since upstream PyTorch has triton xpu backend now, I think we don't have to run xpu triton with IPEX?

**Comment by narendrachaudhary51** [comment]
How do we scale a triton-based workload to multiple XPUs without torch-ccl (oneccl_bindings_for_pytorch)? 
If torch-ccl doesn't work with upstream pytorch then it will not be possible.

**Comment by ZailiWang** [comment]
I see your point. As I mentioned above, upstream PyTorch support is working in progress. The feature like distributed via torch-ccl is likely to be supported early 2025. Before that `ipex-xpu` is required. IPEX team is working for minimize the time gap but anyway it will fall behind of official PyTorch versions as the features are dependent on a patched PyTorch.

**Comment by jingxu10** [comment]
pls try nightly built
`pip3 install --pre torch torchvision torchaudio --index-url
https://download.pytorch.org/whl/nightly/xpu`

**Comment by narendrachaudhary51** [comment]
Should I compile and use the latest IPEX on top of that? I can see that there are some commits related to that.

**Comment by ZailiWang** [comment]
No, this is for installing PyTorch with support for Intel GPU, IPEX is not needed.
