### ISSUE TITLE
unable to install pytorch and ipex

### ISSUE THREAD

**Issue by nishtsha** [intel/intel-extension-for-pytorch#704]
### Describe the issue

I have ARC A770 graphics card on a ubuntu 22.04 host. I am trying to install pytorch and ipex using following command
`python3 -m pip install torch==2.3.1+cxx11.abi torchvision==0.18.1+cxx11.abi torchaudio==2.3.1+cxx11.abi intel-extension-for-pytorch==2.3.110+xpu oneccl_bind_pt==2.3.100+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/`

But I keep getting following error
![image](https://github.com/user-attachments/assets/b65cc5a3-1766-4a60-8723-941ff5bae4ed)

I am able to install other packages like numpy and matplotlib but no success with pytorch and ipex.

**Comment by devpramod** [comment]
@nishtsha Are you installing while connected to a VPN?
For a sanity check could you try:

`curl https://pytorch-extension.intel.com/release-whl/stable/xpu/us/`
