### ISSUE TITLE
`intel-extension-for-pytorch=2.3.110` package not available

### ISSUE THREAD

**Issue by idkSeth** [intel/intel-extension-for-pytorch#706]
### Describe the issue

Followed [installation instructions](https://intel.github.io/intel-extension-for-pytorch/#installation?platform=gpu&version=v2.3.110%2bxpu&os=linux%2fwsl2&package=conda) for my platform.

Ubuntu noble 24.04 x86_64
Conda Python 3.9

Conda gives me PackagesNotFoundError for `intel-extension-for-pytorch=2.3.110`

![image](https://github.com/user-attachments/assets/8aa7e3b6-d689-4d9c-81f0-71c839ed78e8)

**Comment by tye1** [comment]
Could you please try again? Conda package should be available now.
