### ISSUE TITLE
igpu 

### ISSUE THREAD

**Issue by ayttop** [intel/intel-extension-for-pytorch#714]
### Describe the issue

igpu  UHD 770

support?

**Comment by ZhaoqiongZ** [comment]
Hi @ayttop , UHD 770 is not officially supported yet.
along with release 2.3.110+xpu, we support Intel® Core™ Ultra Processors with Intel® Arc™ Graphics (MTL-H) & Intel® Core™ Ultra Series 2 with Intel® Arc™ Graphics https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.3.110%2bxpu&os=windows&package=pip
