### ISSUE TITLE
Difference between FusedMLP and MLP?

### ISSUE THREAD

**Issue by prmudgal** [intel/intel-extension-for-pytorch#715]
### Describe the issue

I see FusedMLP implmentation in the repo and I am trying to find the therory/explaination associated with this. Appreciate if somebody could mention the differences between FusedMLP and MLP or share some literature for this.

**Comment by ZhaoqiongZ** [comment]
Do you mean those fused kernels for MLP of different Large Language Models?

**Comment by ZhaoqiongZ** [comment]
close since no further comments
