### ISSUE TITLE
Any plans to add a vision language model (e.g. Llama 3.2)?

### ISSUE THREAD

**Issue by asmith26** [intel/intel-extension-for-pytorch#716]
Hi there,

Just wondering if you have plans to add fine-tuning/inference support of VLMs like Llama 3.2 (https://ai.meta.com/blog/llama-3-2-connect-2024-vision-edge-mobile-devices/)?

Many thanks for any help! :)

**Comment by ZailiWang** [comment]
We have supported Llama 3.2 VLM & LLM models. Please check the link: https://github.com/intel/intel-extension-for-pytorch/blob/2.6-llama-3/docs/index.md#211-run-vision-text-generation-with-llama-32-11b-models-using-bf16-autotp-tensor-parallel-on-multiple-cpu-numa-nodes

**Comment by asmith26** [comment]
Thanks for the info @ZailiWang is looks like this might only be for CPU (apologies if I'm misunderstanding)? Thanks again

**Comment by ZailiWang** [comment]
Hi @asmith26 , yes IPEX support for Llama3.2 is for CPU. Please check [this page](https://www.intel.com/content/www/us/en/developer/articles/technical/intel-ai-solutions-support-the-new-llama-3-2-model.html) for Gaudi or AIPC (Core Ultra or discrete Arc graphics) solutions. Thanks.
