### ISSUE TITLE
issue with IPEX v2.3.110 

### ISSUE THREAD

**Issue by wallacezq** [intel/intel-extension-for-pytorch#717]
### Describe the issue

Hi,

I encountered the after installing IPEX v2.3.110 following the guide from this [link ](https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.3.110%2bxpu&os=windows&package=pip)

system: MTL-H
OS: Windows 11
Python ver: 3.11
`
python -m pip install torch==2.3.1+cxx11.abi torchvision==0.18.1+cxx11.abi torchaudio==2.3.1+cxx11.abi intel-extension-for-pytorch==2.3.110+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/mtl/us/
`

I did not see similar issue with the version: v2.1.40+xpu.

The installation completed successfully, but running the sanity test throw the following error:
`
python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.__version__); print(ipex.__version__); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];
`
Console log:
 (Triggered internally at C:\Jenkins\workspace\IPEX-WW-BUILDS\frameworks.ai.pytorch.private-gpu\torch\csrc\utils\tensor_numpy.cpp:84.)
  values=torch.randn(3, 3, device="meta"),
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\MTL\miniconda3\envs\ipex_231\Lib\site-packages\intel_extension_for_pytorch\__init__.py", line 107, in <module>
    raise err
OSError: [WinError 193] %1 is not a valid Win32 application. Error loading "C:\Users\MTL\miniconda3\envs\ipex_231\Lib\site-packages\intel_extension_for_pytorch\bin\intel-ext-pt-gpu.dll" or one of its dependencies.

Please let me know how to resolve this. thanks.

regards,
Wallace

**Comment by jingxu10** [comment]
Did you run `conda install libuv`?

**Comment by 0Pinky0** [comment]
Related issue: https://github.com/intel/intel-extension-for-pytorch/issues/710
Looks like this problem happens on Windows with python version in [3.8, 3.9, 3.11].

**Comment by tye1** [comment]
@wallacezq  could you please verify if IPEX v2.3.110 hotfix patch resolves your issue?

please refer to the installation guide: https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.3.110%2bxpu&os=windows&package=pip.

# For Intel® Core™ Ultra Processors with Intel® Core™ Ultra Processors with Intel® Arc™ Graphics (MTL-H), use the commands below:
conda install libuv
python -m pip install torch==2.3.1.post0+cxx11.abi torchvision==0.18.1.post0+cxx11.abi torchaudio==2.3.1.post0+cxx11.abi intel-extension-for-pytorch==2.3.110.post0+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/mtl/us/

**Comment by wallace-lee** [comment]
Yes, it does. thanks
