### ISSUE TITLE
Error when transferring transformer model training to A770 graphics card

### ISSUE THREAD

**Issue by SoldierWz** [intel/intel-extension-for-pytorch#729]
### Describe the bug

<h1>Model Training Issue on Intel PyTorch with XPU Device - Native API Error</h1>

<h2>Description:</h2>

<p>Due to confidentiality reasons, I cannot upload my data. However, I have provided my code below, which works fine when using the CPU but encounters an issue when running on the <strong>XPU</strong> device.</p>

<h2>Environmental Information:</h2>

<ul>
<li><strong>Python Version:</strong> 3.10.15  </li>
<li><strong>PyTorch Version:</strong> 2.3.1+cxx11.abi  </li>
<li><strong>Warning Message:</strong>
<code>plaintext
UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\12710\.conda\envs\a770\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies).  
If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?  
</code></li>
<li><strong>Intel Extension for PyTorch Version:</strong> 2.3.110+xpu  </li>
</ul>

<h2>Code Snippet:</h2>

```
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset

data = pd.read_csv(r"###")
data['datas'] = data['datas'].apply(lambda x: np.array(eval(x)))

class TimeSeriesDataset(Dataset):
    def __init__(self, data, labels, max_length):
        self.data = data
        self.labels = labels
        self.max_length = max_length

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        series = self.data[idx]
        if len(series) < self.max_length:
            padded_series = np.pad(series, (0, self.max_length - len(series)), 'constant')
        else:
            padded_series = series[:self.max_length]
        return torch.tensor(padded_series, dtype=torch.float32), torch.tensor(self.labels[idx], dtype=torch.long)

max_length = max(data['datas'].apply(len))
y = data['label'].values
X_train, X_test, y_train, y_test = train_test_split(data['datas'], y, test_size=0.2, random_state=42)

train_dataset = TimeSeriesDataset(X_train.tolist(), y_train, max_length)
test_dataset = TimeSeriesDataset(X_test.tolist(), y_test, max_length)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

class TransformerClassifier(nn.Module):
    def __init__(self, input_dim, hidden_dim, n_heads, n_layers, n_classes):
        super(TransformerClassifier, self).__init__()
        self.hidden_dim = hidden_dim
        self.encoder_layers = nn.TransformerEncoderLayer(d_model=hidden_dim, nhead=n_heads, dim_feedforward=hidden_dim * 2, batch_first=True)
        self.transformer_encoder = nn.TransformerEncoder(self.encoder_layers, num_layers=n_layers)
        self.fc = nn.Linear(hidden_dim, n_classes)

    def forward(self, x):
        x = x.unsqueeze(-1).expand(-1, -1, self.hidden_dim)
        x = self.transformer_encoder(x)
        x = x.mean(dim=1)
        return self.fc(x)

device = torch.device("xpu")
import intel_extension_for_pytorch as ipex
model = TransformerClassifier(1, 64, 2, 2, len(np.unique(y_train))).to(device)
optimizer = optim.Adam(model.parameters(), lr=0.0001)
model, optimizer = ipex.optimize(model, optimizer=optimizer)
criterion = nn.CrossEntropyLoss().to(device)

epochs = 10
for epoch in range(epochs):
    model.train()
    running_loss = 0.0
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
        optimizer.step()
        running_loss += loss.item()
    print(f"Epoch {epoch + 1}/{epochs}, Loss: {running_loss / len(train_loader)}")

```
<h2>Error Message:</h2>
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[46], [line 30](vscode-notebook-cell:?execution_count=46&line=30)
     [28](vscode-notebook-cell:?execution_count=46&line=28) device = torch.device("xpu")
     [29](vscode-notebook-cell:?execution_count=46&line=29) import intel_extension_for_pytorch as ipex
---> [30](vscode-notebook-cell:?execution_count=46&line=30) model = TransformerClassifier(input_dim, hidden_dim, n_heads, n_layers, n_classes).to(device)
     [31](vscode-notebook-cell:?execution_count=46&line=31) optimizer = optim.Adam(model.parameters(), lr=0.0001)
     [32](vscode-notebook-cell:?execution_count=46&line=32) model, optimizer = ipex.optimize(model, optimizer=optimizer)

File c:\Users\12710\.conda\envs\a770\lib\site-packages\torch\nn\modules\module.py:1173, in Module.to(self, *args, **kwargs)
   [1170](file:///C:/Users/12710/.conda/envs/a770/lib/site-packages/torch/nn/modules/module.py:1170)         else:
   [1171](file:///C:/Users/12710/.conda/envs/a770/lib/site-packages/torch/nn/modules/module.py:1171)             raise
-> [1173](file:///C:/Users/12710/.conda/envs/a770/lib/site-packages/torch/nn/modules/module.py:1173) return self._apply(convert)

File c:\Users\12710\.conda\envs\a770\lib\site-packages\torch\nn\modules\module.py:779, in Module._apply(self, fn, recurse)
    [777](file:///C:/Users/12710/.conda/envs/a770/lib/site-packages/torch/nn/modules/module.py:777) if recurse:
    [778](file:///C:/Users/12710/.conda/envs/a770/lib/site-packages/torch/nn/modules/module.py:778)     for module in self.children():
--> [779](file:///C:/Users/12710/.conda/envs/a770/lib/site-packages/torch/nn/modules/module.py:779)         module._apply(fn)
    [781](file:///C:/Users/12710/.conda/envs/a770/lib/site-packages/torch/nn/modules/module.py:781) def compute_should_use_set_data(tensor, tensor_applied):
    [782](file:///C:/Users/12710/.conda/envs/a770/lib/site-packages/torch/nn/modules/module.py:782)     if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    [783](file:///C:/Users/12710/.conda/envs/a770/lib/site-packages/torch/nn/modules/module.py:783)         # If the new tensor has compatible tensor type as the existing tensor,
    [784](file:///C:/Users/12710/.conda/envs/a770/lib/site-packages/torch/nn/modules/module.py:784)         # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    [789](file:///C:/Users/12710/.conda/envs/a770/lib/site-packages/torch/nn/modules/module.py:789)         # global flag to let the user control whether they want the future
    [790](file:///C:/Users/12710/.conda/envs/a770/lib/site-packages/torch/nn/modules/module.py:790)         # behavior of overwriting the existing tensor or not.
...
   [1163](file:///C:/Users/12710/.conda/envs/a770/lib/site-packages/torch/nn/modules/module.py:1163)     )
   [1164](file:///C:/Users/12710/.conda/envs/a770/lib/site-packages/torch/nn/modules/module.py:1164) except NotImplementedError as e:
   [1165](file:///C:/Users/12710/.conda/envs/a770/lib/site-packages/torch/nn/modules/module.py:1165)     if str(e) == "Cannot copy out of meta tensor; no data!":

RuntimeError: Native API failed. Native API returns: -999 (Unknown PI error) -999 (Unknown PI error)

### Versions

StatusCode        : 200
StatusDescription : OK
Content           : # Referenced from https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py
                    # Run it with `python collect_env.py`.
                    import json
                    import locale
                    import re
                    import subprocess
                    import sys
                    impo...
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
                    Strict-Transport-Security: max-age=31536000
                    X-Content-Type-Options: nosniff
                    ...
Forms             : {}
Headers           : {[Connection, keep-alive], [Content-Security-Policy, default-src 'none'; style-src 'unsafe-inline';
                     sandbox], [Strict-Transport-Security, max-age=31536000], [X-Content-Type-Options, nosniff]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 17618

**Comment by huiyan2021** [comment]
Hi @SoldierWz , I tried below code and it passed at my side

![image](https://github.com/user-attachments/assets/91d4ecfc-7e5c-464c-bddc-096d80bdf5e9)

![image](https://github.com/user-attachments/assets/ced193a9-f76e-44b3-a6d9-c018e8f74148)

Could you run `conda list` in your environment and paste the output here?

**Comment by SoldierWz** [comment]
I tried some more and I think this may not be a problem with intel-extension-for-pytorch, because I found that it can run on the graphics card after trying to reduce the parameters. This is probably because my parameters are adjusted too large, causing the video memory to overflow. If this is the case, I am sorry to submit this issue, and I will close it.

**Comment by SoldierWz** [comment]
I tried changing to an LSTM network with only one layer, and then the moment I started training my computer screen went black, and the display settings seemed to have been restored to default, because the eye protection mode I had turned on was turned off after the black screen, and then the same error was output.

**Comment by huiyan2021** [comment]
Could you share the code so that I can reproduce at my side?

**Comment by SoldierWz** [comment]
> Could you share the code so that I can reproduce at my side?

I think you can just let GPT generate an LSTM network and put it on the graphics card to train it.

**Comment by huiyan2021** [comment]
Hi @SoldierWz , I can run LSTM without any issues on Arc770.

**Comment by SoldierWz** [comment]
> Hi @SoldierWz , I can run LSTM without any issues on Arc770.

Sorry, I think I didn't restart the environment to clean up the cache, which caused the error in the case of small models. I have also tried various large models recently and they can run on the GPU. I think the problem is the problem of video memory overflow, sorry.
