### ISSUE TITLE
ipex co-operate with pytorch-cuda

### ISSUE THREAD

**Issue by lam-mini** [intel/intel-extension-for-pytorch#730]
Is it possible to use both MTL-H's iGPU by ipex and pytorch for NVIDIA's discrete GPU at the same time?
If possible, how to install and set environment?

**Comment by xiguiw** [comment]
> Is it possible to use both MTL-H's iGPU by ipex and pytorch for NVIDIA's discrete GPU at the same time? If possible, how to install and set environment?

What do you mean by iGPU and NV GPU work at the same time?
1) both iGPU and NV work independently, but at the same time, 
2) or both hardware work together to complete a task.

We never try that case. And we do not encourage to do this.
Both of them race the memory capacity, memory bandwidth and host cpu computing resources. That make their performance drop a lot.

**Comment by lam-mini** [comment]
Hi, @xiguiw,
Thanks for your reply. I mean the latter case you mentioned. As the document shows that iGPU has good performance. I wonder if it's possible to let iGPU share part of the computation in a complex task with the discrete GPU. So  I'm curious whether it is possible to introduce ipex in the torch cuda version.

**Comment by xiguiw** [comment]
Hi @lam-mini,

No one had ever tried such case.

For iGPU, just use IPEX interface to use it.

**Comment by lam-mini** [comment]
Ok, I get it. Thanks for your reply.
