### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'generate'

### ISSUE THREAD

**Issue by mlc168219** [intel/intel-extension-for-pytorch#738]
### Describe the bug

My code below:
```
from transformers import AutoModelForCausalLM, AutoTokenizer, TextStreamer
import time
import intel_extension_for_pytorch as ipex
import torch

device = "cpu"

model = AutoModelForCausalLM.from_pretrained("mistralai/Mistral-7B-Instruct-v0.1")
model = ipex.llm.optimize(model.eval(), torch.bfloat16)
tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-Instruct-v0.1")

messages = [
    {"role": "user", "content": "What is your favourite condiment?"}
]

start_time = time.time()
encodeds = tokenizer.apply_chat_template(messages, return_tensors="pt")

model_inputs = encodeds.to(device)
#model.to(device)

generated_ids = model.generate(model_inputs, max_new_tokens=100, do_sample=True)

decoded = tokenizer.batch_decode(generated_ids)
```
Error happens in: generated_ids = model.generate(model_inputs, max_new_tokens=100, do_sample=True)
AttributeError: 'tuple' object has no attribute 'generate'

```
Please help me to solve the issue.
Thanks!

### Versions

```
python 3.10
intel_extension_for_pytorch        2.3.100+cpu
tokenizers                         0.20.3
torch                              2.3.1
torchaudio                         2.3.1
torchvision                        0.18.1
```

**Comment by ZhaoqiongZ** [comment]
Hi @mlc168219, thank you for reporting it.
a little change in the line ``` ipex.llm.optimize``` will fix the issue
`
from transformers import AutoModelForCausalLM, AutoTokenizer, TextStreamer
import time
import intel_extension_for_pytorch as ipex
import torch

device = "cpu"

model = AutoModelForCausalLM.from_pretrained("mistralai/Mistral-7B-Instruct-v0.1")
model = ipex.llm.optimize(model.eval(), dtype=torch.bfloat16)
tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-Instruct-v0.1")

messages = [
    {"role": "user", "content": "What is your favourite condiment?"}
]

start_time = time.time()
encodeds = tokenizer.apply_chat_template(messages, return_tensors="pt")

model_inputs = encodeds.to(device)
#model.to(device)

generated_ids = model.generate(model_inputs, max_new_tokens=100, do_sample=True)

decoded = tokenizer.batch_decode(generated_ids)
`

**Comment by winniechj** [comment]
@ZhaoqiongZ , Thank you so much! The issue can be closed.
