### ISSUE TITLE
Possible typo? in FindAVX.cmake

### ISSUE THREAD

**Issue by Nor7th** [intel/intel-extension-for-pytorch#741]
https://github.com/intel/intel-extension-for-pytorch/blob/main/cmake/Modules/FindAVX.cmake#L144C1-L148C14

Shouldn’t the **if** case use `CHECK_CXX_SOURCE_COMPILES` rather than `CHECK_C_SOURCE_COMPILES`? A typo?

**Comment by ZailiWang** [comment]
Thanks for reporting, it is indeed a typo. We'll fix it.

**Comment by ZailiWang** [comment]
Fixed by https://github.com/intel/intel-extension-for-pytorch/commit/95ea987c3d5e8277e21028738e0035600dbf9228
