### ISSUE TITLE
when run llama2-7b use intel_extension_for_pytorch and transformers :error  key_states, value_states = past_key_values[layer_idx] ValueError: too many values to unpack (expected 2) 

### ISSUE THREAD

**Issue by shawnnjupt** [intel/intel-extension-for-pytorch#744]
### Describe the bug

**my code**
![image](https://github.com/user-attachments/assets/228221f8-e9d3-407d-a65c-ec1ec32c65e8)
in test_llama2.py ,like

```
import torch
#################### code changes ####################  
import intel_extension_for_pytorch as ipex
######################################################  
import argparse
from modeling_llama import LlamaForCausalLM 
from transformers import(
    LlamaTokenizer,
    # LlamaForCausalLM,
)


model_id = "/home/congxiao/model/llama2_7b_hf"
tokenizer = LlamaTokenizer.from_pretrained(model_id, cache_dir=None,trust_remote_code=False)
model = LlamaForCausalLM.from_pretrained(model_id,cache_dir=None,trust_remote_code=False)

model_ipex = ipex.llm.optimize(model, dtype=torch.int8)

inputs = tokenizer(
    "No one's born being good at all things. \
    You definitely have to do a few drafts of a paper before",return_tensors="pt") 

print(inputs.input_ids.size())

generate_ids = model_ipex.generate(inputs.input_ids,max_new_tokens=4)#use_cache=False

print(tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0])
```
this modeling_llama.py is cloned from transformers source code (i want to customize this file ,for example add some print sentence)
`from modeling_llama import LlamaForCausalLM `

when i python test_llama2.py

error like 
```
(ipex) congxiao@test-SYS-741GE-TNRT:~/code/python/llama2/2-7b/vtune_llama/amx_version$ python test_llama2.py 
/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.78it/s]
[INFO] SINGLE_INSTANCE MODE.
Traceback (most recent call last):
  File "/home/congxiao/code/python/llama2/2-7b/vtune_llama/amx_version/test_llama2.py", line 17, in <module>
    model_ipex = ipex.llm.optimize(model, dtype=torch.int8)
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/intel_extension_for_pytorch/transformers/optimize.py", line 1481, in optimize
    _model = model_convert_lowering(
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/intel_extension_for_pytorch/transformers/optimize.py", line 1140, in model_convert_lowering
    trace_model = torch.jit.trace(
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/intel_extension_for_pytorch/jit/_trace.py", line 69, in wrapper
    traced = f(*args, **kwargs)
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/jit/_trace.py", line 820, in trace
    return trace_module(
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/jit/_trace.py", line 1076, in trace_module
    module._c._create_method_from_trace_with_dict(
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1522, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/congxiao/code/python/llama2/2-7b/vtune_llama/amx_version/modeling_llama.py", line 1174, in forward
    outputs = self.model(
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1522, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/congxiao/code/python/llama2/2-7b/vtune_llama/amx_version/modeling_llama.py", line 1000, in forward
    past_key_values = DynamicCache.from_legacy_cache(past_key_values)
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/transformers/cache_utils.py", line 163, in from_legacy_cache
    key_states, value_states = past_key_values[layer_idx]
ValueError: too many values to unpack (expected 2)
(ipex) congxiao@test-SYS-741GE-TNRT:~/code/python/llama2/2-7b/vtune_llama/amx_version$ 

### Versions

my env list below:
```

(ipex) congxiao@test-SYS-741GE-TNRT:~/code/python/llama2/2-7b/vtune_llama/amx_version$ pip list
Package                     Version
--------------------------- -----------
asttokens                   3.0.0
certifi                     2024.8.30
charset-normalizer          3.4.0
comm                        0.2.2
debugpy                     1.8.9
decorator                   5.1.1
exceptiongroup              1.2.2
executing                   2.1.0
filelock                    3.16.1
fsspec                      2024.10.0
huggingface-hub             0.26.5
idna                        3.10
importlib_metadata          8.5.0
intel-extension-for-pytorch 2.3.0
ipykernel                   6.29.5
ipython                     8.18.1
jedi                        0.19.2
Jinja2                      3.1.4
jupyter_client              8.6.3
jupyter_core                5.7.2
MarkupSafe                  3.0.2
matplotlib-inline           0.1.7
mpmath                      1.3.0
nest_asyncio                1.6.0
networkx                    3.2.1
numpy                       2.0.2
nvidia-cublas-cu12          12.1.3.1
nvidia-cuda-cupti-cu12      12.1.105
nvidia-cuda-nvrtc-cu12      12.1.105
nvidia-cuda-runtime-cu12    12.1.105
nvidia-cudnn-cu12           8.9.2.26
nvidia-cufft-cu12           11.0.2.54
nvidia-curand-cu12          10.3.2.106
nvidia-cusolver-cu12        11.4.5.107
nvidia-cusparse-cu12        12.1.0.106
nvidia-nccl-cu12            2.20.5
nvidia-nvjitlink-cu12       12.4.127
nvidia-nvtx-cu12            12.1.105
oneccl-bind-pt              2.5.0+cpu
packaging                   24.2
parso                       0.8.4
pexpect                     4.9.0
pickleshare                 0.7.5
pillow                      11.0.0
pip                         24.2
platformdirs                4.3.6
prompt_toolkit              3.0.48
psutil                      6.1.0
ptyprocess                  0.7.0
pure_eval                   0.2.3
Pygments                    2.18.0
pyitt                       1.7.2
python-dateutil             2.9.0.post0
PyYAML                      6.0.2
pyzmq                       26.2.0
regex                       2024.11.6
requests                    2.32.3
safetensors                 0.4.5
sentencepiece               0.2.0
setuptools                  75.1.0
six                         1.17.0
stack_data                  0.6.3
sympy                       1.13.1
tokenizers                  0.15.2
torch                       2.3.0
torchaudio                  2.3.0
torchvision                 0.18.0
tornado                     6.4.2
tqdm                        4.67.1
traitlets                   5.14.3
transformers                4.36.0
triton                      2.3.0
typing_extensions           4.12.2
urllib3                     2.2.3
wcwidth                     0.2.13
wheel                       0.44.0
zipp                        3.21.0
(ipex) congxiao@test-SYS-741GE-TNRT:~/code/python/llama2/2-7b/vtune_llama/amx_version$ 
```

i also use intel-extension-for-pytorch==2.2 or ==2.4  
transformers==4.38.0 or ==4.39.0 or ==4.44.0 or ==4.45.0
the same error ,so i think it is not the version makes this problem
**so who can help me? thaks very much**

**Comment by ZailiWang** [comment]
Hi `ipex.llm.optimize` makes some changes for further performance optimization (e.g. re-written forward function for Llama is [here](https://github.com/intel/intel-extension-for-pytorch/blob/v2.5.0%2Bcpu/intel_extension_for_pytorch/transformers/models/reference/models.py#L300) ), so it does not work with the modeling file in original transformers.

We suggest to use the [LLM examples](https://github.com/intel/intel-extension-for-pytorch/tree/v2.5.0%2Bcpu/examples/cpu/llm) to quickly benchmark the performance as well as study the example scripts about how to do LLM optimizations with IPEX.

**Comment by shawnnjupt** [comment]
> Hi makes some changes for further performance optimization (e.g. re-written forward function for Llama is [here](https://github.com/intel/intel-extension-for-pytorch/blob/v2.5.0%2Bcpu/intel_extension_for_pytorch/transformers/models/reference/models.py#L300) ), so it does not work with the modeling file in original transformers.`ipex.llm.optimize`
> 
> We suggest to use the [LLM examples](https://github.com/intel/intel-extension-for-pytorch/tree/v2.5.0%2Bcpu/examples/cpu/llm) to quickly benchmark the performance as well as study the example scripts about how to do LLM optimizations with IPEX.

**Comment by shawnnjupt** [comment]
> Hi `ipex.llm.optimize` makes some changes for further performance optimization (e.g. re-written forward function for Llama is [here](https://github.com/intel/intel-extension-for-pytorch/blob/v2.5.0%2Bcpu/intel_extension_for_pytorch/transformers/models/reference/models.py#L300) ), so it does not work with the modeling file in original transformers.
> 
> We suggest to use the [LLM examples](https://github.com/intel/intel-extension-for-pytorch/tree/v2.5.0%2Bcpu/examples/cpu/llm) to quickly benchmark the performance as well as study the example scripts about how to do LLM optimizations with IPEX.

Thanks for replying , so why i use api from transformers ,
for example 
```
from transformers import(
    LlamaTokenizer,
     LlamaForCausalLM,
)
model_id = "/home/congxiao/model/llama2_7b_hf"
tokenizer = LlamaTokenizer.from_pretrained(model_id, cache_dir=None,trust_remote_code=False)
model = LlamaForCausalLM.from_pretrained(model_id,cache_dir=None,trust_remote_code=False)
model_ipex = ipex.llm.optimize(model, dtype=torch.int8)
```

 this  ipex.llm.optimize can work
compared to i clone source code(modeling_llama.py) from transformers to my work directory, and i use it in my work directory like 
```
from modeling_llama import LlamaForCausalLM 
from transformers import( 
    LlamaTokenizer,
)
model_id = "/home/congxiao/model/llama2_7b_hf"
tokenizer = LlamaTokenizer.from_pretrained(model_id, cache_dir=None,trust_remote_code=False)
model = LlamaForCausalLM.from_pretrained(model_id,cache_dir=None,trust_remote_code=False)
model_ipex = ipex.llm.optimize(model, dtype=torch.int8)

```
in my knowledge ,api and source code, i think they are the same.
so why source code not work?

**Comment by shawnnjupt** [comment]
> Hi `ipex.llm.optimize` makes some changes for further performance optimization (e.g. re-written forward function for Llama is [here](https://github.com/intel/intel-extension-for-pytorch/blob/v2.5.0%2Bcpu/intel_extension_for_pytorch/transformers/models/reference/models.py#L300) ), so it does not work with the modeling file in original transformers.
> 
> We suggest to use the [LLM examples](https://github.com/intel/intel-extension-for-pytorch/tree/v2.5.0%2Bcpu/examples/cpu/llm) to quickly benchmark the performance as well as study the example scripts about how to do LLM optimizations with IPEX.

Thanks for replying , so why i use api from transformers ,
for example
```

from transformers import(
    LlamaTokenizer,
     LlamaForCausalLM,
)
model_id = "/home/congxiao/model/llama2_7b_hf"
tokenizer = LlamaTokenizer.from_pretrained(model_id, cache_dir=None,trust_remote_code=False)
model = LlamaForCausalLM.from_pretrained(model_id,cache_dir=None,trust_remote_code=False)
model_ipex = ipex.llm.optimize(model, dtype=torch.int8)
```
this ipex.llm.optimize can work
compared to i clone source code(modeling_llama.py) from transformers to my work directory, and i use it in my work directory like

```
from modeling_llama import LlamaForCausalLM 
from transformers import( 
    LlamaTokenizer,
)
model_id = "/home/congxiao/model/llama2_7b_hf"
tokenizer = LlamaTokenizer.from_pretrained(model_id, cache_dir=None,trust_remote_code=False)
model = LlamaForCausalLM.from_pretrained(model_id,cache_dir=None,trust_remote_code=False)
model_ipex = ipex.llm.optimize(model, dtype=torch.int8)
```

in my knowledge ,api and source code, i think they are the same.
so why source code not work?

**Comment by ZailiWang** [comment]
`ipex.llm.optimize` is a model level API tailored for `transformers` package. From source code perspective, the implementation of the API is hard-coded to be dependent on interfaces from `transformers` package.
A few examples:
https://github.com/intel/intel-extension-for-pytorch/blob/main/intel_extension_for_pytorch/transformers/optimize.py#L473
https://github.com/intel/intel-extension-for-pytorch/blob/main/intel_extension_for_pytorch/transformers/optimize.py#L578

**Comment by shawnnjupt** [comment]
> `ipex.llm.optimize`是为 package 量身定制的模型级 API。从源代码的角度来看，API 的实现是硬编码的，以依赖于 package 中的接口。几个示例：https://github.com/intel/intel-extension-for-pytorch/blob/main/intel_extension_for_pytorch/transformers/optimize.py#L473 https://github.com/intel/intel-extension-for-pytorch/blob/main/intel_extension_for_pytorch/transformers/optimize.py#L578`transformers``transformers`

thanks for replying,so if i want to modify llama model to add something(for example add some print sentences),how can i use ipex to run my new model

**Comment by ZailiWang** [comment]
If only some logging lines, you can directly add them in the python file in the `transformers` package.
If you need to experiment some model architectural change and would like to optimize with IPEX, please refer to [the module level API for LLM](https://github.com/intel/intel-extension-for-pytorch/tree/main/examples/cpu/inference/python/llm-modeling). Specifically, there is a `modeling_llama.py` as a sample for code change in this directory, you can do the changings based on that.
