### ISSUE TITLE
enable slice semantics

### ISSUE THREAD

**Issue by pinzhenx** [intel/intel-extension-for-pytorch#98]
For bf16, we may support slicing in such a way:

A tensor slice like `a[4:8, 4:8, 4:8, 4:8]` will call the `slice()` by four times, and in the first call to the `slice()`, we could convert the whole buffer to bf16, and all subsequent calls will only change its shape info.

This way, no matter users are reading or writing a submemory, we don't have to worry about writing a bf16 tensor back to original buffer, as the whole buffer has already been bf16 as well.

**Caveats:**

1. This approach assumes that when a user is using a part of memory, he/she is also going to use the remaining part sooner or later. To put it another way, if the user will only use part of a memory, why would he/she allocate the whole buffer in the first place? (_Correct me if I'm wrong_)

2. Since DNNL may not optimize or even correctly handle non-contiguous tensors for all situations ([check this](https://github.com/oneapi-src/oneDNN/issues/731)). We may still need contiguous checks in `slice()`, that is, we are not going to fully support slicing semantics.

**Comment by pinzhenx** [comment]
As the first step, we need to make a clear distinction between two roles of DIL tensors in our integration

1. DIL tensor as a storage
This DIL tensor should always be contiguous because it's a storage. It's the one we stored in shade data conext.

2. DIL tensor as a tensor wrapper
In ops implementation, each time we call `try_gen_dil_tensor`, it should always return a new DIL tensor with shape info stored in `TensorImpl`, instead of returning that storage DIL tensor. So that we could create a view on both CPU storages and DIL storages, and no longer need to worry about shape mismatch.

On top of that, we could further implement bf16 slicing semantics as follows:

`reorder_to_bf16_for_mix_prec` and `reorder_to_public` should always convert the DIL storage to expected format or data type, not just convert the part of tensor described by the tensor wrapper.

**Comment by EikanWang** [comment]
We switched the underhood device to CPU. And the activation is always plain format while only the weight will be blocked format. The slice semantics are as same as PyTorch CPU now.
